### ISSUE TITLE
Fly problems

### ISSUE THREAD

**Issue by Shadow232** [DivineRPG/DivineRPG#104]
Hey, i dont think that is is hot problem, but still have some issues with plugins. Server plugin such as essentials can`t get information ( dont work/answer ) about fly ( command /fly ) :) It will be good if you fix it ^_^

**Comment by Eternaldoom** [comment]
Quite difficult. I'll try though.

**Comment by Shadow232** [comment]
i noticed 1 think, then i use command /fly i get fly for 0.5 and after that reset ...

**Comment by badtzmaru** [comment]
I also noticed that when you have morph installed, you cannot fly using the bat or other flying morphs

**Comment by Shadow232** [comment]
i think solution of this problem trying to add permission...
