### ISSUE TITLE
How do you get beta builds, i would like to test some bugs

### ISSUE THREAD

**Issue by MasterArt** [DivineRPG/DivineRPG#107]
The name says it, btw love the mod

**Comment by krwminer** [comment]
Use the current github repository. I copied another mods gradle build script and modified it for DRPG.

**Comment by MasterArt** [comment]
k thanks

**Comment by MasterArt** [comment]
i used the repository and it didnt work

**Comment by Shadow232** [comment]
than wait official release :)

**Comment by Eternaldoom** [comment]
Yeah. There are plenty of tutorials on how to build a mod. Beta builds won't be made readily available to prevent what happened with the 1.6.4 beta.

**Comment by MasterArt** [comment]
is there going to be a 1.7.10 version?

**Comment by Eternaldoom** [comment]
Yes, the mod is currently being developed for 1.7.10
