### ISSUE TITLE
Rupee, Realmite and Arlemite Ores not TNT proof

### ISSUE THREAD

**Issue by krwminer** [DivineRPG/DivineRPG#112]
In 1.4.7 Rupee, Realmite and Arlemite Ores were TNT proof. They all get destroyed in the current version.

**Comment by RadioactiveStud** [comment]
For the record, this was implemented but *someone* removed it and I didn't notice.

**Comment by krwminer** [comment]
lol. I do not know the history. One of my testers reported it and I checked it on 1.4.7 before reporting it. Thanks.
