### ISSUE TITLE
DivineRPG Wiki

### ISSUE THREAD

**Issue by krwminer** [DivineRPG/DivineRPG#114]
O.K. I have struggled for a while now without access to the official wiki for DRPG. Time to make it an "issue" placeholder.

**Comment by Eternaldoom** [comment]
The host of the wiki (sactage, a member of the old team), has decided to stop hosting it and not reply on skype. We're trying to get the files and hopefully move it to a new host. However, this isnt a mod dev issue so it'd probably be better to PM me on mc forums for things like this
