### ISSUE TITLE
Shift-Click does not work with DRPG Furnaces

### ISSUE THREAD

**Issue by krwminer** [DivineRPG/DivineRPG#115]

**Comment by krwminer** [comment]
So are all the Iceika furnaces suppose to take a single item at a time and cook it slowly without any fuel?

**Comment by Eternaldoom** [comment]
Well there's only one iceika one and several arcana ones, but yes. Some might be changed in the future.

**Comment by krwminer** [comment]
Sorry I meant all the Infinite Furnaces.
One item at a time? I do not see much use in that, if it already is much slower to smelt.
Why would anyone use one?

**Comment by krwminer** [comment]
Anyway, if you want to keep it one item at a time, I will change the issue name, because you can drag and drop a stack of items right now. Using shift-click limits it to one at a time.
Also I plan to add the check for whether an item stack can be smelted to make it operate smarter.

**Comment by Eternaldoom** [comment]
Oh I see what you mean. No it should be a whole stack.

**Comment by krwminer** [comment]
OK. I will fix furnace containers by removing the limit of one item shift-click and making them smarter about smeltable items with shift-click.

**Comment by krwminer** [comment]
You have a lot of links to ContainerModFurnace, but it looks like really only ContainerExtractor uses it right now.

Under the assumption that the Extractor only takes Arcanium Ore for smelting and Charged Collectors for fuel, I need to make its own unique transferStackInSlot() function.

So ContainerExtractor needs to be a separate class. Do we still want to keep the ContainerModFurnace class and all of its hooks?

**Comment by Eternaldoom** [comment]
Probably, since it will be useful if any furnaces are changed in the future.

**Comment by krwminer** [comment]
O.K. That is done right now. Still checking into other possible issues with the furnaces. Shift-Clicking is working and doing the right thing with all the furnaces and the Extractor.

**Comment by krwminer** [comment]
Yikes. The furnaces are all over the place in 1.4.7...

Demon - Burn time 5 seconds, Fuel slot but no fuel needed.
Coalstone - Burn time 50 seconds, no fuel
Oceanfire - Burn time 10 seconds
Molten - Burn time 16 seconds
Whitefire - Burn time 7 seconds

Currently all the furnaces are set to 15 seconds burn time.

Do you want me to change anything?

**Comment by Eternaldoom** [comment]
You can if you want.

**Comment by krwminer** [comment]
I had an idea of something to do with the Demon furnace... Make it smelt at the nice fast rate of 5 seconds, but also have a chance to have surrounding blocks catch fire.

I am running into render issues with the furnaces that I will try and tackle tonight.

**Comment by RadioactiveStud** [comment]
Go for it.
