### ISSUE TITLE
Suggestion: Add recipes from twilight blocks back to fragments

### ISSUE THREAD

**Issue by krwminer** [DivineRPG/DivineRPG#125]
I will be glad to do it, just want your O.K.

**Comment by krwminer** [comment]
I forgot about portal farming. What about just for Mortum blocks?

**Comment by Eternaldoom** [comment]
That'd be inconsistent. Maybe ill add versions of the blocks that only spawn as portals and are useless.

**Comment by krwminer** [comment]
That would work. One of my big concerns is that people make a bunch of Sky blocks only to find out you need 3 for the bed, since the portal is different.

**Comment by krwminer** [comment]
Once you activate a portal turn the blocks you activated into the "new and useless" portal blocks.

**Comment by krwminer** [comment]
I changed my mind about this one. Feel free to re-open if you think it is worth it.
