### ISSUE TITLE
Arcana problems

### ISSUE THREAD

**Issue by krwminer** [DivineRPG/DivineRPG#126]
No portal was created on the Arcana side.
Appeared in the middle of fire traps blocks.
Spawners get broken with a single hit. - Fixed
Spawners are not generating any mobs.

**Comment by krwminer** [comment]
What about having a single specific "portal room" generate in arcana and always link that portal?

**Comment by krwminer** [comment]
Hmm. It looks like Arcana spawners got destroyed from a single hit with just you hand. Was that a bug or was it intended?

**Comment by Eternaldoom** [comment]
Bug. They should be unbreakable.

**Comment by krwminer** [comment]
Is that true of all arcana blocks?

**Comment by Eternaldoom** [comment]
Not arcanite tubes, but yes to everything else

**Comment by krwminer** [comment]
Whenever we set a block to UnBreakable should we by default set it also to have a blast resistance to 18,000,000?

**Comment by Eternaldoom** [comment]
Yeah

**Comment by krwminer** [comment]
What do you think about the portal room gen? I think it would be a nice solution to the portal glitches that occur in Arcana.

**Comment by Eternaldoom** [comment]
Maybe. It would have to be at the same chunk coords as the portal in the overworld.

**Comment by krwminer** [comment]
Hmm. Why the same?

**Comment by Eternaldoom** [comment]
When sending the player back, there's no way to easily save where the overworld portal is

**Comment by krwminer** [comment]
NBT field on the player.dat?

**Comment by krwminer** [comment]
Spawners created by the Arcana worldgen emit particles, but do not spawn mobs. If in creative you destroy the spawner and replace it, it will spawn mobs.

**Comment by ShadowOfStrelok** [comment]
Guys, I'm a little off topic, but do you have the source code of the old divine RPG on github? I have a guess as to correct a surprising number of bugs, including vethea crash in multiplayer, and crash when killing Ender-triplets with the sword.

**Comment by Eternaldoom** [comment]
No. All we have is the decompiled src. Besides, the old version won't be updated. 1.4.7 is just way too old

**Comment by Eternaldoom** [comment]
I cant reproduce this issue. They spawn mobs fine for me. Are you sure you didnt just not wait long enough?

**Comment by krwminer** [comment]
I waited long enough. (Just to be sure I waited a good ten minutes). I am talking about the BlockStupidSpawner blocks not spawning, the "trader creatures" spawn as they should.

I spent quite a bit of time in eclipse on this. It looked like by using the setBlock() functions from ArcanaChunk rather than the one from the worldObj, the server side misses getting the TileEntity registered. So you see the spawners "particles" in TileEntityStupidSpawner.updateEntity() because the client side is O.K., but it never enters the "if(!this.worldObj.isRemote) {" server side part that deals with the spawnTimer because the server side does not know about the TileEntity.

If for some reason you are seeing the BlockStupidSpawner working in Arcana, we need to figure out what is different.

**Comment by Eternaldoom** [comment]
Yeah I've seen them work. There's no reason it wouldn't update server side. Have you tried multiple types of spawners?

**Comment by krwminer** [comment]
Yes. All of them fail. When I place a spawner it works. :/

**Comment by krwminer** [comment]
When should it update the server side?

**Comment by krwminer** [comment]
I just ran the latest pull with the latest Forge in eclipse. Same problem. I will PM you a dropbox of the jar file I just built which also shows the problem.

**Comment by Eternaldoom** [comment]
Yeah I was able to reproduce this in the copy of the jar you sent me. Did you change anything related to the spawner flames? They seem a lot faster in that version.

**Comment by krwminer** [comment]
All environments, dev and obfuscated versions. I have been trying to figure out the problem in eclipse that is why I gave so much info on what I observed above. I did not change anything from the github pull. As a matter of fact a did a full clean re-install of Forge/Eclipse to the latest version and then did a clean pull from github and then ran it from eclipse.

**Comment by RadioactiveStud** [comment]
I am getting the same problem as @krwminer. 
Dev environment, Forge 1230, Linux.

**Comment by krwminer** [comment]
So I am not going crazy... That is good to hear.

**Comment by Shadow232** [comment]
UP arcana spawners can`t be destroyed...

**Comment by Eternaldoom** [comment]
They aren't meant to be.

**Comment by krwminer** [comment]
I am sure I am stating to obvious, but you tried this on a new world right when you said you see them spawning? (Just trying to figure this out).

**Comment by Eternaldoom** [comment]
Yeah. I'll keep trying to reproduce this.

**Comment by krwminer** [comment]
Would it help to zip up my dev environment and dropbox it too you?
