### ISSUE TITLE
TileEntityStupidSpawner does not check if someone is near it

### ISSUE THREAD

**Issue by krwminer** [DivineRPG/DivineRPG#131]
Doesn't this mean that it will spawn all the time until the area is full of mobs?

In the Overworld this makes it easy to setup mob grinders.
In Arcana this could be a big problem as there are so many spawners.

**Comment by Eternaldoom** [comment]
Well you can't obtain them to make overworld grinders. They don't spawn if there are greater than 6 (I think) mobs near them. I guess it couldn't hurt to add a required player radius.

**Comment by krwminer** [comment]
They are used in in the Divine Dungeons, that was what I meant for Overworld Grinders.

**Comment by Eternaldoom** [comment]
Whoops. Yeah I'll definitely fix this.

**Comment by krwminer** [comment]
Also minor coding point, but it is best to not even start the spawning check loops if c > 8.
And you might want to use the bounds check like the one from EntityLiving to make sure you do not spawn things in walls:
        return this.worldObj.checkNoEntityCollision(this.boundingBox) && this.worldObj.getCollidingBoundingBoxes(this, this.boundingBox).isEmpty() && !this.worldObj.isAnyLiquid(this.boundingBox);
