### ISSUE TITLE
Crash mob

### ISSUE THREAD

**Issue by Shadow232** [DivineRPG/DivineRPG#134]
In default world i get crash log:

url - http://pastebin.com/FSEvc4WA

**Comment by Eternaldoom** [comment]
I haven't had this crash, and I think @krwminer said ayeracos are fine in the compiled version, so I'm not sure what the problem is. We can't really trust crash reports from cauldron servers though, since cauldron modifies a lot of stuff.

**Comment by Shadow232** [comment]
hmm, but is it right, that we can summon horde ( by horde horn ) in main world ? ( not in ender ) and when i hit him it get crash..

**Comment by krwminer** [comment]
I did not experience a crash with the ayeracos when I spawned them in the End. They did act funny about not coming down. I was not sure if it was a creative mode thing.

I did not try spawning them in the Overworld. That should not be allowed as far as I know.

**Comment by Shadow232** [comment]
with spawn no problem, but after 1 hit...

**Comment by RadioactiveStud** [comment]
Sense no one else can reproduce this, it's probably a conflict with another mod. Does it crash if you remove all your other mods?

**Comment by krwminer** [comment]
I tried this again. It did not let me spawn them in the Overworld. When I did spawn them in the End they worked fine. The only thing we may want to fix is that it is easy to get them to get stuck in endstone and suffocate. (I am adding a separate Issue for that).

**Comment by RadioactiveStud** [comment]
Closed until it can be reproduced.
