### ISSUE TITLE
Arcana needs a portal room.

### ISSUE THREAD

**Issue by krwminer** [DivineRPG/DivineRPG#140]
It is too easy to spawn in and be stuck, (no possible way to get to progress), because of random dungeon layout.

**Comment by krwminer** [comment]
I really think this is just a bug. Now that you can not use beds or TNT to open up passages, this becomes really important to fix.

**Comment by krwminer** [comment]
I may try and tackle this one soon. I might look into making a single portal room. If we have that it will be easy to trace and make sure the vital areas are present to allow a person to progress in Arcana. (Spawner, Extractor and Dramix Altar).

**Comment by Eternaldoom** [comment]
if a portal room has 4 doors, the likelyhood of being trapped is very small. the problem with arcana gen is that chunks dont have access to other chunks when generated, and using a lot of worldgen will make it laggy.

**Comment by krwminer** [comment]
You might be right, just making the portal room with 4 doors might be enough.
