### ISSUE TITLE
Should Charged Collectors be consumed in summoning?

### ISSUE THREAD

**Issue by krwminer** [DivineRPG/DivineRPG#143]
They do not in 1.4.7, but it is real easy to get as many keys as you want.

**Comment by RadioactiveStud** [comment]
Maybe it could have a durability of 5 or something?

**Comment by krwminer** [comment]
Hmm. Then can you use damaged collectors in the extractor? I think it would be better to have a different item, say "Glowing Collector" or "Sparking Collector", that can be traded for 3 collectors.

**Comment by RadioactiveStud** [comment]
>Then can you use damaged collectors in the extractor?
No.
But yeah I like the idea that it's a different item that you use on the alter than the extractor.

**Comment by RadioactiveStud** [comment]
Can reopen if what I did isn't good enough.

**Comment by krwminer** [comment]
No, it looks good. Thanks!
