### ISSUE TITLE
Shouldn't the color of the keys match the door for Arcana?

### ISSUE THREAD

**Issue by krwminer** [DivineRPG/DivineRPG#148]
I was fixing the keys to have the color names like in 1..4.7, rather than key1, key2, etc.
Then I noticed the color of the key does not match the color of the door. Should we either have the door color determine the key color or the other way around?

**Comment by Shadow232** [comment]
if look loogically, than yes :)

**Comment by RadioactiveStud** [comment]
Yeah sure.

**Comment by krwminer** [comment]
I am not good with textures, so I will let @RadioactiveStud or @Eternaldoom do this.

**Comment by Eternaldoom** [comment]
what do you think they should be called? there are 2 teal doors and 2 purple doors.

**Comment by krwminer** [comment]
Teal1 and Teal2, Purple1 and Purple2... lol. Just kidding.

**Comment by krwminer** [comment]
We could compromise and make colored keyholes in the doors, (Red, Yellow, etc.).

**Comment by Eternaldoom** [comment]
Nah, I have an idea for key names/textures
