### ISSUE TITLE
Speed boost not working on full armor sets

### ISSUE THREAD

**Issue by krwminer** [DivineRPG/DivineRPG#150]

**Comment by RadioactiveStud** [comment]
Works for me just fine in the dev environment.

**Comment by krwminer** [comment]
Several reports from people testing on my server. I have not confirmed myself. I will do so tonight to be sure.

**Comment by Eternaldoom** [comment]
this was only an smp issue.

**Comment by krwminer** [comment]
Why did you close this? Should we not look into fixing it?

**Comment by Eternaldoom** [comment]
I just fixed it

**Comment by krwminer** [comment]
Sorry, I just thought you closed it without fixing it. My mistake.
