### ISSUE TITLE
Jack-O-Man causes Iron Golem Wars

### ISSUE THREAD

**Issue by krwminer** [DivineRPG/DivineRPG#151]
The Jack-O-Man is somewhere between a villager and a mob. So when in the presence of one Iron Golem the Jack-O-Man is attacked by the Iron Golem. If in the presence of two Iron Golems, one will attack the Jack-O-Man and the second will attack the first Iron Golem for attacking the Jack-O-Man.
This goes on till there is but one Iron Golem left attacking the Jack-O-Man.

**Comment by RadioactiveStud** [comment]
That's new. :laughing:

**Comment by krwminer** [comment]
You have to try it. It is real fun to watch!

**Comment by krwminer** [comment]
If we remove IMob from EntityDivineRPGVillager it fixes this. Is there any harm in doing that?

**Comment by RadioactiveStud** [comment]
It shouldn't seeing as how it wasn't using any of IMob's variables anyway.
