### ISSUE TITLE
Need Instructions!

### ISSUE THREAD

**Issue by BIOSLuke** [DivineRPG/DivineRPG#153]
I don't know what version of minecraft this is for, if it needs to be copied into the game's version jar, or if it isn't meant for use. I really need some instructions because I'd like to play this mod.

**Comment by krwminer** [comment]
It is for 1.7.10. If you know enough to put together a gradle build for it, then you can make jar file.
We are testing and bug fixing right now for the official release.

**Comment by BIOSLuke** [comment]
thanks, been testing all the versions .6+ and wasn't getting anywhere. Wish I knew what a gradle is, and thanks for the help so fast.
