### ISSUE TITLE
Full set Armor Imune To Fire stuck on after removing armor.

### ISSUE THREAD

**Issue by krwminer** [DivineRPG/DivineRPG#156]
After putting on a full set of Bedrock/Netherite/Molten Armor and then removing it, the immunity to fire stays stuck on.

**Comment by Eternaldoom** [comment]
Probably gonna just fix this by making the armor apply fire resistance potion. That'll also fix #155.

**Comment by krwminer** [comment]
O.K.

**Comment by krwminer** [comment]
Hmm. I just noticed this in the wiki for potions:

"The maximum level an effect can have is level 255. Like any other normal potion effect, the effect completely wears off at the end of its duration. Unlike normal potion effects, potions with levels above 127 do not cause particle effects."

I wonder if we can use this to not make the Full Armor sets have potion effects for Night Vision and Fire Resistance.
