### ISSUE TITLE
gradle build help

### ISSUE THREAD

**Issue by TrueBlueCrafter** [DivineRPG/DivineRPG#157]
Sorry if this isn't the right place to post this, but I was trying to make this into a .jar, but I was having trouble on the final step with the mcmod.info. What do you all normally change on the build.gradle to compile the mod? I'm a little bit of a novice at this :D

**Comment by Eternaldoom** [comment]
I'm not sure exactly what the problem is, but there are plenty of tutorials out there on building a minecraft mod.

**Comment by RadioactiveStud** [comment]
Just made a little tutorial on how to build the mod at the bottom of the readme.
