### ISSUE TITLE
Tooltips, messages are hardcoded

### ISSUE THREAD

**Issue by Adaptivity** [DivineRPG/DivineRPG#158]
All tooltips and messages are hardcoded. So, there is no way to translate them. I can take a look at it but not now so maybe someone want to do it.

**Comment by Adaptivity** [comment]
You still not finished it. Look for *p.addChatMessage* in code, these messages should be localized.

**Comment by Eternaldoom** [comment]
If you want to make a list of messages and where they are, or submit a PR, I'd be happy to look at this. However, please realize that going through, finding every hardcoded string, and localizing it is no easy task, and simply saying "You still have not finished it" accomplishes literally nothing.

**Comment by sheenrox82** [comment]
He doesn't have to. We have lives. We have school, jobs, friends, and family. We are busy. If you want, submit a PR that goes through the entire code and localizes it.

**Comment by Adaptivity** [comment]
By "You still not finished it" I mean you shouldn't close this issue :) That's all, I know that everyone busy. I'm very busy right now too. So, I can't translate or submit a PR for you. Take your time and code only when you have free time :smile:

**Comment by RadioactiveStud** [comment]
I'm actually working on it right now soo....

**Comment by RadioactiveStud** [comment]
Didn't close it because there are some tooltips Eternaldoom didn't do.
