### ISSUE TITLE
Need to add Candy Cane Blocks

### ISSUE THREAD

**Issue by krwminer** [DivineRPG/DivineRPG#159]

**Comment by RadioactiveStud** [comment]
Not sure if we were planning on adding all the decorative blocks back, but we can I guess.

**Comment by Eternaldoom** [comment]
It was originally planned to remove them, but there's no reason to.

**Comment by RadioactiveStud** [comment]
Well I feel like no one is ever going to use them, that's all.

**Comment by krwminer** [comment]
Decorative blocks are easy and part of what we liked about DRPG. I say include them.
