### ISSUE TITLE
Some interesting bug

### ISSUE THREAD

**Issue by Shadow232** [DivineRPG/DivineRPG#160]
Then you go to winter portal, that teleport you to winter dimension, it crashes sometimes . I dont have any problems, but my friend get such error: I can`t understand why is getting such problem, my 4 friend all is ok, but fifth get error :D

http://pastebin.com/FGsWuRcq

**Comment by Eternaldoom** [comment]
If it's only 1 person (especially a person with liteloader), this probably isn't an issue.

**Comment by Shadow232** [comment]
not only 1 ...

**Comment by Eternaldoom** [comment]
@krwminer, are you able to reproduce this? I can't in a dev workspace.

**Comment by krwminer** [comment]
I will check this when I get home tonight. I have not seen any problem with it so far nor has any of my friends reported it as a problem.

**Comment by Shadow232** [comment]
I already checked and find problem. If in server config != clieng config of dimension number will get crash :) so simple
