### ISSUE TITLE
Inventory Boss Bar

### ISSUE THREAD

**Issue by SonicBoom213** [DivineRPG/DivineRPG#163]
Sonic here, 

Thanks for solving the first problem! 
I noticed that after whenever you open your inventory, the parasecta boss bar appears. This also applies to chests and the like

**Comment by RadioactiveStud** [comment]
Most likely a conflict with NEI. #39 duplicate.

**Comment by SonicBoom213** [comment]
Got it, all check the other posts next time before I post an error, thanks!

**Comment by RadioactiveStud** [comment]
>Got it, all check the other posts next time before I post an error, thanks!
No. It's okay you posted this because #39 was closed because we thought it was fixed. Not your fault.
