### ISSUE TITLE
Using the teleportation crystal in another dimension puts you underground.

### ISSUE THREAD

**Issue by Eternaldoom** [DivineRPG/DivineRPG#167]

**Comment by krwminer** [comment]
In the same dimension or in Dimension 0? Have you used a bed or not?

**Comment by Eternaldoom** [comment]
No bed, I was in Eden

**Comment by Eternaldoom** [comment]
It put me underground in the overworld.

**Comment by krwminer** [comment]
OK. Thanks, I will look into it.

**Comment by krwminer** [comment]
One more thing. Could you give me the seed for the world you tested on, just in case I have trouble reproducing it. Thanks.

**Comment by Eternaldoom** [comment]
3325622067925315873, but i tested this on a couple worlds

**Comment by krwminer** [comment]
I am easily able to reproduce. Fixing it is the issue. I am still working on it. I am getting closer.

**Comment by krwminer** [comment]
Ugh. I fixed this and I tried to push but you changed the file. I will fix it and push it in tonight, I am out of time this morning.
