### ISSUE TITLE
Mob spawning still needs tuning.

### ISSUE THREAD

**Issue by krwminer** [DivineRPG/DivineRPG#168]
Eden Weak Cori never seems to spawn anymore, not compared to 1.4.7.
Moonwolfs spawn out of control.

I had done some work on this, I plan to get back to it and complete it.

I did not want to forget about it.

**Comment by RadioactiveStud** [comment]
Are the two you listed the only two mobs you have seen problems with?

**Comment by krwminer** [comment]
Yes. But I have not really done a comprehensive test. They are just the ones I noticed so far. Because there are differences, I thought we should do a more thorough look through.
