### ISSUE TITLE
Twilight Trees leaves should decay.

### ISSUE THREAD

**Issue by krwminer** [DivineRPG/DivineRPG#169]
I forgot the exact reason why they did not, I think it was a worldgen issue.

If in fact it is a worldgen issue, I think we should fix that.

It is real ugly to not have them decay.

**Comment by Eternaldoom** [comment]
I removed the leaf decay because it wasn't crucial and it caused all the trees in the Wildwood to start decaying. I guess it could be added back, but it should use something better than the vanilla stuff.

**Comment by krwminer** [comment]
Was the problem that they decayed when you did not want them too? Or that it caused lag or both?

We can play around with our own decay.

**Comment by Eternaldoom** [comment]
Both.
