### ISSUE TITLE
PVP damage

### ISSUE THREAD

**Issue by FirKys** [DivineRPG/DivineRPG#170]
Hello. Please fix one problem. All weapons ignore flag pvp: deny in worldguard.

**Comment by Eternaldoom** [comment]
Well the weapons use vanilla combat tracing, and work with vanilla PVP disabled, so I can't do anything about this, sorry. You could raise this issue with Worldguard though.

**Comment by rlemish** [comment]
Странные вы ребят, ну очевидно что будут использовать WG, люди сидят и сами дописывают.

**Comment by ensirius** [comment]
@Eternaldoom You can add forge damage event check. I am pretty sure, cauldron can pass it correctly to bukkit.

@rlemish Потому что моды пишутся для ваннилы, а не для ведра.
