### ISSUE TITLE
Beds in Vethea do literally nothing

### ISSUE THREAD

**Issue by Flameminer221** [DivineRPG/DivineRPG#173]
The Hunger now trades Beds for 5 shiny pearls. When I placed a bed in Vethea, I right-clicked it and nothing happened. No explosion, no sleep, no "you can only sleep at night" message. I know it was not lagging because mobs were moving and broken blocks (including the bed) could be picked up.

Also, where is the best place to post suggestions?

**Comment by Eternaldoom** [comment]
PM me minecraft forums.
