### ISSUE TITLE
Dream lamp not working

### ISSUE THREAD

**Issue by aking4125** [DivineRPG/DivineRPG#175]
Last I recall. You had to right-click a dream lamp and a GUI will open. I remember you had to place a piece of Acid and the lamp will stay on for a set amount of time. Right-clicking the lamp with or without the Acid in hand does nothing.

**Comment by Flameminer221** [comment]
Right now, the name for inactive dream lamps is "Dream Lamp Off", which is sort of technical. Shouldn't it just be "Dream Lamp"?
