### ISSUE TITLE
Marsine has no uses, unable to craft DRPG stained glass

### ISSUE THREAD

**Issue by aking4125** [DivineRPG/DivineRPG#182]
I recall the Marsine used to craft the DRPG Stained glass. According to NEI it has no uses and the stained glass has no recipe. Unless this was changed to be a trade. Marsine doesn't seem to be used for anything.

Firestock and Veilo doesn't seem to have any uses either. I don't remember what they was used for in 1.4.7 either.

**Comment by Eternaldoom** [comment]
Veilo never had a use, it was going to be fuel in an experience condenser.

**Comment by Flameminer221** [comment]
So Veilo is basically crud used by Leorna to scam people who think it has a use? It should be removed or given a use.

**Comment by Eternaldoom** [comment]
Lol. Yeah, the machine will be added, or the trade temporarily removed.
