### ISSUE TITLE
Fire Crystal and Firelight: Difference?

### ISSUE THREAD

**Issue by Flameminer221** [DivineRPG/DivineRPG#185]
Firecrystals and Firelights seem to be exactly the same. Is there really a need for a duplicate block (fire light) that is more expensive than the one that is readily available (fire crystal)? Or is there supposed to be a difference?

**Comment by Eternaldoom** [comment]
Firecrystals should be dimmer.

**Comment by Flameminer221** [comment]
Ouch. I never actually tested the light level, but should they have a different texture so they are easier to identify?

**Comment by RadioactiveStud** [comment]
They do have different light levels. I think they should have different textures though.

**Comment by Flameminer221** [comment]
Maybe the texture for firelight could be a blue or green (probably blue, since whoever heard of a green fire) recolor of firecrystals.

**Comment by RadioactiveStud** [comment]
For the record, if copper burns, it creates green fire. 
But yeah blue sounds good.

**Comment by Flameminer221** [comment]
...oops. Firelights aren't made out of copper, anyway, right? ...Hey, what are all those blocks made of anyway?

**Comment by RadioactiveStud** [comment]
Heck if I know.

**Comment by RadioactiveStud** [comment]
Closed in latest commit.

**Comment by Flameminer221** [comment]
I found this Firelight texture from the 1.6.4 beta, do you think it's better than the blue one?
![firelight](https://cloud.githubusercontent.com/assets/11131230/7098593/a8270730-dfb0-11e4-95ab-0aed09a2f489.png)
I didn't make this, and I don't know who did, but it was in the beta.
