### ISSUE TITLE
Vethea pickaxe

### ISSUE THREAD

**Issue by Flameminer221** [DivineRPG/DivineRPG#186]
Since the readme said that stuff like "Could you add/change _____?" belonged here, I decided to just post my suggestions here.

I think that Vethea should have some sort of Pickaxe obtainable through Hunger trading. Currently, there are tons of stone-based blocks in Vethea (from dream stone and everstone to lunastone and metal caging) that should be harvestable with a pick. The number of blocks that can be obtained in Vethea at the moment is limited, and a pickaxe should help mitigate this problem (though I still think Vethea needs more vanilla blocks than just chests).

The other reason that a pickaxe would be good is because it would allow for a better way to get up to the next layer of Vethea. Currently, the only thing you can do is gather tons of blocks, pillar up to the ceiling, and then punch through the stone (which takes a long time) to get to the next level. A pick would at least let you drill through the stone.

The pickaxe itself should be moderately expensive (say, 8 dirty pearls) and should have durability in order to encourage players to fight more mobs in order to get more pickaxes. Personally, I think it should be an iron pickaxe, because stone breaks a bit too fast and diamond is OP. It could be called a "Dream Pickaxe" which is functionally identical or close to an iron pickaxe (durability and all), but is Vethean-themed with a blue handle and a green tip, but iron ones would probably be sufficient.

**Comment by Eternaldoom** [comment]
I don't like the idea of including a pickaxe in Vethea, as the dimension is entirely oriented toward combat, not mining/building. Also, the whole theme of the dimension is to make the player feel vulnerable, and adding pickaxes would take away from that.

**Comment by aking4125** [comment]
If a pickaxe is a bad idea in Vethea. Then at least make it so that the stone can be broken a lot easier with your fist, as it takes a a really long time to get to the top. Maybe add a super rare staircase or elevator or transporter to enter the next floor?

**Comment by Flameminer221** [comment]
If its super rare, though, you might as well just punch the stone. But, yeah, I think that if you fight enough mobs, the Hunger should give you something that does nothing but get you to the next level.
