### ISSUE TITLE
Most DRPG Furances smelt stuff at the same rate as a vanilla furnace

### ISSUE THREAD

**Issue by aking4125** [DivineRPG/DivineRPG#188]
Coalstone, Oceanfire, Greenlight, & Molten Furnaces smelt stuff at the same rate as a vanilla furnace. Essentially making the 4 furnaces just decorative difference. All 4 doesn't use fuel which seems to be intended. If I'm not mistaken, I think it was suppose to be a tier level thing? Unless those furnaces smelt specific things.

Moonlight Furnace seems to smelt about 25% or so faster than the rest. Whitefire and Demon Furnaces smelt the fastest and are equal at in terms of smelting speed. I don't recalll any of these being specific to Vethea. Maybe make one of them a trade for the hunger hungry even though it will not have any uses now, it may in the future? Just a suggestion.

**Comment by Eternaldoom** [comment]
The smelting rates might be changed in the future, but the furnaces are intended mainly as a collectable item.

**Comment by krwminer** [comment]
The last time I touched these, I made them tiered according to the cost.
The speeds are, (lower is faster):
Demon: 100
Whitefire: 150
Moonlight: 200
Ocean: 225
Greenlight: 250
Molten: 275
