### ISSUE TITLE
Decorative Frosted Chest still functions the same as the Frosted Chest

### ISSUE THREAD

**Issue by aking4125** [DivineRPG/DivineRPG#189]
I'm assuming they are naturally found in Iceika either in the Village houses or in dungeons (If that's still a thing). I don't seem them as a trade either. They are pretty much the exact same thing and function the same and even has the same slots. What is the purpose of the Decorative Frosted chest? Am I missing something?

**Comment by Eternaldoom** [comment]
The only difference is that the decorative ones don't drop snowflakes.
