### ISSUE TITLE
Some seeds pop off when they enter their next growing stage

### ISSUE THREAD

**Issue by aking4125** [DivineRPG/DivineRPG#190]
Hitchak, Velio, Eucalyptus and Aquamarine seeds pop off when they enter the next growing stage. Pinfly, and Firestock seeds seem to grow normally. Placed on Arcana grass with Tar all around it. You also can't place the seeds directly next to each other, different or not. This may be intended.

Moonblub, Purple and pink glowbones grow normally and doesn't require tiled dirt or water.

Mushroom and Tomato seeds grow normally on tiled dirt.

Would also like to point out Pinfly and firestock seeds does drop the seed and item normally.

**Comment by Eternaldoom** [comment]
can't reproduce this.
