### ISSUE TITLE
Vethean block names

### ISSUE THREAD

**Issue by Flameminer221** [DivineRPG/DivineRPG#191]
Enhancement/suggestion:
Some Vethean blocks have numbers in front of their names. For example, the Karos chamber is made partly of "Karos Bricks2" and the hunger trades "Dream Bricks1" and "Dream Bricks2" for pearls. This is a bit...weird, especially since the latter can be obtained in normal survival. Should they be called something like "Light Dreambricks" or just names that aren't exactly the same and have no numbers?

~~Bug:
The Karos Cannon is called "tile.karosCannonBlock.name"~~

**Comment by RadioactiveStud** [comment]
I don't have a problem with renaming them.
The Karos Cannon thing isn't a bug. Any names like that will be named correctly eventually. If you see any more, don't worry about it.
