### ISSUE TITLE
Some Decorative blocks has no recipes

### ISSUE THREAD

**Issue by aking4125** [DivineRPG/DivineRPG#192]
All of the Mob Pumpkins, Vane blocks, Dye blocks, Checker, Rainbow Wool, Crate, and fancy wool has no recipes. I suspect many of these will be removed anyways. 

Aqua Torch and Skeleton Torch has no recipe either. I'm not sure if they will stay or be removed.

What is the purpose of the Blue and Purple stone? They have no recipe or uses. I don't seem them as a trade unless I'm blind and I don't remember a mob dropping that.

**Comment by RadioactiveStud** [comment]
Actually we plan on adding all the decorative blocks back.

**Comment by aking4125** [comment]
What is the purpose of the Blue and Purple stone? They have no recipe or uses. I don't seem them as a trade unless I'm blind and I don't remember a mob dropping that.

**Comment by RadioactiveStud** [comment]
**Shurgs**

**Comment by aking4125** [comment]
Welp. I might be super blind, if they spawn anywhere in any of the dimensions I sure have missed it. They don't give light either by the looks of it. Just wanted to bring this up. I think they are useless but if they are going to be added. I wonder how you would get them.
