### ISSUE TITLE
DRPG mob movement seems "glitchty" and not smooth & Bohemite is sonic

### ISSUE THREAD

**Issue by aking4125** [DivineRPG/DivineRPG#194]
The mobs movement seems glitchty. They don't move very smoothly and it seems the AI is a tad "slow". With the Entralled Dramcryx for example. Sometimes, moving out of his range and he'll walk away then return. Though it's hard to tell if he is just turning, doing a 180 or whatever. I'm sure this will be ironed out once all the mobs and such is rebalanced but just wanted to at least point this out.

The Bohemite moves at a crazy speed and seems to "teleport" around all over the place.

**Comment by Eternaldoom** [comment]
The bohemite had a crazy movement speed, but there's no reason the other mobs should be glitchy, it could just be their size in which case there's nothing we can do about it.

**Comment by aking4125** [comment]
It's a hard thing to explain. But their movement isn't really smooth like, say the vanilla mobs. It's almost like they are skipping frames or something. I can't really explain it but I still hold to what I say when the DRPG mobs don't move very smoothly. Glitchy may be a harsh term but kinda looks like that sorta.
