### ISSUE TITLE
Icicle bow damage

### ISSUE THREAD

**Issue by Flameminer221** [DivineRPG/DivineRPG#196]
The Icicle bow claims to do 2-11 damage. Shooting a Spider and Quadro (my weapons tester) after drawing the bow back as far as possible did a maximum of 8 damage (maybe 9).

**Comment by Eternaldoom** [comment]
Is it also like this with other bows that say 2-11?

**Comment by Flameminer221** [comment]
Apparently, yes. I just tested the inferno, hunter, and shadow bows and they never did any more than 10 damage to quadro.
