### ISSUE TITLE
Suggestions on better ways to go up in Vethea

### ISSUE THREAD

**Issue by Flameminer221** [DivineRPG/DivineRPG#202]
There has to be a better way to get up to the top in Vethea. Right now, the only way to get up is to use blocks to reach the ceiling and punch through several blocks of dream stone before getting to the next level. Since Vethea is supposed to be combat oriented, maybe the way up should involve getting pearls.

Teleportation crystals? Maybe The Hunger can sell a crystal for each floor, and using the layer x crystal will teleport you to layer x. The only issue I see is that the Hunger only spawns on layer 1...

Staircase blocks that spawn a spiral staircase (made of some material) when placed and right clicked sound like a good idea. Perhaps they can be found at the end of crypts, temples, etc. (in that case, they'd need pearls as fuel to create the staircase) or get sold by the hunger for some amount of that layer's pearls (no fuel since you already paid pearls for it). The blocks would only work on the layer they're made for and build a staircase that always stops at the bottom-most altitude of the next layer (no matter where they start). These would probably be better in my opinion.

**Comment by Eternaldoom** [comment]
This isn't going to be changed. We plan to stay away from changing the content in vethea.

**Comment by Flameminer221** [comment]
Okay, no more vethea suggestions then.
