### ISSUE TITLE
Vethean weapons do one more point damage than claimed.

### ISSUE THREAD

**Issue by Flameminer221** [DivineRPG/DivineRPG#205]
See title.

For example, the Teaker Backsword claims to do 4 damage, but it actually does 5.
The Arksiane Backsword claims 37, but it actually does 38.

**Comment by Flameminer221** [comment]
Just thought of this: shouldn't it say +4 or +37 attack damage like normal vanilla minecraft items?

**Comment by Eternaldoom** [comment]
No, that's intentionally overridden to match the other tooltips.
