### ISSUE TITLE
Everfright does not say "Vethean"

### ISSUE THREAD

**Issue by Flameminer221** [DivineRPG/DivineRPG#206]
Every Vethean weapon from disks and bows to swords and cannons says "Vethean" along with stats when moused over. For some reason, the Everfright does not say this, even though all of the other Vethean bows and Ever-weapons say it.

Off topic: Is the official wiki going to reopen soon, or is the communiy wikia the new "official" one?

**Comment by Eternaldoom** [comment]
There will be a new wiki at some point.
