### ISSUE TITLE
Bedrock Tools and Armor should be changed

### ISSUE THREAD

**Issue by aking4125** [DivineRPG/DivineRPG#213]
With the whole rebalancing thing happening slowly. I think the ability to craft bedrock should be removed and the tools and armor should be changed to use a different material. What exactly I don't know but. I feel that being able to craft bedrock just shouldn't be a thing for a mod like this. It can be used as a serious troll device by blocking out someones entire home and encasing it in bedrock then they'll never be able to get out etc. This is a Suggestion that I'm sure will be ignored.

**Comment by Eternaldoom** [comment]
You're right, I was thinking about this the other day. It probably won't happen in this release though. For griefing, it isn't really an issue. You have to play for a while to get a rupee block, and a player who has devoted that much time to a server isn't likely to risk getting banned.

**Comment by krwminer** [comment]
What about making a DRPG bedrock block. Have it have texture of bedrock, but otherwise have the hardness and resistance of obsidian. It is not just griefing, it can be accidentally placed and never removed too.

**Comment by Eternaldoom** [comment]
Maybe

**Comment by aking4125** [comment]
Regardless of how difficult it is to get or whatever. Crafting bedrock just shouldn't be a thing now a days. Unless this is something like Rotary craft but you don't "craft" bedrock, you crush it for a type of Bedrock ore whatever.

**Comment by Flameminer221** [comment]
How about this?

Four obsidian and one rupee block crafted in a compass formation makes 2 bedrock chunks
Bedrock chunks craft armor, weapons, tools, bricks, minibricks, and storage block (and all bedrock-related blocks)
Said blocks become breakable and harvestable with diamond pick (they're not pure bedrock) though it takes twice as long as obsidian.

**Comment by Eternaldoom** [comment]
I still think there's nothing wrong with bedrock if it's difficult to obtain.

**Comment by aking4125** [comment]
That's different for certain stuff just as the flight armor or whatever. But bedrock in Minecraft is meant as a "barrier block". Placing Bedrock and you cannot remove it what so ever. Either by accident or on purpose it's not a good idea in a mod like this to be able to craft bedrock really. It just doesn't make sense.

**Comment by Flameminer221** [comment]
How about...a config option to enable/disable crafting of bedrock? Server owners could turn it off, but normal players who like to make houses out of bedrock could keep it on.

Off topic: Wow, a lorgaflight!

**Comment by Eternaldoom** [comment]
Hmm, maybe. I'm a little reluctant to make any gameplay configurable.

I figured a Lorgaflight was better than a green cow thing :P.

**Comment by Flameminer221** [comment]
Okay.

That was a cow? I thought it was a pig!

**Comment by Eternaldoom** [comment]
Bedrock will stay craftable. The whole point of having bedrock items is crafting with bedrock. Adding a new item won't be as nice. I'll think about adding a config option.
