### ISSUE TITLE
New version of mod won't build

### ISSUE THREAD

**Issue by Flameminer221** [DivineRPG/DivineRPG#214]
For some reason, the latest (written 3/1/2015) test version of the mod isn't building for me. After it failed, I tried building one of the older versions (the latest I had was from 2/25/2015) and it worked. I replaced those old source files (the java folder, the resources folder, and the two other files) with the new ones again and it failed once again. I'm using the latest version of forge (forge-1.7.10-10.13.2.1291).

Here's the command I ran (the red stuff is just blocking my desktop username 'cause I like to keep it private :D):
![buildissue1](https://cloud.githubusercontent.com/assets/11131230/6434282/07eb1f6c-c053-11e4-89e0-d51f8d1158a4.png)

Here's a part of the stacktrace:
![buildissue2](https://cloud.githubusercontent.com/assets/11131230/6434283/0afe21a4-c053-11e4-86d5-73a65bc5bfe7.png)

**Comment by Eternaldoom** [comment]
Update your mappings to stable_12 in your build.gradle file.

**Comment by Flameminer221** [comment]
How?

**Comment by Eternaldoom** [comment]
Add the line:
> mappings = 'stable_12'
under minecraft {.
