### ISSUE TITLE
Hunger trade issue?

### ISSUE THREAD

**Issue by Flameminer221** [DivineRPG/DivineRPG#216]
In both of my survival worlds in Vethea, I have a Hunger near my house. When I go to the last trade for tormented templates and put in 5 (or any more than 5) pearls and then click the resulting template, I get Dream Sours instead and only one pearl is taken. When not enough pearls for the tormented template are provided, I still get Dream Sours as if I was using that trade. In a Creative world, I didn't get this issue...can you replicate it? Restarting mc did not fix the issue.

**Comment by Eternaldoom** [comment]
Sorry, I cant reproduce this and neither can some other people who are testing.

**Comment by Flameminer221** [comment]
Never mind, I think the issue had to do with hungers spawned in before the last build. In that creative world, my old hunger didn't trade right and spawning a new one in the survival world apparently fixed my problem.

**Comment by Eternaldoom** [comment]
Oh. Yeah I changed the NBT stuff.
