### ISSUE TITLE
Vethia Performance issues for low end computers

### ISSUE THREAD

**Issue by AquosStormfront** [DivineRPG/DivineRPG#219]
Possible, do you think you could optimize the Vethea dimension for better performance on lower quality computers? I have 1.4 Ghz processor, and the lag for the dimenstion is antagonizing, like around 5fps at the best.

**Comment by ShadowOfStrelok** [comment]
try to pregen wethea. but yes, wethea is most demanding for resourses.

**Comment by Eternaldoom** [comment]
Pretty hard to optimize it more. The best you can do is to turn down your render distance.
