### ISSUE TITLE
Mob spawn issues

### ISSUE THREAD

**Issue by ano101** [DivineRPG/DivineRPG#22]
Hi ! Sorry for my bad English . Translated by Google . I have a problem in the standard world no spawn mobs. Only saw the shark, crab and many Jack'o man. Tested in single player . Compiled the latest version. forge-1.7.10-10.13.2.1240

**Comment by ShadowOfStrelok** [comment]
I also propose to increase the number of protection in Halite armor because there is some imbalance between the attacking means and means of protection (fully enchanted Halite blade kills with enemy attacks in druh completely enchanted Halite armor if the opponent also has Halite armor), as well a complete set Halite armor protects worse than a set of quantum armor without a helmet of IC2

**Comment by ShadowOfStrelok** [comment]
And if the vamasheron model will be big, and vamasheron damage model will be small, it will interfere with normal playing. the same speed of vamasheron is so small, he moved slowly of walking Player

**Comment by Eternaldoom** [comment]
Halite armor will not be buffed, as going above 83% damage reduction would make it so that with protection 4 on all your armor, you're almost invulnerable.

**Comment by ShadowOfStrelok** [comment]
okay, я понял это. просто при двух противниках в халитовой броне один очень быстро убивает другого.

**Comment by ShadowOfStrelok** [comment]
omg. okay, but when two opponents in one Halite armor very quickly kills another. have you any idea to change that?

**Comment by Eternaldoom** [comment]
Enchant the armor with prot. 4. I assume you mean pvp?

**Comment by ShadowOfStrelok** [comment]
yes. Player in full enchanted halite armor die after 2-3 hits from halite armored enemy with halite blade,

**Comment by ShadowOfStrelok** [comment]
maybe we can control the damage? try to remove effect of enemy halite armor in player halite armor?

**Comment by Eternaldoom** [comment]
No. The halite blade is a strong weapon. Keep in mind that halite is only slightly better than vanilla diamond. DRPG was meant to be played with enchantments and something to heal yourself.

**Comment by ShadowOfStrelok** [comment]
hmmm, as far as I remember, vanilla diamond has 50% defence?

**Comment by Eternaldoom** [comment]
80%

**Comment by ShadowOfStrelok** [comment]
omg, why? maybe change this defence to 40 maybe? because elite realmite armor has 50% damage reduction. and iron armor to 30-35?

**Comment by ShadowOfStrelok** [comment]
and i have one question - this version of Divine rpg will be released on 1.7.10?

**Comment by Eternaldoom** [comment]
DRPG does nerf diamond armor, and yes, it will be 1.7.10.

**Comment by ShadowOfStrelok** [comment]
What is nerf?

**Comment by Eternaldoom** [comment]
DRPG replaces vanilla armor with some that isn't as good

**Comment by Eternaldoom** [comment]
Oh and I guess this issue is fixed :P.

**Comment by fewizz** [comment]
ShadowOfStrelok,  nerf ( нерф ) - это изменение характеристик чего-либо (чаще всего в худшую сторону).  Вроде как-то так.

**Comment by Flumaster** [comment]
@Eternaldoom, nope, issue is not fixed.  :(

**Comment by ShadowOfStrelok** [comment]
Man, issue isnt fixed now, mobs not spawning in the day and spawn too little in the night underground. and i cant see any spawned crabs, cyclops, ender spiders and more old divine mobs.

**Comment by Eternaldoom** [comment]
Cyclops and crabs definitely spawn. I'll probably increase the rate though.
