### ISSUE TITLE
Acceleron directional placement?

### ISSUE THREAD

**Issue by Flameminer221** [DivineRPG/DivineRPG#221]
I think that the ability to make accelerons have directional placements should be implemented so players can make better-looking conveyor belts or speed travel systems. I know that whatever way the block is facing doesn't affect how it acts, but having a north bound "monorail" with all the blocks facing east doesn't look aesthetically pleasing in my opinion.

**Comment by Eternaldoom** [comment]
Instead of making it a rotated pillar and everything, the block will just get a new texture
