### ISSUE TITLE
[Enhancement] Mob death message grammar/consistency fixes

### ISSUE THREAD

**Issue by Flameminer221** [DivineRPG/DivineRPG#232]
- [x] For some reason, the DivineRPG mobs' death message (when you kill them) has a period at the end (e.g. Player has slain a Rotatick.), but the vanilla mobs' message does not. I think the drpg message should not have a period to be consistent.

- [x] The vanilla mobs' death message uses "an" (e.g. Player has slain an Skeleton) when that probably wouldn't be a good choice since only a few vanilla mobs (iron golem, ocelot, enderman) use "an" and two of them aren't even common. Perhaps the default should be "a" (e.g. a Skeleton) since almost all vanilla mobs go with "a" and not "an".

- [x] The fractite and dissiment, for some reason, display two death messages (one vanilla, one drpg) when killed. For example, upon killing dissiment it says "Player has slain an Dissiment (next line) Player has slain a Dissiment."

- [ ] Since there's already a gramatically different message for Twins, how about making the death messages for drpg use "an" instead of "a" for applicable mobs? I compiled a list of mobs that start with a vowel wound and should use "an":

Acid hag
Alicanto
Angry bunny
Apalachia cadillion
Apalachia tomo
Apalachia golem
Arid warrior
Eden cadillion
Eden tomo
Ehu
Enchanted warrior
Enchanted archer
Ender spider
Ender watcher
Ender triplets
Endiku
Ent (if they even spawn anymore)
Enthralled dramcryx
Epiphite
L'heiva

**Comment by Flameminer221** [comment]
Off-topic (I didn't want to create a new issue just to ask this):

Where can I get images of the mobs with new textures outside of the game, like the kinds on the MC wiki's infoboxes? Images in-game have hard-to-remove block surroundings, and it's really hard to get mobs in an appropriate angle for photo shoots.

**Comment by RadioactiveStud** [comment]
Well, our wiki is currently down, and I don't even know if that has the images you want. So as of now, no where. Sorry. 

There are ways to make mobs stop moving. There's also a technique I learned where you texture a block to be completely black or white and use it as a background when you are taking screenshots. Then you can use paint.NET's magic wand or similar to turn the background to transparent.

**Comment by Flameminer221** [comment]
Okay. I'll probably retexture somehing I don't really care about...

**Comment by Eternaldoom** [comment]
What mob images do you need? I can get them as I have the folder of Techne models.

**Comment by RadioactiveStud** [comment]
Oh. :neutral_face:

**Comment by Flameminer221** [comment]
I'm getting these so I can put them on the community wiki, since a lot of the pictures are in-game and have weird angles.
Rotatick (new texture)
The Eye (new texture)
Cave crawler
Wildwood and apalachia tomo
Eden cadillion 
The Hunger
Mysterious men
...That's it for now, I may ask for more but these are the more important ones. Thanks!

**Comment by Eternaldoom** [comment]
Oh yeah are you Cookiepower?

**Comment by Flameminer221** [comment]
Uh-huh.

**Comment by Eternaldoom** [comment]
https://www.dropbox.com/s/zyak8j4e5pxc9qk/mobPics.zip?dl=0

Here you go. I also added the new mobs the new textures for the other cadillions (they all got new textures), and the new parasecta model. Thanks for editing the wiki!
