### ISSUE TITLE
Plants in dimensions should be broken with shears

### ISSUE THREAD

**Issue by Dizzlepop12** [DivineRPG/DivineRPG#234]
When you break plants in the dimensions, you will get the drop for the specific plant no matter how you break it. This is annoying when fighting / mining, since I don't want to keep emptying the plant from my inventory. Perhaps make it only be dropped when broken with shrears.

**Comment by Flameminer221** [comment]
But aren't the plants supposed to be craftable into dust as ammunition for blitzes and such?
Also, shears aren't in Vethea and that would give no way to harvest bulbatobes, shimmers, etc.

**Comment by Eternaldoom** [comment]
I'll probably keep flowers and vethean plants harvestable by hand, and make grass/brush require shears.

**Comment by Flameminer221** [comment]
In the latest version, the wildwood tallgrass was still dropping when broken by hand. Not sure about the others, though
