### ISSUE TITLE
Sug: rupee/arlemite shickaxe difference

### ISSUE THREAD

**Issue by Flameminer221** [DivineRPG/DivineRPG#235]
Currently, both rupee and arlemite shickaxes (claim to) have a durability of 15, and they both have infinite uses. Unless the tooltip is faulty, the only thing functionally different about them is the crafting recipe. Shouldn't one have a greater efficiency over the other?

**Comment by RadioactiveStud** [comment]
Well the ores have the exact same rarity. So they should have the same stats. Although I do think they should be different some how, I just don't know how.

**Comment by Eternaldoom** [comment]
The stats should be changed back to what they were in 1.4.7.

**Comment by RadioactiveStud** [comment]
Well, they should be the same though.
