### ISSUE TITLE
Twilight bow incorrect tooltip damage

### ISSUE THREAD

**Issue by Flameminer221** [DivineRPG/DivineRPG#236]
The twilight bow found in the nei screen claims to do 13-25 damage. Testing it out without effects or armor, I got it to do as little as 10 damage and as much as 34.

Also, I think the twilight bow should be placed in the creative menu (right now it's not there). I mean, it's already there, and has info and works properly (hopefully), so why not? It doesn't hurt to have a creative-only weapon like that.

**Comment by Eternaldoom** [comment]
Over 25 is a critical hit. I can't reproduce getting <13.

**Comment by Flameminer221** [comment]
To get 10, I had to just tap the mouse button as lightly as possible several times, but I guess it's possible that something was screwing up damage indicators.
