### ISSUE TITLE
Pet issues

### ISSUE THREAD

**Issue by Flameminer221** [DivineRPG/DivineRPG#237]
I'm in Eden right now, and I see several pieces of empowered meat just lying on the ground. Now I know why. Bunnies and angry bunnies are leaping at cadillions (and maybe tomos) and damaging them. I thought only the tamed bunnies would do such a thing? 

Perhaps this is similar to the hellpigs attacking the pigmen without the former being tamed (though the pigmen actually fight back, so it's not such a big deal). I haven't tested yet, but I'm willing to bet that this bug affects moonwolfs too. (Edit: it does)

**Comment by krwminer** [comment]
I am not seeing this in eclipse. Does it happen all the time? Something seem to trigger it?

**Comment by Flameminer221** [comment]
No, they just get attacked. They only get 1 damage per attack, but the mobs never find out. They're in open spaces, and the damage only occurs near a potential pet.

**Comment by krwminer** [comment]
Any other mods?

**Comment by Flameminer221** [comment]
Besides nei and damage indicators, no.

I don't have the latest latest build of divinerpg, though. I know there was a "tried fixing pets" commit, so I'll get that version when I have the chance and see if this still happens.

**Comment by krwminer** [comment]
Please check the latest and let us know if the problem still exists.

**Comment by Flameminer221** [comment]
Apparently, it doesn't. Moonwolves aren't attacking cadillions anymore.

**Comment by Eternaldoom** [comment]
If this is definitely gone, can you test it? Try taming one and getting it to attack.

**Comment by RadioactiveStud** [comment]
It seems they don't attack when they are untamed now, but they have some other problems, like never sitting up and following after being tamed. (This has been a problem for awhile)

**Comment by RadioactiveStud** [comment]
Okay, so current bugs with pets I've seen:
* The tamed pets attack mobs even if you don't tell them to.
* Bunny crashes if you feed him meat. (Commented out that section for now)
* The function that toggles isSitting on and off is never accessed, so the pets will never sit up.

**Comment by Eternaldoom** [comment]
Tamed pets should always attack mobs.

**Comment by RadioactiveStud** [comment]
Umm, not how vanilla wolfs work. During the night they will never stop attacking and never follow you.

**Comment by ShadowOfStrelok** [comment]
I apologize for the fact that I'm a little off topic, but how is calculating enchantment "protection"? I had an idea at the expense of armor, but I do not know how to calculate protection with enchantments.

**Comment by RadioactiveStud** [comment]
Well I don't know exactly, but the Minecraft wiki has a in debt explanation.

**Comment by ShadowOfStrelok** [comment]
Yes, but this explanation is pretty hard for my understanding

**Comment by RadioactiveStud** [comment]
That is because it is a complicated math thing, you can't really explain it in a simple way.
