### ISSUE TITLE
Epiphite kills player and then wipes out inventory

### ISSUE THREAD

**Issue by Flameminer221** [DivineRPG/DivineRPG#238]
When you get killed by an epiphite, you lose everything that was in your inventory. This is probably because they use lightning as their damage source, and lightning in vanilla also wipes out inventories. The thing I don't like is...should there really be a mob that automatically destroys the players inventory if it kills him/her? That can be frustrating...

**Comment by Eternaldoom** [comment]
Well, there's only a 1/5 chance to spawn a lightning bolt on hit, and the epiphite is going to be made quite a bit rarer (it'll have good drops). Players should consider the risk before fighting an epiphite.
