### ISSUE TITLE
Problem with mob-spawning in vanilla world

### ISSUE THREAD

**Issue by Shadow232** [DivineRPG/DivineRPG#239]
Problem with mob-spawning in vannilla world, before using latest updates all was OK, but now they dont actually spawn at all.. With other world ( End, Nether, Eden etc )all is alright.

forge 1291, source`s latest.

**Comment by Eternaldoom** [comment]
Well nothing at all was changed, so I'm not sure what the problem is.

**Comment by Shadow232** [comment]
I same cant understand... i got compiled version from 07.03, today compiled new version and spawning of mob in vanilla world ends...

**Comment by Shadow232** [comment]
I found problem ..  i think else if(WorldChunkManager.allowedBiomes.contains(biome)){ here is error, and that because he couldnt spawn any monster in vanilla

**Comment by Eternaldoom** [comment]
The old method was incompatible with other mods that added dimensions. I guarantee the new way works, me and 3 other people have no problem.

**Comment by Shadow232** [comment]
but like you can see. it's doesnt work, then i returned old method monsters begin spawning

**Comment by Flameminer221** [comment]
Do you have any other mods whatsoever?

**Comment by Shadow232** [comment]
Do you have any other mods whatsoever?
yes it is thaumcraft 4

**Comment by Eternaldoom** [comment]
What happens if you remove that?

**Comment by Shadow232** [comment]
without thaumcraft 4 they same dont spawn. ( tested in single player )
