### ISSUE TITLE
Bug with getting ore

### ISSUE THREAD

**Issue by Shadow232** [DivineRPG/DivineRPG#242]
If you wear eden armor set and take pickaxe with silktouch, you will get from 1 block of some ore in twilight worlds ( eden, arlemite etc ) 4 ores ...

some pictures with bug + dupe :D
http://prntscr.com/6gyf0x
http://prntscr.com/6gyf66
http://prntscr.com/6gyfae

**Comment by RadioactiveStud** [comment]
Oh yeah forgot about this.
