### ISSUE TITLE
(Sug) Vethea biome name

### ISSUE THREAD

**Issue by Flameminer221** [DivineRPG/DivineRPG#245]
Right now, the Vethea biome is named "Arksiane", while the other dimensions' biomes are named after the dimensions' names. Should the Vethea biome be called "Vethea" for consistency, since "Arksiane" as a biome name doesn't feel right?

**Comment by Eternaldoom** [comment]
No. It was Vethea for a while, but Arksiane contributes more to the "mythology" of the dimension.

**Comment by Flameminer221** [comment]
Yeah, but the biome names are only visible on the debug screen...and the debug screen isn't very mythological, right?
