### ISSUE TITLE
Messed up item ids

### ISSUE THREAD

**Issue by Flameminer221** [DivineRPG/DivineRPG#247]
Apparently, renamed/reworked items are just thrown to the end of the data value list, so now a bunch of items have mixed up IDs. For example, ID 4741 (as of a recent build) is a warsword of some kind, ID 4742 is a DRPG iron chestplate, and ID 4743 is the heliosis wrathhammer. Other scrambled ids include hellspider pumpkins being separated from all of the other pumpkins and the vethean blocks (dream bricks, etc.) not being too organized.

**Comment by Eternaldoom** [comment]
Can't be fixed. All item ids are handled internally by forge.

**Comment by Flameminer221** [comment]
But don't other mods have config options for item ids?
Also, are those going to be the IDs in the final release?

**Comment by aking4125** [comment]
Since this is for 1.7.10. The IDs for items and blocks don't matter anymore. The number is just something Forge assigns it for whatever reason. It won't break anything when using other mods for the most part. Only the dimension and Biome IDs needs to be changed.

**Comment by Flameminer221** [comment]
Okay, so the configs were for things like 1.6.4 then. I see.
