### ISSUE TITLE
GUI is rendering in front of chat

### ISSUE THREAD

**Issue by RadioactiveStud** [DivineRPG/DivineRPG#25]
GUIOverlay.drawArmor() draws the GUI in front of the chat.
![Error](http://i.gyazo.com/5bc5d652387e556e6c3bb9f278a7ad32.png)

**Comment by Eternaldoom** [comment]
Why won't fix?

**Comment by RadioactiveStud** [comment]
Because it won't fix...

**Comment by Eternaldoom** [comment]
Wontfix means it won't be fixed

**Comment by RadioactiveStud** [comment]
Well that's dumb
