### ISSUE TITLE
How broken is this?

### ISSUE THREAD

**Issue by Wuerfel21** [DivineRPG/DivineRPG#255]
Just asking, how broken is this currently?
Also, is this a rewrite of DRPG or is it based on the original sources?

I hope, that in the end, we get something that actually work... still have nightmares of broken traders in old DRPG, and my server just rejected being tortured with the shittynes of Nevermine(great mod, just horribly broken). And as i dont think there are any other loads-of-dimensions-and-mobs-and-stuff mods, i just hope DRPG comes back... so much memorys with this, remeber lanpartying drpg back in 1.4 time...

**Comment by Eternaldoom** [comment]
It's a rewrite (or at least it's supposed to be, certain people copied over some classes :/). It's not very broken at all, the only known issues are on github, and it's been tested VERY extensively.

P.S. Nevermine is most certainly not very broken.
