### ISSUE TITLE
Statue issues

### ISSUE THREAD

**Issue by Flameminer221** [DivineRPG/DivineRPG#261]
1. The statues are mostly (if not always) facing backwards in the inventory screen (circled in red).
2. The statues clip through the inventory box (circled in green).
3. When a statue is broken, the particles are the "missing texture" particles.
4. There is no kar-ot statue.
![statueissues](https://cloud.githubusercontent.com/assets/11131230/6837314/5fc52184-d321-11e4-8a8d-7967718aa8cd.png)

**Comment by RadioactiveStud** [comment]
Not sure if number 2 can be helped.
