### ISSUE TITLE
Two arcana plants have no apparent use

### ISSUE THREAD

**Issue by Flameminer221** [DivineRPG/DivineRPG#263]
Firestock: I've tried right-clicking it, checking crafting recipes for it, and even hitting mobs with it. Does it have a purpose, or is it just like veilo?

Eucalyptus root: When it is planted on arcanite dirt, it can be bonemealed into a full plant that drops seeds, but nothing else. They also appear to pop out when placed next to another eucalyptus root and sometimes on their own. Are these related to eucalyptus wood blocks?

On a side note, whatever happened to the note in the readme that explained how to build the mod? Was it too complicated?

**Comment by RadioactiveStud** [comment]
"It was a matter of time before it showed up in some modpack"
-Eternaldoom

**Comment by Flameminer221** [comment]
Did it show up in one?

**Comment by Eternaldoom** [comment]
No, but I didn't want to take the chance. Also, it defeated the purpose of releasing a public beta, since the original intention was to have it only be built by modders.

**Comment by Flameminer221** [comment]
So what does firestock do?

**Comment by Eternaldoom** [comment]
Fuel for Greenlight & Moonlight furnaces.
