### ISSUE TITLE
Orb of light effect does not go away when you get rid of it

### ISSUE THREAD

**Issue by Flameminer221** [DivineRPG/DivineRPG#265]
If you have an orb of light in your inventory and get rid of it (tossing it on the ground, into lava, into the void or the creative delete box), the light it emitted does not disappear.

**Comment by Eternaldoom** [comment]
Not sure if this is fixable :/. Mojang's lighting system is pretty bad.

**Comment by AreaOfMobeus** [comment]
Yo, there is a witchery item called Sun Grenade, it acts more like Lamona(Which also has the problem) than the Orb of Light, but it doesnt seem to have any lingering light problems. Not saying you should copy code or anything, but the bug may be fixable.

**Comment by Eternaldoom** [comment]
I'll have a look, thanks.

**Comment by Eternaldoom** [comment]
Tested the Sun Grenade, it dropped my FPS by about 30. The light staying problem could be reduced by increasing the light update frequency, but this would also increase the FPS drop.

**Comment by aking4125** [comment]
The Orb of light might as well be removed altogether as it doesn't seem to work as intended. I personally don't see the use of it either. But it's not my place to really give any "Ideas or Criticism" to Minecraft mod makers since most of them are very touchy about it.

**Comment by RadioactiveStud** [comment]
We'll keep it if anyone wants it.
