### ISSUE TITLE
Everfright doesn't have same sound as other vethean bows

### ISSUE THREAD

**Issue by Flameminer221** [DivineRPG/DivineRPG#266]
The vethea bows, from the teaker bow to the arksiane bow, use a different shooting sound from the vanilla bow, but the everfright uses the sound of a vanilla bow.

**Comment by RadioactiveStud** [comment]
Well the everfright is a different bow compared to the others. It could have a different sound, but not the same as that teaker-arksiane bows.

**Comment by Eternaldoom** [comment]
It should have the same sound.
