### ISSUE TITLE
Some tooltips say "DivineRPG", but not all

### ISSUE THREAD

**Issue by Flameminer221** [DivineRPG/DivineRPG#267]
Some items include "DivineRPG" in their tooltips, such as vanilla tools, starlights and starlight staffs, and food items. However, many do not, such as vanilla weapons, most arcana weapons, and most vethea weapons. I think that this "DivineRPG" label should just be removed since it is way too inconsistent and doesn't show much anyway.

**Comment by Eternaldoom** [comment]
Can't find any more.
