### ISSUE TITLE
Twilight tree suggestions

### ISSUE THREAD

**Issue by Flameminer221** [DivineRPG/DivineRPG#268]
The trees in the twilight dimensions (eden - mortum) do virtually nothing. The logs can't be crafted into planks, the trees don't have any saplings, and the leaves don't even decay properly. I think that the trees should get at least a bit more tree-like features:

- The trees should have saplings. Right now, once you harvest a twilight tree, you can't regrow it. It's gone forever (well, the leaves don't decay, but...). It's just not Minecraft-ish for a tree to not drop saplings. There needs to be a way for the trees to be legitimately renewable and growable in places like the Overworld. The saplings should grow on the dirt and grass of each respective dimension (since vanilla saplings can grow on dirt) and have the same drop rate as normal saplings.

- The trees should have planks. They used to have them in 1.4.7 (e.g. Red wood gets crafted into red planks) but not anymore for some reason. I think that just like the divine trees, the twilight trees should have planks (called stuff like "wildwood planks" or "skythern planks"). The planks shouldn't be craftable from dyeing wooden planks because that would ruin the uniqueness of the planks to the woods of said trees.

- Finally, Mortum trees should have a chance to drop "mortum fruit".  I mean, the mortum leaves are already covered in red fruit-like things, so they should drop some fruit at about the same drop rate as saplings.

**Comment by Eternaldoom** [comment]
3 isn't going to happen, 1 and 2 will.
