### ISSUE TITLE
Old blocks not in current version

### ISSUE THREAD

**Issue by Flameminer221** [DivineRPG/DivineRPG#271]
Are any of these 1.4.7 items/blocks going to return in the 1.7.10 version?

- [x] Spike block
- [x] Hot spike block
- [x] Dark bridge
- [x] Slime light
- [x] Dual claw
- [ ] Mini pizza
- [ ] Pizza dough
- [x] Star bridge

Dark plate [Edit: Won't be added]
Music boxes (Twilight, snowy, explorer, arcana, adventurer, natural) [Edit: Won't be added]

**Comment by Eternaldoom** [comment]
Music boxes and dark plate no, the rest will.

**Comment by Flameminer221** [comment]
I noticed these aren't in 1.7.10 too:

Acceleraunch
Queen of fire
Queen of ice
Arcanium bucket
Illumicase
Dual claw
Mini pizza
Pizza dough
Watermelon

**Comment by Eternaldoom** [comment]
Queens of Fire and Ice and the Arcanium Bucket were removed intentionally.

**Comment by Eternaldoom** [comment]
Acceleraunch also won't be added

**Comment by RadioactiveStud** [comment]
Music boxes are also never coming back.
- [ ] Spike block
- [ ] Hot spike block
- [ ] Dark bridge
- [ ] Dark plate
- [ ] Slime light
- [ ] Illumicase
- [ ] Dual claw
- [ ] Mini pizza
- [ ] Pizza dough

**Comment by Flameminer221** [comment]
Dual claw has already been added back if I'm correct, same commit as slime light.

Music boxes were useless anyway.

**Comment by Eternaldoom** [comment]
Pizza might come back, but more likely in the next update where they'll be redone and given variety.

**Comment by ShadowOfStrelok** [comment]
Not only blocks - old items not in current version.

**Comment by Flameminer221** [comment]
Well, yeah, but it started off with blocks (spike/hot spike, slime light, dark bridge, illumicase) and extended to items.
