### ISSUE TITLE
Divine accumulator does not work with unnaturally regenerated arcana

### ISSUE THREAD

**Issue by Flameminer221** [DivineRPG/DivineRPG#272]
The divine accumulator does not seem to work with unnaturally regenerated arcana. When arcana is regenerated through death or arcana potions, the divine accumulator does the particle effect but you stay on the ground. Here's how to reproduce:

(I tested this on survival, but I don't think gamemode will make a difference)

Potions do not work:
1. Get divine accumulator and several arcana potions (weak or strong). (If on survival, get skythern or other no fall damage armor and wear it).
2. Use divine accumulator twice.
3. On the way down, immediately drink the arcana potions and fill up the arcana.
4. Use the divine accumulator immediately after you get back down. The particles appear but you don't get launched into the air.

Death does not work:
1. Set gamemode to survival. Get divine accumulator and set keepInventory to true.
2. Use divine accumulator twice.
3. When you hit the ground, immediately respawn.
4. Now, immediately use the divine accumulator. Again, the particles appear but you don't launch.

The only way to get it to work properly seems to be to let the arcana regenerate normally.

**Comment by Eternaldoom** [comment]
Can you reproduce this with other arcana items?

**Comment by Flameminer221** [comment]
The ender scepter seems to be having issues too, as sometimes I use it and it doesn't teleport. Stuff like the meteor mash works just fine (I can drink the potions and immediately spam meteors).
