### ISSUE TITLE
Twilight shickaxes still have recipe

### ISSUE THREAD

**Issue by Flameminer221** [DivineRPG/DivineRPG#282]
They were removed and all, but their crafting recipe is still in the recipe file.

**Comment by ShadowOfStrelok** [comment]
omfg, why twilight shickaxes removed?

**Comment by ShadowOfStrelok** [comment]
And we must compile this version on recommendated forge, because latest cauldron is 1307-forge.

**Comment by Ghaarp** [comment]
May someone drop compiled version of mod on my email "xdmail(a)bk.ru"? Is this working for server with 2-4 people for now?

**Comment by Eternaldoom** [comment]
They were removed because they were OP.

**Comment by ShadowOfStrelok** [comment]
What is OP in this context?

**Comment by ShadowOfStrelok** [comment]
And divine shickaxe still inside the mod? And has it unlimited uses? Sry for my questions, i cand watch code now.

**Comment by Eternaldoom** [comment]
Divine shick isn't as powerful, and is arguably harder to obtain.

**Comment by ShadowOfStrelok** [comment]
OP- it is operator or what?

**Comment by Flameminer221** [comment]
Not sure if this is what you mean, but OP means overpowered, and in context it means that twilight shicks mine stuff a bit too fast.

**Comment by Eternaldoom** [comment]
Yep.

**Comment by ShadowOfStrelok** [comment]
But man, overpower is nice for mining metro tunnels and other

**Comment by Flameminer221** [comment]
Just use a mortum pick.
