### ISSUE TITLE
Missing build.gradle

### ISSUE THREAD

**Issue by Wuerfel21** [DivineRPG/DivineRPG#286]
Well, i can't compile the mod without it, and as i don't see any download links, where to get the mod from?

**Comment by Eternaldoom** [comment]
Setup a new forge workspace and drop in the code.

**Comment by fewizz** [comment]
![50b7599e-f7ef-11e4-8000-dcca5a21902a](https://cloud.githubusercontent.com/assets/8060034/7570295/bcb41a1a-f817-11e4-8c1a-2bbd4c16996c.png)

**Comment by Wuerfel21** [comment]
Seems like theres something wrong...

**Comment by RadioactiveStud** [comment]
I can compile just fine. I am using the **recommended** forge. 
Also make sure you have the line ```mappings = 'stable_12'``` in the ```minecraft``` section of ```build.gradle```
