### ISSUE TITLE
Nothing drops / crafts Halite Blitz

### ISSUE THREAD

**Issue by Dizzlepop12** [DivineRPG/DivineRPG#288]
As far as other Halite weapons and armor goes, all is well. However, nothing drops the Halite Blitz. It exists, and functions correctly, but there doesn't seem to be any boss that drops it.

**Comment by AreaOfMobeus** [comment]
switch(this.rand.nextInt(2)) {
			case 0: this.dropItem(TwilightItemsWeapons.haliteBlitz, 1);break;
			case 1: this.dropItem(TwilightItemsWeapons.haliteBow, 1);

Extract from code of the Twilight Demon boss, it has 50% chance to drop Blitz or Bow. You probably killed it once and didn't think it had a second drop.
