### ISSUE TITLE
More  compatibility with industrial mods

### ISSUE THREAD

**Issue by ShadowOfStrelok** [DivineRPG/DivineRPG#289]
MB white nerf of ic2\rc\other_industrial_mod armors to more gameplay compatibility?

**Comment by Eternaldoom** [comment]
I don't understand what you're saying.

**Comment by fewizz** [comment]
ShadowOfStrelok saying about nerf IC2 armor, if Divinerpg installed

**Comment by Eternaldoom** [comment]
This would require creating special items for specific compatibility with IC2. This won't be done, we aren't responsible for the balance of other mods.

**Comment by ShadowOfStrelok** [comment]
But if i do this, will you add it?

**Comment by TheSlayerMC** [comment]
You will have to talk to other mod authors about this issue, seeming that it's their mod that isn't balanced.

**Comment by ShadowOfStrelok** [comment]
But we can do special line in configuration file - "Industrial_compatibility = 0\1"?

**Comment by RadioactiveStud** [comment]
If it is good, we will add it.

**Comment by Eternaldoom** [comment]
We aren't going to integrate compatibility for specific mods (especially not balance changing), it'd become a mess.
