### ISSUE TITLE
Iceika Portal not working?

### ISSUE THREAD

**Issue by SonicBoom213** [DivineRPG/DivineRPG#291]
I made a 4x5 portal from snow just like the nether and crafted a Twilight clock, however I'm having trouble lighting it. Is there a new way to light the portal now?

**Comment by SonicBoom213** [comment]
![twilight](https://cloud.githubusercontent.com/assets/9716784/7843762/749d7cce-0471-11e5-9871-fca720c36d54.png)

**Comment by aking4125** [comment]
You need to use a snow globe not the twilight clock.

**Comment by SonicBoom213** [comment]
Ah, thanks for that, didn't know it changed!

**Comment by aking4125** [comment]
Yeah, I believe it was changed because Iceika is more of a side dimension of DRPG. I wonder if DRPG will eventually get more side Dimensions. Probably not though, the current ones still need a lot of work IMO.
