### ISSUE TITLE
Iceika lag?

### ISSUE THREAD

**Issue by SonicBoom213** [DivineRPG/DivineRPG#292]
If it is an issue, I'm pretty sure you guys are aware of it, but I still felt I should ask, is it just me or does the Iceika seem to lag quite a bit? Particularly when the flying mobs are around. I remember this was a problem in an older build, and I can run AoA's dimensions as well as others without any lag, and I was using up less than 500MB of memory. Is it just my computer?

**Comment by Flameminer221** [comment]
I have iceika lag too, I think it may be caused by all the trees and the number of different light/dark contrasts they create.

**Comment by aking4125** [comment]
I don't experience this though my system is fairly beefy.

**Comment by Eternaldoom** [comment]
It's definitely the lighting. Not sure what I can do about it though :/.
