### ISSUE TITLE
divine version bug

### ISSUE THREAD

**Issue by cynsparkletime** [DivineRPG/DivineRPG#293]
where can i find the new update of divine rpg i wanna play.

i sent the person eternaldoom123 on minecraft fourms and he didnt respond for 10 days plz help

ty

**Comment by BossLetsPlays** [comment]
Uhm, you realize this isnt a message board right? You not being able to find an update is not a bug...

**Comment by Eternaldoom** [comment]
The update is still in beta, it has been given to a few testers who have been selected. I've gotten a lot of PMs, and sadly I can't accept them all.
