### ISSUE TITLE
Compitabilty with cauldron 1388 and plus

### ISSUE THREAD

**Issue by ShadowT1me** [DivineRPG/DivineRPG#295]
Here is get a problem with cauldron ( server part ) from here tcpr.ca/cauldron . All version 1388 and above have problem, that bonus sets dont work and dont give any bonuses, with lower version alright.

**Comment by Eternaldoom** [comment]
Cauldron has been abandoned, after the DCMA. That is likely an illegal download site. Since DRPG has been tested and works on normal Forge servers, this isn't a real issue, I have no reason to support obsolete software which seems to be bugged.
