### ISSUE TITLE
Tar needs to be fully implemented

### ISSUE THREAD

**Issue by Flameminer221** [DivineRPG/DivineRPG#296]
Still tar does not burn stuff. When you throw an item on it it will play the lava burning item sound but the item will just bounce around (without the item-on-fire animation) until it despawns or reaches a standstill. Flowing tar, on the other hand, will destroy the item. Just try mining a bunch of stone over an underground tar lake....

What is tar anyway? It has no use anymore as far as I know (it used to be related to arcanium plants if I remember properly) and texture doesn't really look connected. The only use tar has for me is luring in those chompers from the swamp next to my house.

**Comment by Eternaldoom** [comment]
It's supposed to be used in place of water for growing arcana plants.
