### ISSUE TITLE
Mob spawning bug

### ISSUE THREAD

**Issue by THEVOLCO** [DivineRPG/DivineRPG#298]
Hi,
im using the 1.7.10 version of drpg. There is a really aweful bug. Overworld drpg Mobs spawn in modded dimensions. There are also almost no drpg Mobs spawning in the overworld.
Also: Is it a bug or am I just doing something wrong?. I cant enter Vethea for some reason. What could i be making wrong?

**Comment by Eternaldoom** [comment]
By modded dimensions, do you mean DRPG dimensions, or dimensions from another mod? I've tested this with Nevermine, the mob spawning seems fine. Overworld spawn rates were heavily buffed, are you using the latest version? Vethea is now entered using a nightmare bed, not a portal. Make sure your render distance is low and that you've dedicated a decent amount of RAM (Vethea is very resource intensive).

**Comment by Flameminer221** [comment]
When you are in the affected mod dimension bring up the debug f3 screen and find out what biome name it says.

**Comment by THEVOLCO** [comment]
so i am also using nevermine and drpg. i think the Problem maybe is that im not using the latest Version of drpg. i am using Version 2.4.3. Is that the latest Version?

**Comment by THEVOLCO** [comment]
and with modded dimensions i mean all modded ones expect drpg ones.

**Comment by Eternaldoom** [comment]
2.4.3 is not a real version, when did you build the mod?

**Comment by Eternaldoom** [comment]
Yep, tested with the newest versions of DRPG and AoA, the mob spawning is just fine.

**Comment by THEVOLCO** [comment]
Where can i download the latest Version of drpg from?

**Comment by aking4125** [comment]
Here. But it seems you got the copy from a different source I'm guessing?

**Comment by Eternaldoom** [comment]
If you did in fact get it somewhere else, I need to know where ASAP. I don't want the mod being distributed by a 3rd party.

**Comment by Combustible** [comment]
Interestingly, I'm running into a similar problem as the original poster. In my case, I'm seeing Divine RPG Ender mobs spawning in Thaumcraft's Eldritch dimension in a stock version of the modpack "Crundee Craft". This is running the latest version of Divine RPG, 1.4.1.3. Any ideas? Really strange to have triplets spawning in narrow corridors...

![2016-03-12_21 02 30](https://cloud.githubusercontent.com/assets/2737074/13727027/3cd5a9ce-e896-11e5-9e19-93d06401702e.png)

**Comment by Eternaldoom** [comment]
If that dimension uses the end biome type, those'll spawn. I'll add a check to make sure the biome actually has Endermen spawning in it.

**Comment by Combustible** [comment]
Thanks!
