### ISSUE TITLE
Blood Magic and Armor compatibility

### ISSUE THREAD

**Issue by AreaOfMobeus** [DivineRPG/DivineRPG#301]
It seems that Shadow Armor causes a slow effect rather than speed when used with certain mods. Not sure whats causing this, will edit this if I can pinpoint the conflict.

EDIT: Confirmed Blood Magic to be the mod that is conflicting, using latest version for both mods.

EDIT: Confirmed all types of armor that give speed effect slows instead when used with blood magic.

**Comment by Eternaldoom** [comment]
https://github.com/WayofTime/BloodMagic/blob/23106c7129153352262d102b12e8e6744e314a99/src/main/java/WayofTime/alchemicalWizardry/common/AlchemicalWizardryEventHooks.java#L530

WHYYYYY

**Comment by Eternaldoom** [comment]
Fixed here:

https://github.com/WayofTime/BloodMagic/commit/3328c4db745e6278fbe16839c0280b69256385d8
