### ISSUE TITLE
Twilight bow not in creative menu

### ISSUE THREAD

**Issue by Flameminer221** [DivineRPG/DivineRPG#304]
I've bought up this issue before but it was with other more important issues and was never directly acknowledged so I'm bringing it up again more directly.

The twilight bow should be in the creative menu with the other bows, a creative only bow would be helpful. Most people use NEI anyways and those who want to cheat one in can just use NEI to do so, so keeping it out of creative mode would really just make it harder for those who want a twilight bow to spawn one in.

**Comment by Eternaldoom** [comment]
The Twilight Bow is pretty much the equivalent of a technical block in vanilla MC. I can't do anything about people spawning them in with NEI/Commands, but I'm not putting it in creative.
