### ISSUE TITLE
Vethean boss issues

### ISSUE THREAD

**Issue by AreaOfMobeus** [DivineRPG/DivineRPG#306]
So there are a few issues about the bosses in the Vethea dimension.

*Hive Queen - There is no reason whatsoever to try and kill the hive queen at all, as its drops have no relation to the progression in Vethea. Also, it doesn't move. Not sure if this is intended, but it makes the fight uninteresting if its stuck in a corner during the entire thing.
*Dr. Karos - It sometimes gets stuck in a corner and never comes back out. I can still attack it though ranged means, but I can't knock it back to its original position.
*Lady Luna - For a boss that drops the strongest items in Vethea, it seems to be one of the easiest, even with the arena cleared of obstacles.
*Structural Problems - There are four problems with structures: The explosive droppers in Dr. Karos's arena can be destroyed, Raglok's projectiles are blocked by the ceiling, Wreck cannot get out of the little space in the middle due to being to large, and Lady Luna is blocked too often by trees.

**Comment by Flameminer221** [comment]
Yeah, that DRPG wiki says Lady Luna is "one of the hardest boss fights" but IMO wreck is more dangerous (he runs insanely fast and shots these tiny balls that are very deadly). All you have to do is bring one of each weapon type (sword, disk/bow, staff) and you really can't lose, especially if you are on higher ground.

The Hive Queen - can't there be any new weapon drop from it, like some "hive sword?" That would be cool. All the hive queen drops are food items that are inferior to the extremely cheap Hunger-purchased items.

Also, the HQ really should either be spawned from an altar (single-use, maybe) or just not despawn on peaceful. People play on peaceful difficulty, and no one likes to see a hive with no hive queen.

**Comment by AreaOfMobeus** [comment]
Other than having another sword, why not have an item that lets you spawn hive minions as soldiers?

**Comment by Flameminer221** [comment]
...seems like a copy of that "hive staff" from AoA but...anything better than that rip-off food would be good.

**Comment by RadioactiveStud** [comment]
Thanks for reporting the issues and for the sound advice.
