### ISSUE TITLE
Eden cadillions spawning only in dark, not often enough?

### ISSUE THREAD

**Issue by Flameminer221** [DivineRPG/DivineRPG#307]
Could be coincidence, horrible chance, or something. I haven't seen a single naturally spawned eden cadillion. I have seen several bunnies, dozens of eden tomos, and even a greenfeet (and heard some cories). Are they spawning fine anywhere else?

I don't have any mods that alter mob-spawning, and even if I did I don't know why it would only affect eden cadillions. 

EDIT: Well, apparently it's a part of making them automatically hostile, but now the eden cadillions only seem to spawn in the darkness. This gives tomos way too much room to spawn so now eden on the surface is just bunnies and tomos.

**Comment by Eternaldoom** [comment]
Whoops, forgot to make them spawn in all light levels when making them hostile.

**Comment by Flameminer221** [comment]
For some reason, after updating they are still very uncommon and always seem to be near a dark place (I have yet to see any in the light away from darkness). Not sure why...
