### ISSUE TITLE
/fly does not work in survival

### ISSUE THREAD

**Issue by ktole1999** [DivineRPG/DivineRPG#309]
is this intended?

**Comment by Flameminer221** [comment]
There's a command called "/fly"? I'm assuming it's from another mod or from a server plugin.

**Comment by ktole1999** [comment]
yes essentials plugin on server gives that command. why did divinerpg turn the that flag off? works fine without divinerpg.

**Comment by AreaOfMobeus** [comment]
I remember there was an issue about flight items not being compatible with drpg. https://github.com/DivineRPG/DivineRPG/issues/104 I've also found that extra utils wings don't seem to work with drpg.

**Comment by Eternaldoom** [comment]
I actually implemented a system to allow flight compatibility, so the issues involving items are caused by other mods. I'll look into /fly.

**Comment by ktole1999** [comment]
I dont understand how this can be caused by other mods. Without divinerpg everything works fine in the Departed pack regarding flight.

**Comment by Flameminer221** [comment]
He said "the issues involving items are caused by other mods". Items include stuff such as extra utilities wings. /fly is not an item, it's a server plugin command, and it's likely DivineRPG is the problem if everything works fine in the departed pack otherwise.

What does DRPG do to flight, anyway?

**Comment by Eternaldoom** [comment]
For Angelic Armor, it has to control when flight is and isn't allowed for each player. The problem is what people typically do for flight stuff is something like:

If player has item/items, player can fly
Otherwise (and if the player isn't in creative), he/she can't fly at all no matter what

**Comment by ktole1999** [comment]
so basically any mod that has added flight with items will be broken if divinerpg is installed based on how the mod handles flight. Not really what i wanted to hear but ok, i guess.
