### ISSUE TITLE
Attempted to register a entity with invalid ID

### ISSUE THREAD

**Issue by BlayzerQ** [DivineRPG/DivineRPG#313]
Not Work DivineRPG on KCauldron. https://gitlab.prok.pw/Prototik/KCauldron/

java.lang.IllegalArgumentException: Attempted to register a entity with invalid ID: 2500 Name: EnderWatcher Class: class net.divinerpg.entities.vanilla.EntityEnderWatcher at net.minecraft.entity.EntityList.func_75618_a(EntityList.java:87) at net.minecraft.entity.EntityList.func_75614_a(EntityList.java:108) at net.divinerpg.utils.Util.registerDivineRPGMob(Util.java:76) at net.divinerpg.utils.entities.VanillaEntityRegistry.init(VanillaEntityRegistry.java:73) at net.divinerpg.utils.proxies.CommonProxy.preInitServer(CommonProxy.java:143) at net.divinerpg.DivineRPG.preInit(DivineRPG.java:36) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:497) at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:497) at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) at com.google.common.eventbus.EventBus.post(EventBus.java:275) at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:497) at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) at com.google.common.eventbus.EventBus.post(EventBus.java:275) at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556) at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88) at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:319) at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:176) at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) at java.lang.Thread.run(Thread.java:745)

**Comment by Eternaldoom** [comment]
You appear to be using an unofficial version of DRPG. Go download the official version from the thread, this issue has been fixed. Also: What is KCauldron?
