### ISSUE TITLE
Hoverstinger: should it poison?

### ISSUE THREAD

**Issue by Flameminer221** [DivineRPG/DivineRPG#314]
It IS a hover_stinger_ after all. I can see why it would be a bit too much, but even on layer 1 they're not too common and they are easily dispatched with moderately strong melee attacks.

**Comment by Eternaldoom** [comment]
Ehhh, I honestly think that this might make the Hive Queen fight a bit too difficult. Hoverstingers are meant to be an easy mob. I'll think about maybe a short poison effect, but if anyone else would like to give feedback on this it'd be appreciated.
