### ISSUE TITLE
Mandragora doesn't act right

### ISSUE THREAD

**Issue by Flameminer221** [DivineRPG/DivineRPG#316]
Sometimes, they spawn on trees and will follow the player, even to the point where they are "planted" on air. From what I heard, they're supposed to spawn on the ceiling, or at least in places where they can effectively attack the player.

**Comment by Eternaldoom** [comment]
What they were intended to do is to spawn as a normal mob, and occasionally scream and damage nearby players.

**Comment by Flameminer221** [comment]
Well, they hang on the ceiling, but occasionally they are found hanging off of the bottom of trees and move off the trees just to get to the player.
