### ISSUE TITLE
Armor angel is not working correctly

### ISSUE THREAD

**Issue by BlayzerQ** [DivineRPG/DivineRPG#317]
If at first to wear the armor of an angel, fly and then change the set buffs will. Removed after rejoining or death.
You can not endlessly fly (Bug?)

**Comment by BlayzerQ** [comment]
change the set of armor*

**Comment by Flameminer221** [comment]
That's not really a "bug", but angelic armor now uses arcana so you can't fly endlessly (you have to stop and recharge). Rejoining rests the arcana to 0, so...
