### ISSUE TITLE
Texture/Sound Naming

### ISSUE THREAD

**Issue by krwminer** [DivineRPG/DivineRPG#32]
There few textures/sounds that need to be renamed:

- [ ] EnderSpider.png -> enderSpider.png
- [ ] dreamWrecker.png -> dreamwrecker.png
- [ ] karosCannon.png -> karosCannonBlock.png
- [ ] sharkhurt.ogg -> sharkHurt.ogg
- [ ] dreamWreckerHurt.ogg -> dreamwreckerHurt.ogg?

There are a few textures not yet added, (you likely already know this):

- [ ] dreamWoodLeaves_fast.png
- [ ] mintwoodLeaves_fast.png
- [ ] fireWoodLeaves_fast.png
- [ ] hyreWoodLeaves_fast.png

**Comment by Eternaldoom** [comment]
The leaves aren't needed (I'll fix the errors though). Thanks, I'll fix the other names

**Comment by krwminer** [comment]
I do not know if RadioactiveStud has already done this but in the original report I mentioned BlockDivineTable.jar references "divinePlank" when it should reference ""divinePlanks" instead.

**Comment by Eternaldoom** [comment]
It doesn't. Thanks. The divine crafting table might be removed (at least for this update) until it has more uses and we update to 1.8
