### ISSUE TITLE
crash when starting. Any help is appreciated.

### ISSUE THREAD

**Issue by ktole1999** [DivineRPG/DivineRPG#324]
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 7/8/15 7:06 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
at java.net.NetworkInterface.getInterfaceAddresses(Unknown Source)
at net.divinerpg.utils.events.UpdateChecker.isOnline(UpdateChecker.java:32)
at net.divinerpg.client.render.gui.GUIOverlay.drawOverlay(GUIOverlay.java:28)
at net.divinerpg.utils.events.EventOverlay.renderOverlay(EventOverlay.java:20)
at cpw.mods.fml.common.eventhandler.ASMEventHandler_27_EventOverlay_renderOverlay_RenderGameOverlayEvent.invoke(.dynamic)
at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:899)
at net.minecraftforge.client.GuiIngameForge.renderExperience(GuiIngameForge.java:544)
at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:150)
at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1038)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
at java.net.NetworkInterface.getInterfaceAddresses(Unknown Source)
at net.divinerpg.utils.events.UpdateChecker.isOnline(UpdateChecker.java:32)
at net.divinerpg.client.render.gui.GUIOverlay.drawOverlay(GUIOverlay.java:28)
at net.divinerpg.utils.events.EventOverlay.renderOverlay(EventOverlay.java:20)
at cpw.mods.fml.common.eventhandler.ASMEventHandler_27_EventOverlay_renderOverlay_RenderGameOverlayEvent.invoke(.dynamic)
at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:899)
at net.minecraftforge.client.GuiIngameForge.renderExperience(GuiIngameForge.java:544)
at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:150)

-- Affected level --
Details:
Level name: MpServer
All players: 1 total; [EntityClientPlayerMP]
Chunk stats: MultiplayerChunkCache: 0, 0
Level seed: 0
Level generator: ID 00 - default, ver 1. Features enabled: false
Level generator options:
Level spawn location: World: (243,68,-63), Chunk: (at 3,4,1 in 15,-4; contains blocks 240,0,-64 to 255,255,-49), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
Level time: 45693800 game time, 46562392 day time
Level dimension: 0
Level storage version: 0x00000 - Unknown?
Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
Forced entities: 1 total; [EntityClientPlayerMP]
Retry entities: 0 total; []
Server brand: kcauldron,cauldron,craftbukkit,mcpc,fml,forge
Server type: Non-integrated multiplayer server
Stacktrace:
at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
Minecraft Version: 1.7.10
Operating System: Windows 8.1 (amd64) version 6.3
Java Version: 1.7.0_71, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 2473158200 bytes (2358 MB) / 3260547072 bytes (3109 MB) up to 8112832512 bytes (7737 MB)
JVM Flags: 4 total; -Xms256M -Xmx8704M -XX:PermSize=256m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.3.1408 57 mods loaded, 57 mods active
mcp{9.05} [minecraft coder pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
FML{7.10.99.99} [forge mod loader] (forge-1.7.10-10.13.3.1408-1.7.10-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
Forge{10.13.3.1408} [minecraft forge] (forge-1.7.10-10.13.3.1408-1.7.10-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
CodeChickenCore{1.0.6.43} [codechicken core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
NotEnoughItems{1.0.4.107} [not enough items] (NotEnoughItems-1.7.10-1.0.4.107-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
ThaumicTinkerer-preloader{0.1} [thaumic tinkerer core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
OpenModsCore{0.7.3} [openmodscore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
divinerpg{1.4.0.2} [divinerpg] ([1.7.10][smp]DivineRPG-1.4.0.2_1435833372.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
bspkrsCore{6.15} [bspkrscore] ([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
StartingInventory{1.7.10.r03} [startinginventory] ([1.7.10]StartingInventory-universal-1.7.10.r03.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
nevermine{2.0.1} [adventofascension] (AoA-2.2.5-Departed.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
AppleCore{1.1.0} [applecore] (AppleCore-mc1.7.10-1.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
BiblioCraft{1.10.4} [bibliocraft] (BiblioCraft[v1.10.4][mc1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
Baubles{1.0.1.10} [baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
Thaumcraft{4.2.3.5} [thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
Botania{r1.6-190} [botania] (Botania r1.6-190.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
CarpentersBlocks{3.3.6} [carpenter's blocks] (Carpenter's Blocks v3.3.6 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
ChickenChunks{1.3.4.19} [chickenchunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
chisel{2.3.10.37} [chisel 2] (Chisel2-2.3.10.37.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
lootablebodies{1.3.5} [drcyano's lootable bodies] (CyanosLootableBodies-1.3.5-backport.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
props{1.12} [decocraft] (Decocraft-v1.12b_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
Enchiridion{1.1} [enchiridion] (Enchiridion 2-1.7.10-2.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
Enchiridion2{2.0.1} [enchiridion 2] (Enchiridion 2-1.7.10-2.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
EnderStorage{1.4.7.33} [enderstorage] (EnderStorage-1.7.10-1.4.7.33-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
harvestcraft{1.7.10g} [pam's harvestcraft] (Pam's HarvestCraft 1.7.10h.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
Mantle{1.7.10-0.3.2.jenkins184} [mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
Waila{1.5.10} [waila] (Waila-1.5.10_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
TConstruct{1.7.10-1.8.5.build957} [tinkers' construct] (TConstruct-1.7.10-1.8.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
ExtraTiC{1.4.4} [extratic] (ExtraTiC-1.7.10-1.4.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
FastCraft{1.21} [fastcraft] (fastcraft-1.21.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
fastleafdecay{1.0} [fast leaf decay] (FastLeafDecay-1.7.10-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
HardcoreEnderExpansion{1.8} [hardcore ender expansion] (HardcoreEnderExpansion MC-1.7.10 v1.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
inventorytweaks{1.59-dev-152-cf6e263} [inventory tweaks] (InventoryTweaks-1.59-dev-152.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
IronChest{6.0.62.742} [iron chest] (ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
JABBA{1.2.1} [jabba] (Jabba-1.2.1a_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
journeymap{5.0.1} [journeymap] (JourneyMap5.0.1_Unlimited_MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
MineTweaker3{3.0.9B} [minetweaker 3] (MineTweaker3-1.7.10-3.0.9C.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
modtweaker2{0.8.2} [mod tweaker 2] (ModTweaker 2-0.8.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
NEIAddons{1.12.8.29} [nei addons] (neiaddons-1.12.8.29-mc1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
NEIAddons|AppEng{1.12.8.29} [nei addons: applied energistics 2] (neiaddons-1.12.8.29-mc1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
NEIAddons|Botany{1.12.8.29} [nei addons: botany] (neiaddons-1.12.8.29-mc1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
NEIAddons|Forestry{1.12.8.29} [nei addons: forestry] (neiaddons-1.12.8.29-mc1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
NEIAddons|CraftingTables{1.12.8.29} [nei addons: crafting tables] (neiaddons-1.12.8.29-mc1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
NEIAddons|ExNihilo{1.12.8.29} [nei addons: ex nihilo] (neiaddons-1.12.8.29-mc1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
notenoughkeys{@MOD_VERSION@} [notenoughkeys] (NotEnoughKeys-1.7.10-1.0.0b29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
OpenMods{0.7.3} [openmods] (OpenModsLib-1.7.10-0.7.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
OpenBlocks{1.4.3} [openblocks] (OpenBlocks-1.7.10-1.4.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
RedstonePasteMod{1.6.2} [redstone paste] (RedstonePasteMod-1.7.10-1.6.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
SpiceOfLife{1.2.3} [the spice of life] (SpiceOfLife-mc1.7.10-1.2.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
StevesWorkshop{0.5.1} [steve's workshop] (StevesWorkshop-0.5.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
ThaumicTinkerer{unspecified} [thaumic tinkerer] (ThaumicTinkerer-2.5-1.7.10-164.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
TiCTooltips{1.2.4} [tic tooltips] (TiCTooltips-mc1.7.10-1.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
Translocator{1.1.1.14} [translocator] (Translocator-1.7.10-1.1.1.14-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
wawla{1.2.1} [what are we looking at] (Wawla-1.2.1_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
witchery{0.24.1} [witchery] (witchery-1.7.10-0.24.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
Ztones{1.7.10} [ztones] (Ztones-1.7.10-2.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
IguanaTweaksTConstruct{1.7.10-2.1.5.140} [iguana tinker tweaks] (IguanaTinkerTweaks-1.7.10-2.1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.4.0' Renderer: 'GeForce GT 635/PCIe/SSE2'
OpenModsLib class transformers: [gl_capabilities_hook:finished],[player_render_hook:finished],[map_gen_fix:finished],[movement_callback:finished],[stencil_patches:finished]
Class transformer null safety: all safe
Mantle Environment: Environment healthy.
TConstruct Environment: Environment healthy.
Stencil buffer state: Function set: GL30, pool: internal, bits: 8
Launched Version: 1.7.10
LWJGL: 2.9.1
OpenGL: GeForce GT 635/PCIe/SSE2 GL version 4.4.0, NVIDIA Corporation
GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
There is my crash log

**Comment by aking4125** [comment]
Try updating Forge to 1470 or so. According to the report you're using 1408.

**Comment by ktole1999** [comment]
will try that and let you know. ty

**Comment by Eternaldoom** [comment]
Could be a Java bug, I'd update to Java 8.

**Comment by ShadowOfStrelok** [comment]
Im sorry for offtopic, but 1.4.0.4 is for 1.4.7?

**Comment by Flameminer221** [comment]
No, it's for 1.7.10.

**Comment by ShadowOfStrelok** [comment]
Guys, mb compile mod for recommended forge? Not all mods can use latest forge, example is ShaderMod.

**Comment by Eternaldoom** [comment]
It works for any forge version from 1291 onwards.

**Comment by RadioactiveStud** [comment]
Closed until OP responds.
