### ISSUE TITLE
Armor problems

### ISSUE THREAD

**Issue by LemonNick** [DivineRPG/DivineRPG#326]
Properties at a full set of armor - Halit , etc do not add melee damage

**Comment by Eternaldoom** [comment]
SSP or SMP?

**Comment by LemonNick** [comment]
SMP

**Comment by LemonNick** [comment]
tell me how to fix it ? thanks

**Comment by Eternaldoom** [comment]
Are you using Cauldron? I've tested this on SMP before and it works just fine.

**Comment by LemonNick** [comment]
http://tcpr.ca/kcauldron - lates version

**Comment by Eternaldoom** [comment]
People have had issues with this in the past. It isn't DRPG's fault, that's a buggy server.
