### ISSUE TITLE
Dungeon of Arcana generation

### ISSUE THREAD

**Issue by Herzeleid83** [DivineRPG/DivineRPG#327]
There's a major issue with Dungeon of Arcana generation. A lot of rooms have no exit, they're simply blocked with walls of neighbouring rooms. That makes walkable space in this dimension finite and ruins gameplay. And with the latest updates these walls can't be blown up with TNTs. That's a good improvement itself, but there's a big need to remake rooms and make them all connected to each other somehow.

**Comment by NicosaurusRex99** [comment]
Yo @Eternaldoom this is patched now

**Comment by Eternaldoom** [comment]
We added the Frozen Charge as a workaround - blocked doors can now be opened
