### ISSUE TITLE
Divine Dungeon Spawners

### ISSUE THREAD

**Issue by krwminer** [DivineRPG/DivineRPG#33]
The Divine Dungeon Spawners do not seem to spawn anything.

**Comment by Eternaldoom** [comment]
Do you have the latest src?

**Comment by krwminer** [comment]
Yes. Up to date with your latest commit from 17 hours ago. I keep up to date with github and put together a gradle build to make the jar.

I wanted to see where you guys were at. Our family loved playing DRGP and would like to again with the new release.

I might even start helping out with pull requests soon. I am not sure about that.

I do want to make sure that I am helping you guys and not distracting you. Personally I like a list things to fix, rather than keeping it in my head. That is why I am submitting problems that I see.

**Comment by Eternaldoom** [comment]
Alright I'll look at the spawners. You are helping; the point of using github is so that people can submit issues. This will make beta testing a lot easier.
