### ISSUE TITLE
Bug issue with adventure backpack mod

### ISSUE THREAD

**Issue by bablouga** [DivineRPG/DivineRPG#331]
Just found a bug: when you put a bucket of Tar into the tank of the an adventure backpack, the GUI will desync. And if you taking back the Tar from the tank, it will come back to normal.

P.S: Is it normal that i can collect Tar with a normal bucket?

**Comment by Eternaldoom** [comment]
Tar uses forge's fluid system, so this is a problem on the adventure backpack side. And yes, you should be able to use a vanilla bucket.

**Comment by bablouga** [comment]
Okay then.
