### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by LemonNick** [DivineRPG/DivineRPG#332]
A TileEntity Ayeraco Beam(net.divinerpg.blocks.vanilla.container.tileentity.TileEntityAyeracoBeam) located @ -58,59,-68 has thrown an exception during creation, it cannot be created. Report this to the mod author
java.lang.InstantiationException: net.divinerpg.blocks.vanilla.container.tileentity.TileEntityAyeracoBeam
>       at java.lang.Class.newInstance(Class.java:359) ~[?:1.7.0_45]
>       at net.minecraft.tileentity.TileEntity.func_145827_c(TileEntity.java:108) [aor.class:?]
>       at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:525) [aqk.class:?]
>       at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:44) [ChunkIOProvider.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
>       at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15) [ChunkIOProvider.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
>       at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189) [AsynchronousExecutor$Task.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
>       at net.minecraftforge.common.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:354) [AsynchronousExecutor.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
>       at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:30) [ChunkIOExecutor.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
>       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:874) [MinecraftServer.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430) [lt.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:744) [?:1.7.0_45]

**Comment by Eternaldoom** [comment]
If this didn't crash, ignore it for now, but I'll look into it.

**Comment by ShadowOfStrelok** [comment]
Im sorry for second offtopic, but why developers not commiting changes? I cant help nothing because next merge will kill my work(

**Comment by Eternaldoom** [comment]
Because "hype." We don't wanna spoil surprises before they're released.

**Comment by RadioactiveStud** [comment]
Closed until OP responds.
