### ISSUE TITLE
Compile Java failed

### ISSUE THREAD

**Issue by shadic9100** [DivineRPG/DivineRPG#334]
This is what i get when i try to setup.....

C:\Users\William\Desktop\maker\build\sources\java\net\divinerpg\blocks\base\Bloc
kModDoublePlant.java:101: error: method does not override or implement a method
from a supertype
    @Override
    ^
C:\Users\William\Desktop\maker\build\sources\java\net\divinerpg\blocks\base\Bloc
kModFence.java:20: error: cannot find symbol
        setUnlocalizedName(name);
        ^
  symbol:   method setUnlocalizedName(String)
  location: class BlockModFence
C:\Users\William\Desktop\maker\build\sources\java\net\divinerpg\blocks\base\Bloc
kModFence.java:21: error: cannot find symbol
        setTextureName(Reference.PREFIX + name);
        ^
  symbol:   method setTextureName(String)
  location: class BlockModFence
C:\Users\William\Desktop\maker\build\sources\java\net\divinerpg\blocks\base\Bloc
kModFire.java:31: error: cannot find symbol
        setUnlocalizedName(name);
        ^
  symbol:   method setUnlocalizedName(String)
  location: class BlockModFire
C:\Users\William\Desktop\maker\build\sources\java\net\divinerpg\blocks\base\Bloc
kModFire.java:32: error: cannot find symbol
        setTextureName(Reference.PREFIX + name);
        ^
  symbol:   method setTextureName(String)
  location: class BlockModFire
C:\Users\William\Desktop\maker\build\sources\java\net\divinerpg\blocks\base\Bloc
kModFire.java:60: error: method does not override or implement a method from a s
upertype
    @Override
    ^
C:\Users\William\Desktop\maker\build\sources\java\net\divinerpg\blocks\base\port
al\BlockModPortal.java:54: error: cannot find symbol
        setUnlocalizedName(name);
        ^
  symbol:   method setUnlocalizedName(String)
  location: class BlockModPortal
C:\Users\William\Desktop\maker\build\sources\java\net\divinerpg\blocks\base\port
al\BlockModPortal.java:55: error: cannot find symbol
        setTextureName(Reference.PREFIX + name);
        ^
  symbol:   method setTextureName(String)
  location: class BlockModPortal
C:\Users\William\Desktop\maker\build\sources\java\net\divinerpg\blocks\base\Bloc
kModGrass.java:46: error: method does not override or implement a method from a
supertype
    @Override
    ^
C:\Users\William\Desktop\maker\build\sources\java\net\divinerpg\blocks\base\Bloc
kModLadder.java:16: error: cannot find symbol
            setTextureName(Reference.PREFIX + name);
            ^
  symbol:   method setTextureName(String)
  location: class BlockModLadder
C:\Users\William\Desktop\maker\build\sources\java\net\divinerpg\blocks\base\Bloc
kModLadder.java:17: error: cannot find symbol
        setUnlocalizedName(name);
        ^
  symbol:   method setUnlocalizedName(String)
  location: class BlockModLadder
C:\Users\William\Desktop\maker\build\sources\java\net\divinerpg\blocks\base\Bloc
kModLeaves.java:54: error: method does not override or implement a method from a
 supertype
    @Override
    ^
C:\Users\William\Desktop\maker\build\sources\java\net\divinerpg\blocks\base\Bloc
kModLog.java:28: error: cannot find symbol
        setUnlocalizedName(name);
        ^
  symbol:   method setUnlocalizedName(String)
  location: class BlockModLog
C:\Users\William\Desktop\maker\build\sources\java\net\divinerpg\blocks\base\Bloc
kModLog.java:29: error: cannot find symbol
        setTextureName(Reference.PREFIX + name);
        ^
  symbol:   method setTextureName(String)
  location: class BlockModLog
C:\Users\William\Desktop\maker\build\sources\java\net\divinerpg\blocks\base\Bloc
kModLog.java:37: error: method does not override or implement a method from a su
pertype
    @Override
    ^
C:\Users\William\Desktop\maker\build\sources\java\net\divinerpg\blocks\base\Bloc
kModSpawner.java:28: error: cannot find symbol
        setUnlocalizedName(name);
        ^
  symbol:   method setUnlocalizedName(String)
  location: class BlockModSpawner
C:\Users\William\Desktop\maker\build\sources\java\net\divinerpg\blocks\base\Bloc
kModSpawner.java:29: error: cannot find symbol
        setTextureName(Reference.PREFIX + textureName);
        ^
  symbol:   method setTextureName(String)
  location: class BlockModSpawner
C:\Users\William\Desktop\maker\build\sources\java\net\divinerpg\blocks\base\Bloc
kModStairs.java:16: error: cannot find symbol
                setUnlocalizedName(name);
                ^
  symbol:   method setUnlocalizedName(String)
  location: class BlockModStairs
C:\Users\William\Desktop\maker\build\sources\java\net\divinerpg\blocks\base\Bloc
kModTorch.java:22: error: cannot find symbol
        this.setUnlocalizedName(name);
            ^
  symbol: method setUnlocalizedName(String)
C:\Users\William\Desktop\maker\build\sources\java\net\divinerpg\blocks\base\Bloc
kModTorch.java:23: error: cannot find symbol
        this.setTextureName(Reference.PREFIX + name);
            ^
  symbol: method setTextureName(String)
C:\Users\William\Desktop\maker\build\sources\java\net\divinerpg\blocks\base\Bloc
kRedstonelessRails.java:20: error: cannot find symbol
                setUnlocalizedName(name);
                ^
  symbol:   method setUnlocalizedName(String)
  location: class BlockRedstonelessRails
C:\Users\William\Desktop\maker\build\sources\java\net\divinerpg\blocks\base\Bloc
kRedstonelessRails.java:21: error: cannot find symbol
                setTextureName(Reference.PREFIX + name);
                ^
  symbol:   method setTextureName(String)
  location: class BlockRedstonelessRails
C:\Users\William\Desktop\maker\build\sources\java\net\divinerpg\blocks\base\Bloc
kRedstonelessRails.java:143: error: method does not override or implement a meth
od from a supertype
        @Override
        ^
C:\Users\William\Desktop\maker\build\sources\java\net\divinerpg\blocks\base\Bloc
kStupidSpawner.java:30: error: cannot find symbol
        setUnlocalizedName(name);
        ^
  symbol:   method setUnlocalizedName(String)
  location: class BlockStupidSpawner
C:\Users\William\Desktop\maker\build\sources\java\net\divinerpg\blocks\base\Bloc
kStupidSpawner.java:31: error: cannot find symbol
        setTextureName(Reference.PREFIX + textureName);
        ^
  symbol:   method setTextureName(String)
  location: class BlockStupidSpawner
C:\Users\William\Desktop\maker\build\sources\java\net\divinerpg\blocks\base\tile
entity\container\ContainerInfiniteFurnace.java:37: error: cannot find symbol
                super.onCraftGuiOpened(par1ICrafting);
                     ^
  symbol: method onCraftGuiOpened(ICrafting)
C:\Users\William\Desktop\maker\build\sources\java\net\divinerpg\blocks\base\tile
entity\container\ContainerInfiniteFurnace.java:35: error: method does not overri
de or implement a method from a supertype
        @Override
        ^
C:\Users\William\Desktop\maker\build\sources\java\net\divinerpg\blocks\base\tile
entity\container\ContainerInfiniteFurnace.java:93: error: cannot find symbol
                if (FurnaceRecipes.instance().getSmeltingResult(itemstack1) != n
ull)
                                  ^
  symbol:   method instance()
  location: class FurnaceRecipes
C:\Users\William\Desktop\maker\build\sources\java\net\divinerpg\blocks\base\tile
entity\container\ContainerModFurnace.java:40: error: cannot find symbol
                super.onCraftGuiOpened(par1ICrafting);
                     ^
  symbol: method onCraftGuiOpened(ICrafting)
C:\Users\William\Desktop\maker\build\sources\java\net\divinerpg\blocks\base\tile
entity\container\ContainerModFurnace.java:38: error: method does not override or
 implement a method from a supertype
        @Override
        ^
C:\Users\William\Desktop\maker\build\sources\java\net\divinerpg\blocks\base\tile
entity\container\ContainerModFurnace.java:96: error: cannot find symbol
                if (FurnaceRecipes.instance().getSmeltingResult(itemstack1) != n
ull)
                                  ^
  symbol:   method instance()
  location: class FurnaceRecipes
C:\Users\William\Desktop\maker\build\sources\java\net\divinerpg\blocks\iceika\Bl
ockCandyCane.java:42: error: method does not override or implement a method from
 a supertype
        @Override
        ^
C:\Users\William\Desktop\maker\build\sources\java\net\divinerpg\blocks\iceika\Bl
ockCoalstoneFurnace.java:42: error: method does not override or implement a meth
od from a supertype
        @Override
        ^
C:\Users\William\Desktop\maker\build\sources\java\net\divinerpg\blocks\iceika\Bl
ockFrostedChest.java:38: error: cannot find symbol
                setTextureName("ice");
                ^
  symbol:   method setTextureName(String)
  location: class BlockFrostedChest
C:\Users\William\Desktop\maker\build\sources\java\net\divinerpg\blocks\iceika\Bl
ockFrostedChest.java:39: error: cannot find symbol
                setUnlocalizedName(name);
                ^
  symbol:   method setUnlocalizedName(String)
  location: class BlockFrostedChest
C:\Users\William\Desktop\maker\build\sources\java\net\divinerpg\blocks\iceika\Bl
ockFrostedChest.java:99: error: cannot find symbol
                                                entityitem = new EntityItem(w, (
double)((float)x + f), (double)((float)y + f1), (double)((float)z + f2), new Ite
mStack(itemstack.getItem(), j1, itemstack.getMetadata()));

                                         ^
  symbol:   method getMetadata()
  location: variable itemstack of type ItemStack
C:\Users\William\Desktop\maker\build\sources\java\net\divinerpg\blocks\iceika\Bl
ockFrostedChest.java:106: error: cannot find symbol
                        w.updateNeighborsAboutBlockChange(x, y, z, b);
                         ^
  symbol:   method updateNeighborsAboutBlockChange(int,int,int,Block)
  location: variable w of type World
C:\Users\William\Desktop\maker\build\sources\java\net\divinerpg\blocks\iceika\Bl
ockPresentBox.java:32: error: cannot find symbol
                setTextureName(Reference.PREFIX + name);
                ^
  symbol:   method setTextureName(String)
  location: class BlockPresentBox
C:\Users\William\Desktop\maker\build\sources\java\net\divinerpg\blocks\iceika\Bl
ockPresentBox.java:33: error: cannot find symbol
                setUnlocalizedName(name);
                ^
  symbol:   method setUnlocalizedName(String)
  location: class BlockPresentBox
C:\Users\William\Desktop\maker\build\sources\java\net\divinerpg\blocks\iceika\Bl
ockPresentBox.java:82: error: cannot find symbol
                                                entityitem = new EntityItem(w, (
double)((float)x + f), (double)((float)y + f1), (double)((float)z + f2), new Ite
mStack(itemstack.getItem(), j1, itemstack.getMetadata()));

                                         ^
  symbol:   method getMetadata()
  location: variable itemstack of type ItemStack
C:\Users\William\Desktop\maker\build\sources\java\net\divinerpg\blocks\iceika\Bl
ockPresentBox.java:89: error: cannot find symbol
                        w.updateNeighborsAboutBlockChange(x, y, z, b);
                         ^
  symbol:   method updateNeighborsAboutBlockChange(int,int,int,Block)
  location: variable w of type World
C:\Users\William\Desktop\maker\build\sources\java\net\divinerpg\blocks\iceika\Bl
ockWinterberryBush.java:65: error: method does not override or implement a metho
d from a supertype
    @Override
    ^
C:\Users\William\Desktop\maker\build\sources\java\net\divinerpg\blocks\iceika\ti
leentity\TileEntityCoalstoneFurnace.java:6: error: TileEntityCoalstoneFurnace is
 not abstract and does not override abstract method getAccessibleSlotsFromSide(i
nt) in ISidedInventory
public class TileEntityCoalstoneFurnace extends TileEntityInfiniteFurnace {
       ^
C:\Users\William\Desktop\maker\build\sources\java\net\divinerpg\blocks\iceika\ti
leentity\TileEntityFrostedChest.java:9: error: cannot find symbol
                this.setCustomName("Frosted Chest");
                    ^
  symbol: method setCustomName(String)
C:\Users\William\Desktop\maker\build\sources\java\net\divinerpg\blocks\iceika\ti
leentity\TileEntityFrostedChest.java:12: error: method does not override or impl
ement a method from a supertype
        @Override
        ^
C:\Users\William\Desktop\maker\build\sources\java\net\divinerpg\blocks\iceika\ti
leentity\TileEntityPresentBox.java:16: error: TileEntityPresentBox is not abstra
ct and does not override abstract method closeInventory() in IInventory
public class TileEntityPresentBox extends TileEntity implements IInventory {
       ^
C:\Users\William\Desktop\maker\build\sources\java\net\divinerpg\blocks\iceika\ti
leentity\TileEntityPresentBox.java:33: error: method does not override or implem
ent a method from a supertype
        @Override
        ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
100 errors
1 warning
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 38.966 secs

**Comment by Eternaldoom** [comment]
Use the "stable_12" mappings
