### ISSUE TITLE
Mod balanced, like a nevermine

### ISSUE THREAD

**Issue by ShadowOfStrelok** [DivineRPG/DivineRPG#339]
Mod lost that balance, which was in the older versions, and which we all liked. He looked like a nevermine, with a small weapon damage and weak armor. Requires rebalance.

**Comment by Eternaldoom** [comment]
No. It was rebalanced because everything before was disgustingly OP and didn't play well with any other mod involving combat, at all.

**Comment by aking4125** [comment]
100% Agree with Eternaldoom. However, perhaps maybe the durability of most of the mods stuff should be lowered? Also, I feel like the twilight chunks shouldn't be a requirement as it just brings the grind to boring standards.
