### ISSUE TITLE
In a multiplayer game armor has no effect.

### ISSUE THREAD

**Issue by BlayzerQ** [DivineRPG/DivineRPG#340]
In a multiplayer game armor has no effect.
For example Halite set does not increase damage to the server, even in a single game works.

**Comment by Eternaldoom** [comment]
What server jar are you using?

**Comment by BlayzerQ** [comment]
KCauldron
http://tcpr.ca/kcauldron

**Comment by Eternaldoom** [comment]
This causes bugs, it's KCauldrons fault.

**Comment by ShadowOfStrelok** [comment]
But we need to fix it, because KCauldron is a most usable platform.

**Comment by Eternaldoom** [comment]
Um no, KCauldron needs to fix it, it is their problem.

**Comment by aking4125** [comment]
If it's not too much of an issue. I've submitted this issue to what seems to be the official GitLab page for KCauldron here: https://gitlab.prok.pw/Prototik/KCauldron/issues/180

Hopefully they can resolve this issue on their end. Just wanted to report this to the DRPG devs as I find KCauldron to be vastly more useful than forge essentials.
