### ISSUE TITLE
[Enhancement] Plank stairs and slabs and Iceika Planks and saplings

### ISSUE THREAD

**Issue by aking4125** [DivineRPG/DivineRPG#344]
I am glad there are finally planks and saplings for the 5 dimensions. But perhaps maybe add Slabs and stairs to them? Perhaps they can be immune to fire or no mobs from the blocks specific dimension can spawn on them maybe? (Then again if they were slabs it wouldn't matter I guess)

Also, Iceika seemed to have gotten no love in this regard. Perhaps they should receive the same treatment? And what about Vethea trees? Maybe not floating ones for saplings but maybe planks and other stuff to make decorative stuff in there? These are just suggestions.

So far, I haven't found any major issues other than arcana still generating strangely (Issue is already reported and I haven't played too much to really notice) and works so far on my existing world and server. Looking good so far guys!

**Comment by Eternaldoom** [comment]
Saplings may or may not be added for iceika

**Comment by aking4125** [comment]
Thank you for at least looking into it and adding the iceika planks and seemed to have added slabs and stairs too. It shows that least your guys are listening. :+1:
