### ISSUE TITLE
Kobblins do not drop Grass Blocks & Config Request

### ISSUE THREAD

**Issue by Zsashas** [DivineRPG/DivineRPG#348]
I read that they were supposed to drop the block they replaced. Also, any chance of adding a config option to change how these spawn, such as only natural grass blocks, or even disabling completely? They even destroy grass blocks in claims (GriefPrevention plugin). It's getting out of hand on our server.

**Comment by Zsashas** [comment]
It looks like the "drop the grass block" was misunderstood. The grass block appears to drop with gravity like sand (there is a large hole where someone used a quarry, and when we looked down below, there were a bunch of grass blocks below the holes).

Perhaps a config option to toggle between this and having a grass block drop on death instead.

The claims bit is still a valid issue.

**Comment by Eternaldoom** [comment]
Enough people have complained about this that I'll make kobblins just hide in grass instead of replacing it.
