### ISSUE TITLE
Lower spawn rates?

### ISSUE THREAD

**Issue by looterz** [DivineRPG/DivineRPG#351]
Is there any way to do this via the server config?

**Comment by Eternaldoom** [comment]
Nope. I know cauldron servers can have issues with an excessive number of mobs in dimensions. One of the server configs may have an option.

**Comment by looterz** [comment]
Yeah currently every mob spawns in groups of 3, and there are usually 100+ more mobs around you at all times in a biome, way too much. Chokes server performance and makes playing incredibly frustrating.

**Comment by Eternaldoom** [comment]
Can't do anything about it though, sorry. Just try tweaking the server prefs.

**Comment by looterz** [comment]
Try tweaking what, I don't see anything for spawn rates in DivineRPG's config file? or would I be able to put something in?

**Comment by Eternaldoom** [comment]
No, the server config. Is this a vanilla server or something like KCauldron?

**Comment by looterz** [comment]
[Ultra Modded Survival](http://www.technicpack.net/modpack/ultra-modded-survival-101.698929)

**Comment by Eternaldoom** [comment]
What mobs are you talking about by the way?

**Comment by ShadowOfStrelok** [comment]
Guys, i dont think, what you mean, but spawnrates of angry mobs are so low. No spawning glacons and frosts, low spawnrates of dramcryxes, eyes, caveclops and other enemy mobs.
