### ISSUE TITLE
Firefly projectiles do not home in on anything

### ISSUE THREAD

**Issue by Zsashas** [DivineRPG/DivineRPG#352]
Using Crundeecraft pack, DivineRPG version 1.4.1.1

**Comment by RadioactiveStud** [comment]
They should. Does it work with only DivineRPG installed?

**Comment by Zsashas** [comment]
Looks like it's not just the Firefly. None of the "homing" weapons do so. I haven't tried with just Divine RPG, but I tried with mobs from Vanilla, DRPG, and other mods. How is the homing supposed to work?

**Comment by Eternaldoom** [comment]
By "do not home in," do you mean don't reliably hit every time, or are not affected at all?

**Comment by Zsashas** [comment]
They just fly straight every time.
