### ISSUE TITLE
UpdateChecker Freezes server

### ISSUE THREAD

**Issue by Time6628** [DivineRPG/DivineRPG#355]
Every time DivineRPG checks for an update, it freezes the server and prints out this: http://hastebin.com/ehalivowox.avrasm.

**Comment by RadioactiveStud** [comment]
This should be fixed. Do you have the latest version? (1.4.1.3)

**Comment by Time6628** [comment]
I am using 1.4.1.1 in the modpack CrundeeCraft.

**Comment by RadioactiveStud** [comment]
Yeah this is fixed in 1.4.1.3

**Comment by Time6628** [comment]
Still persists in 1.4.1.3.
