### ISSUE TITLE
Wildwood sapling disappearing on dirt

### ISSUE THREAD

**Issue by Flameminer221** [DivineRPG/DivineRPG#356]
The sapling can be placed on wildwood *dirt*, but using bonemeal on it will simply make the sapling disappear, though the particles of the bonemeal appear. It works fine with wildwood grass, and other saplings seem to work fine on both dirt and grass. Tested on single squares of wildwood dirt, 3x3 squares of wildwood dirt, and single squares of wildwood grass.

**Comment by Eternaldoom** [comment]
Fixed for next update.
