### ISSUE TITLE
Server freezes when it can't connect to the update checking server

### ISSUE THREAD

**Issue by ProsperCraft** [DivineRPG/DivineRPG#357]
http://pastebin.com/ciBAX8bt

It seems to check for updates every time a client connects, this is a problem with a lot of users.

The server is freezing for several minutes, then when it recovers it shows the stacktrace above.

Solutions- 
1-please only check for updates on server load
2- better yet-...please add a config option to disable update checking, when you include the mod in a modpack you don't want update checking.

**Comment by RadioactiveStud** [comment]
This should be fixed in the latest version already. What version are you using.

**Comment by ProsperCraft** [comment]
[1.7.10][SMP]DivineRPG-1.4.1.3

**Comment by xaoseric** [comment]
Although this should of been fixed, should still be a way to disable the updater, this pull request should make that possible https://github.com/DivineRPG/DivineRPG/pull/362

**Comment by ProsperCraft** [comment]
Thank you!

**Comment by Eternaldoom** [comment]
Added a config option to disable the update checker.
