### ISSUE TITLE
Players cant connect to the server

### ISSUE THREAD

**Issue by Tennik** [DivineRPG/DivineRPG#359]
Hi!
I just installed a DivineRPG 1.7.10 mod on my server and into my client. But players cant connect to the server (and I also). There is an error during connection:

[SEVERE] FMLIndexedMessageCodec exception caught
16:40:22 java.lang.NullPointerException
16:40:22    at cpw.mods.fml.common.network.FMLOutboundHandler$OutboundTarget$4.selectNetworks(FMLOutboundHandler.java:109) ~[FMLOutboundHandler$OutboundTarget$4.class:1.7.10-1492.152]
16:40:22    at cpw.mods.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:273) ~[FMLOutboundHandler.class:1.7.10-1492.152]
16:40:22    at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
16:40:23    at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
16:40:23    at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637) ~[DefaultChannelHandlerContext.class:?]
16:40:23    at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:115) ~[MessageToMessageEncoder.class:?]
16:40:23    at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
16:40:23    at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
16:40:23    at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
16:40:23    at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688) ~[DefaultChannelHandlerContext.class:?]
16:40:23    at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717) ~[DefaultChannelHandlerContext.class:?]
16:40:23    at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893) ~[DefaultChannelPipeline.class:?]
16:40:23    at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239) ~[AbstractChannel.class:?]
16:40:23    at cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:196) [SimpleNetworkWrapper.class:1.7.10-1492.152]
16:40:23    at net.divinerpg.utils.events.ArcanaHelper.setBarValue(ArcanaHelper.java:91) [ArcanaHelper.class:?]
16:40:23    at net.divinerpg.utils.events.ArcanaTickHandler.onPlayerLoggedOut(ArcanaTickHandler.java:33) [ArcanaTickHandler.class:?]
16:40:23    at cpw.mods.fml.common.eventhandler.ASMEventHandler_37_ArcanaTickHandler_onPlayerLoggedOut_PlayerLoggedOutEvent.invoke(.dynamic) [?:1.7.10-1492.152]
16:40:23    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:1.7.10-1492.152]
16:40:23    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:1.7.10-1492.152]
16:40:23    at cpw.mods.fml.common.FMLCommonHandler.firePlayerLoggedOut(FMLCommonHandler.java:576) [FMLCommonHandler.class:1.7.10-1492.152]
16:40:23    at net.minecraft.server.management.ServerConfigurationManager.disconnect(ServerConfigurationManager.java:437) [oi.class:?]
16:40:23    at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:945) [nh.class:?]
16:40:23    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:162) [nc.class:?]
16:40:23    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
16:40:23    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
16:40:23    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
16:40:23    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
16:40:23    at java.lang.Thread.run(Unknown Source) [?:1.7.0_71]

What can I do with that?

P.S. The version of DivineRPG mod is 1.4.1.3(the latest) and I use a KCauldron 1.7.10-1492 as my server core

**Comment by Eternaldoom** [comment]
This may be a KCauldron issue. The problem is with packets, and nobody has had this issue on a normal forge server.

**Comment by Tennik** [comment]
I also tried on Cauldron with different builds. Can you recommend me a version of cauldron or any other core for 1.7.10? I need a server with mods and plugins on it

**Comment by xaoseric** [comment]
@Eternaldoom it may be related to kcauldron and the updater check when a player first joins. I'll take a look at the logout event as well and see if that causes issues as well. Added a way to disable the updater in my pull request https://github.com/DivineRPG/DivineRPG/pull/362

**Comment by kirich1368** [comment]
all exactly such an error in DivineRPG 1.4.1.3

**Comment by AstralScourge** [comment]
1.7.10 is no longer supported
