### ISSUE TITLE
crabs spawning

### ISSUE THREAD

**Issue by katsantacruz** [DivineRPG/DivineRPG#360]
Is there a way for me to edit your code, i build a house along a beach, and the crabs and king crabs are killing me, they are spawning inside my house, no matter what i did, they keep reappearing, tried getting rid of all the sand, made sure every dark spot was bright, enclosed areas, tried different blocks for walls, they keep spawning inside and on my roof.  Is there a way for me to stop that or remove those 2 mobs completely.

**Comment by Eternaldoom** [comment]
They're neutral mobs. Just don't attack them. You can stop all mobs from spawning by building your floor with slabs.
