### ISSUE TITLE
Vanilla armor replacement

### ISSUE THREAD

**Issue by Andrey96** [DivineRPG/DivineRPG#361]
It's done wrong. For example leather armor can't be dyed anymore. Also textures of armor are duplicated, it's wrong (because of this I have to edit texturepack to get this replacement textured). Also default vanilla armor could be found in dungeons or dropped from mobs. Instead of replacing crafting recipe, armor item should be replaced by extended vanilla armor, not replicated one.

**Comment by Eternaldoom** [comment]
You can't actually replace items like that. However, due to balance changes in the next update armor will no longer be replaced.
