### ISSUE TITLE
Ticking entity server crashes

### ISSUE THREAD

**Issue by axelpx** [DivineRPG/DivineRPG#363]
Here is the crashlog. Any ideas?

---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 3/10/16 7:21 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
    at net.minecraft.entity.EntityLivingBase.func_142014_c(EntityLivingBase.java:2355)
    at net.minecraft.entity.ai.EntityAIHurtByTarget.func_75249_e(SourceFile:35)
    at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:94)
    at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:579)
    at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2066)
    at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:388)
    at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:36)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1899)
    at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:213)
    at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:41)
    at net.minecraft.world.World.func_72866_a(World.java:2674)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:800)
    at net.minecraft.world.World.func_72870_g(World.java:2623)
    at net.minecraft.world.World.func_72939_s(World.java:2423)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:633)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
    at java.lang.Thread.run(Thread.java:745)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.entity.EntityLivingBase.func_142014_c(EntityLivingBase.java:2355)
    at net.minecraft.entity.ai.EntityAIHurtByTarget.func_75249_e(SourceFile:35)
    at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:94)
    at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:579)
    at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2066)
    at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:388)
    at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:36)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1899)
    at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:213)
    at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:41)
    at net.minecraft.world.World.func_72866_a(World.java:2674)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:800)
    at net.minecraft.world.World.func_72870_g(World.java:2623)

-- Entity being ticked --
Details:
    Entity Type: DRPGDungeonPrisoner (net.divinerpg.entities.arcana.EntityDungeonPrisoner)
    Entity ID: 8246
    Entity Name: Dungeon Prisoner
    Entity's Exact location: -8215.62, 33.83, -3275.14
    Entity's Block location: World: (-8216,33,-3276), Chunk: (at 8,2,4 in -514,-205; contains blocks -8224,0,-3280 to -8209,255,-3265), Region: (-17,-7; contains chunks -544,-224 to -513,-193, blocks -8704,0,-3584 to -8193,255,-3073)
    Entity's Momentum: -0.22, 0.29, 0.46
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:2423)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:633)

-- Affected level --
Details:
    Level name: DIM56
    All players: 1 total; [EntityPlayerMP['SonicRainboom'/1227, l='DIM56', x=-8211.66, y=32.94, z=-3276.02](SonicRainboom at -8211.658101802206,32.9375,-3276.0219733824333)]
    Chunk stats: ServerChunkCache: 122 Drop: 0
    Level seed: 8848270868533809587
    Level generator: ID 04 - RWG, ver 0. Features enabled: true
    Level generator options: 
    Level spawn location: World: (0,64,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 5409506 game time, 5409506 day time
    Level dimension: 56
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 99155 (now: false), thunder time: 4170 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
    at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    KCauldron Version: pw.prok:KCauldron:1.7.10-1614.200 Official
    Plugins: EnchLimiter, RemoteToolkitPlugin, VipZeroFIX, SuperCensor, MorePlayerModels2, GetBuy, SimpleReserve, MajoritySleeps, MaxBans, VoxelSniper, SushnostkObana, ItemRestrict, VedroGovna, dynmap, Itemizer, WorldEdit, Spawn_Bed, ForeverFalling, OpenInv, Essentials, iTags, ClearLag, WorldBorder, BetterPvP, ProtocolLib, AutoSaveWorld, broad-cast, kits, PermissionsEx, ModFixNG, mcMMO, CustomHelp, Vault, MassiveCore, BoomcMMoReward, Herochat, MobArena, HolographicDisplays, VipZero, WorldGuard, Factions, EssentialsProtect, PhatLoots, EssentialsSpawn, MyWarp, MarriageMaster, pvparena, HeroBounty, RPG_Items, ScoreboardStats, Fe, VanishNoPacket, ColoredTablist, WGCustomFlags, DreamfinityGlobal, MPN, Dynmap-Factions, RegionFill, WGDropFlags
    Disabled Plugins: 
    Operating System: Linux (amd64) version 3.14.32-xxxx-grs-ipv6-64
    Java Version: 1.8.0_45, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 4212134024 bytes (4017 MB) / 5368709120 bytes (5120 MB) up to 5368709120 bytes (5120 MB)
    JVM Flags: 7 total; -Xms5120M -Xmx5120M -XX:+UseG1GC -XX:MaxGCPauseMillis=50 -XX:+UseFastAccessorMethods -XX:SurvivorRatio=8 -XX:+AggressiveOpts
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 95 mods loaded, 94 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](KCauldron-1.7.10-1614.200.jar) 
    UCHIJAAAA   Forge{10.13.4.1614} [Minecraft Forge](KCauldron-1.7.10-1614.200.jar) 
    UCHIJAAAA   kimagine{0.2} [KImagine](minecraft.jar) 
    UCHIJAAAA   AM2-Preloader{0.0.3} [AMCore](minecraft.jar) 
    UCHIJAAAA   CodeChickenCore{1.0.7.45} [CodeChicken Core](minecraft.jar) 
    UCHIJAAAA   MobiusCore{1.2.5} [MobiusCore](minecraft.jar) 
    UCHIJAAAA   ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) 
    UCHIJAAAA   WitchingGadgetsCore{1.1.10} [Witching Gadgets Core](minecraft.jar) 
    UCHIJAAAA   ClientFixer{1.0} [ClientFixer](minecraft.jar) 
    UCHIJAAAA   <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCHIJAAAA   malisiscore{1.7.10-0.10.5+unknown-b0.git-unknown} [Malisis Core](malisiscore-1.7.10-0.10.5.jar) 
    UCHIJAAAA   AnimationAPI{1.2.4} [AnimationAPI](AnimationAPI-1.7.10-1.2.4.jar) 
    UCHIJAAAA   arsmagica2{1.4.0.009} [Ars Magica 2](1.7.10_AM2-1.4.0.009.jar) 
    UCHIJAAAA   divinerpg{1.4.1.3} [DivineRPG]([1.7.10][SMP]DivineRPG-1.4.1.3.jar) 
    UCHIJAAAA   antiqueatlas{1.7.10-4.2.10} [Antique Atlas](antiqueatlas-1.7.10-4.2.10.jar) 
    UCHIJAAAA   Aquaculture{1.2.3} [Aquaculture](Aquaculture-1.7.10-1.2.5.15.jar) 
    UCHIJAAAA   asielib{0.3.4} [asielib](AsieLib-1.7.10-0.3.4.jar) 
    UCHIJAAAA   Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
    UCHIJAAAA   Thaumcraft{4.2.3.5} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.5.jar) 
    UCHIJAAAA   Waila{1.5.8} [Waila](Waila-1.5.8a_1.7.10.jar) 
    UCHIJAAAA   Automagy{0.27.1} [Automagy](Automagy-1.7.10-0.27.1.jar) 
    UCHIJAAAA   Backpack{2.0.1} [Backpack](backpack-2.0.1-1.7.x.jar) 
    UCHIJAAAA   BiomesOPlenty{2.1.0} [Biomes O' Plenty](BiomesOPlenty-1.7.10-2.1.0.1057-universal.jar) 
    UCHIJAAAA   AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry](BloodMagic-1.7.10-1.3.3-17.jar) 
    UCHIJAAAA   Botania{r1.8-248} [Botania](Botania r1.8-248.jar) 
    UCHIJAAAA   CarpentersBlocks{3.3.8} [Carpenter's Blocks](Carpenter's Blocks v3.3.8 - MC 1.7.10.jar) 
    UCHIJAAAA   ChickenChunks{1.7.10-1.0.8} [ChickenChunks](ChickenChunks-1.7.10-1.7.10-1.0.8-universal.jar) 
    UCHIJAAAA   TwilightForest{2.3.7} [The Twilight Forest](twilightforest-1.7.10-2.3.7.jar) 
    UCHIJAAAA   ForgeMultipart{1.2.0.345} [Forge Multipart](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHIJAAAA   chisel{2.4.1.4beaeeb} [Chisel 2](Chisel2.jar) 
    UCHIJAAAA   ctmlib{1.0.1.5} [CTMLib](Chisel2.jar) 
    UCHIJAAAA   CoFHCore{1.7.10R3.0.3} [CoFH Core](CoFHCore-[1.7.10]3.0.3-303.jar) 
    UCHIJAAAA   CraftHeraldry{1.1.3} [CraftHeraldry](CraftHeraldry 1.1.3.jar) 
    UCHIJAAAA   customnpcs{1.7.10d} [CustomNpcs](CustomNPCs_1.7.10d.jar) 
    UCHIJAAAA   DragonsRadioMod{1.7.1} [Dragon's Radio Mod](Dragon's Radio Mod-MC1.7.10-1.7.1.jar) 
    UCHIJAAAA   DummyCore{1.13} [DummyCore](DummyCore1.13.jar) 
    UCHIJAAAA   Dynmap{2.1-104} [Dynmap](Dynmap-2.1-forge-1.7.10.jar) 
    UCHIJAAAA   EnderStorage{1.4.7.37} [EnderStorage](EnderStorage-1.7.10-1.4.7.37-universal.jar) 
    UCHIJAAAA   harvestcraft{1.7.10j} [Pam's HarvestCraft](Pam's HarvestCraft 1.7.10Lb.jar) 
    UCHIJAAAA   Mantle{1.7.10-0.3.2.jenkins191} [Mantle](Mantle-1.7.10-0.3.2b.jar) 
    UCHIJAAAA   TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct](TConstruct-1.7.10-1.8.8.jar) 
    UCHIJAAAA   ExtraTiC{1.4.5} [ExtraTiC](ExtraTiC-1.7.10-1.4.5.jar) 
    UCHIJAAAA   farseek{1.0.3} [Farseek](Farseek-1.0.3.jar) 
    UCHIJAAAA   flansmod{4.10.0} [Flan's Mod](Flans Mod-1.7.10-4.10.0.jar) 
    UCHIJAAAA   ThaumicTinkerer{unspecified} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-164.jar) 
    UCHIJAAAA   ForbiddenMagic{1.7.10-0.572} [Forbidden Magic](Forbidden Magic-1.7.10-0.572.jar) 
    UCHIJAAAA   gokiStats{1.0.0} [gokiStats](Goki-Stats-Mod-1.7.2.jar) 
    UCHIJAAAA   HardcoreEnderExpansion{1.8.5} [Hardcore Ender Expansion](HardcoreEnderExpansion  MC-1.7.10  v1.8.5.jar) 
    UCHIJAAAA   IronChest{6.0.62.742} [Iron Chest](ironchest-1.7.10-6.0.62.742-universal.jar) 
    UCHIJAAAA   JABBA{1.2.1} [JABBA](Jabba-1.2.1a_1.7.10.jar) 
    UCHIJAAAA   TeNNoX_KeyAndCodeLock{1.4} [KeyAndCodeLock](Key-and-Code-Lock-Mod-1.7.10.jar) 
    UCHIJAAAA   lycanitesmobs{1.13.0.5 - MC 1.7.10} [Lycanites Mobs](LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    UCHIJAAAA   arcticmobs{1.13.0.5 - MC 1.7.10} [Lycanites Arctic Mobs](LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    UCHIJAAAA   demonmobs{1.13.0.5 - MC 1.7.10} [Lycanites Demon Mobs](LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    UCHIJAAAA   desertmobs{1.13.0.5 - MC 1.7.10} [Lycanites Desert Mobs](LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    UCHIJAAAA   forestmobs{1.13.0.5 - MC 1.7.10} [Lycanites Forest Mobs](LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    UCHIJAAAA   freshwatermobs{1.13.0.5 - MC 1.7.10} [Lycanites Freshwater Mobs](LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    UCHIJAAAA   infernomobs{1.13.0.5 - MC 1.7.10} [Lycanites Inferno Mobs](LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    UCHIJAAAA   junglemobs{1.13.0.5 - MC 1.7.10} [Lycanites Jungle Mobs](LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    UCHIJAAAA   mountainmobs{1.13.0.5 - MC 1.7.10} [Lycanites Mountain Mobs](LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    UCHIJAAAA   plainsmobs{1.13.0.5 - MC 1.7.10} [Lycanites Plains Mobs](LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    UCHIJAAAA   saltwatermobs{1.13.0.5 - MC 1.7.10} [Lycanites Saltwater Mobs](LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    UCHIJAAAA   shadowmobs{1.13.0.5 - MC 1.7.10} [Lycanites Shadow Mobs](LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    UCHIJAAAA   swampmobs{1.13.0.5 - MC 1.7.10} [Lycanites Swamp Mobs](LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
    UCHIJAAAA   mdeco{0.3.5} [Magical Decorations](MagicalDecorations-0.3.5.jar) 
    UCHIJAAAA   malisisdoors{1.7.10-1.4.3} [Malisis' Doors](malisisdoors-1.7.10-1.4.3.jar) 
    UCHIJAAAA   MoarSigns{1.1.4} [MoarSigns](MoarSigns-1.7.10-1.1.4.jar) 
    UCHIJAAAA   cfm{3.4.8} [�9MrCrayfish's Furniture Mod](MrCrayfishFurnitureModv3.4.8%281.7.10%29.jar) 
    UCHIJAAAA   MapWriter{2.1.2} [MapWriter](Opis-1.2.5_1.7.10.jar) 
    UCHIJAAAA   Opis{1.2.5} [Opis](Opis-1.2.5_1.7.10.jar) 
    UCHIJAAAA   libsandstone{1.0.0} [libsandstone](LibSandstone-1.0.0.jar) 
    UCHIJAAAA   xreliquary{1.2} [Reliquary](Reliquary-1.2.257.jar) 
    UCHIJAAAA   RWG{Alpha 1.3.2} [Realistic World Gen Alpha](RWG-alpha-1.3.2.jar) 
    UCHIJAAAA   streams{0.1.3} [Streams](Streams-0.1.3.jar) 
    UCHIJAAAA   TaintedMagic{1.1.6.4} [Tainted Magic](TaintedMagic-1.1.6.4.jar) 
    UCHIJAAAA   tcnodetracker{1.1.1} [TC Node Tracker](tcnodetracker-1.7.10-1.1.1.jar) 
    UCHIJAAAA   ThaumcraftMobAspects{1.7.2-2A} [Thaumcraft Mob Aspects](ThaumcraftMobAspects-1.7.2-2A.jar) 
    UCHIJAAAA   thaumcraftneiplugin{@VERSION@} [Thaumcraft NEI Plugin](thaumcraftneiplugin-1.7.10-1.7a.jar) 
    UCHIJAAAA   TU{1.0} [Thaumic Upholstry](Thaumic_Upholstery-1.2_1.7.10.jar) 
    UCHIJAAAA   thaumicbases{1.3.1710.2} [Thaumic Bases](ThaumicBases-1.3.1710.4.jar) 
    UCHIJAAAA   ThaumicExploration{0.6.0} [Thaumic Exploration](ThaumicExploration-1.7.10-1.1-53.jar) 
    UCHIJAAAA   TravellersGear{1.16.5} [Traveller's Gear](TravellersGear-1.7.10-1.16.5.jar) 
    UCHIJAAAA   examplemod{1.0} [Example Mod](VipCrystal.jar) 
    UCHIJAAAA   vips{0.0.3} [Mayakplay DF Vip](VipCrystal.jar) 
    UCHIJAAAA   Wintercraft{1.1.3} [Wintercraft](Wintercraft-1.7.10-1.1.3.jar) 
    UCHIJAAAA   witchery{0.24.1} [Witchery](witchery-1.7.10-0.24.1.jar) 
    UCHIJAAAA   WitchingGadgets{1.1.10} [Witching Gadgets](WitchingGadgets-1.7.10-1.1.10.jar) 
    UCHIJAAAA   WR-CBE|Core{1.4.1.9} [WR-CBE Core](WR-CBE-1.7.10-1.4.1.9-universal.jar) 
    UCHIJAAAA   WR-CBE|Addons{1.4.1.9} [WR-CBE Addons](WR-CBE-1.7.10-1.4.1.9-universal.jar) 
    UCHIJAAAA   WR-CBE|Logic{1.4.1.9} [WR-CBE Logic](WR-CBE-1.7.10-1.4.1.9-universal.jar) 
    UCHIJAAAA   XW{1.0.1.4c} [Xerxes Weapons Mod](XW-1.7.10-1.0.1.4c.jar) 
    UCHIJAAAA   McMultipart{1.2.0.345} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHIJAAAA   ForgeMicroblock{1.2.0.345} [Forge Microblocks](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UD  asielibcore{} [AsieLib CoreMod](minecraft.jar) 
    CoFHCore: -[1.7.10]3.0.3-303
    Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: bukkit
    TConstruct Environment: Environment healthy.
    Hardcore Ender Expansion: CAUTION! Ars Magica 2 is not supported by HEE, if the crash is caused by a conflict of the two mods, it will very likely not be possible to fix.
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 6 / 60; [EntityPlayerMP['SonicRainboom'/1227, l='DIM56', x=-8211.66, y=32.94, z=-3276.02](SonicRainboom at -8211.658101802206,32.9375,-3276.0219733824333), EntityPlayerMP['PbiCb'/1175, l='tcracy', x=-2760.13, y=74.00, z=630.36](PbiCb at -2760.128206778364,74.0,630.3590458067696), EntityPlayerMP['terik800'/1786, l='tcracy', x=-1330.86, y=66.13, z=5587.70](terik800 at -1330.862500011921,66.125,5587.699999988079), EntityPlayerMP['Pogreb_ExE'/1785, l='tcracy', x=-2763.43, y=74.00, z=633.06](Pogreb_ExE at -2763.4325430831477,74.0,633.0570110831862), EntityPlayerMP['AndreeGG'/2302, l='tcracy', x=622.18, y=11.00, z=-376.50](AndreeGG at 622.17830346561,11.0,-376.50332236243884), EntityPlayerMP['Fomka'/5461, l='tcracy', x=-2762.67, y=79.00, z=635.70](Fomka at -2762.6733620196665,79.0,635.7009876345921)]
    Is Modded: Definitely; Server brand changed to 'kcauldron,cauldron,craftbukkit,mcpc,fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by AstralScourge** [comment]
1.7.10 is no longer supported
