### ISSUE TITLE
Duplicate worlds

### ISSUE THREAD

**Issue by allinminecraft** [DivineRPG/DivineRPG#365]
Hi all, i am using mod on KCauldron 1.7.0 version. On start all dimension folders created by dimension ID: example **DIM50**, **DIM51**, etc.
But in game, at the time of teleport to any dimension, created another folder: **Eden**, **The Wildwood**, etc.
Further, I can move to dimensions in random order.
[http://s50.radikal.ru/i128/1604/46/15569b08d97d.png](http://s50.radikal.ru/i128/1604/46/15569b08d97d.png)

**Comment by ensirius** [comment]
Same for me

**Comment by allinminecraft** [comment]
The problem is solved.

**Comment by ensirius** [comment]
@allinminecraft how you solved problem?
