### ISSUE TITLE
Invisible mods

### ISSUE THREAD

**Issue by ensirius** [DivineRPG/DivineRPG#366]
Like in older versions of Divine RPG, still exists bug, when mob is invisible. You can hear it sounds, but cant see it. Can be fixed by rejoning server.

**Comment by Eternaldoom** [comment]
This is a forge bug, there's sadly nothing I can do about it.

**Comment by ShadowOfStrelok** [comment]
But in other mods we can always see any mobs. Maybe we have any problem?

**Comment by Eternaldoom** [comment]
AoA has this same problem. IIRC, I first saw it reported for TConstruct. So, no.
