### ISSUE TITLE
Some players get "Internet server error"

### ISSUE THREAD

**Issue by dig** [DivineRPG/DivineRPG#367]
Error Log: http://pastebin.com/pTfmkKbR

Explanation of issue: some players are getting kicked on join "internal server error"

How to recreate this issue: Not sure

Modpack Name: CrundeeCraft (ATLauncher)

Mods Installed: https://www.atlauncher.com/pack/CrundeeCraft

Forge Version: 1614.46

**Comment by mat41997** [comment]
http://pastebin.com/ycJiqAru

**Comment by LemADEC** [comment]
dup of #379

**Comment by AstralScourge** [comment]
1.7.10 is no longer supported.
