### ISSUE TITLE
[Possible Bug] Updater caused server hanging

### ISSUE THREAD

**Issue by mingl0280** [DivineRPG/DivineRPG#371]
Hi,
     I'm having an issue with Divine RPG when a client tried to connect to the server. This action seems triggered the mod to check for updates. Unfortunatelly, it can't always be done and when it happens, the whole server hanged up and wait for timeout of the updater. Then all the players are kicked out because there is a timeout between server and client.
    The mod version is the latest, 1.4.1.3 and Forge version is 10.13.4.1614.
    Environment: JRE 1.8.0 - update 91, Windows 2008 r2 x64.
    The hanging log is here: https://gist.github.com/mingl0280/484965022c964bb3a845d5ead7f68c40
    Please check this out and probably to have a configuration command to stop the updater.

Thank you.

**Comment by ensirius** [comment]
Problem already reported #357

**Comment by AstralScourge** [comment]
1.7.10 is long unsupported, and in 1.12.2 the update checker uses a different system
