### ISSUE TITLE
Wildwood chickaxe and some wildwood blocks\items\entities still missing textures

### ISSUE THREAD

**Issue by ShadowOfStrelok** [DivineRPG/DivineRPG#375]

**Comment by ShadowOfStrelok** [comment]
Pickaxe, i mean

**Comment by ensirius** [comment]
Chickaxe :D

**Comment by ShadowOfStrelok** [comment]
There are many textures in the resource folder, but they are not displaying in the game

**Comment by ShadowOfStrelok** [comment]
But i see, developers abandoned this mod. WTF, guys? lets do the fucking latest bugfix

**Comment by ShadowOfStrelok** [comment]
Hey, guys, myou have any idea, why wildwood textures not displaying? i checked names, ist normally

**Comment by ShadowOfStrelok** [comment]
HEEEEY

**Comment by ensirius** [comment]
Mod is dead

**Comment by ShadowOfStrelok** [comment]
F.U.C.K! We can reanimate this?

**Comment by Eternaldoom** [comment]
There's stuff in the resources folder that isn't part of the game, it was either an experiment or was replaced.

The mod's development is on hold, it may be resumed eventually.

**Comment by ShadowOfStrelok** [comment]
What do you mean for this "There's stuff in the resources folder that isn't part of the game, it was either an experiment or was replaced."? @Eternaldoom

**Comment by Eternaldoom** [comment]
The wildwood shickaxe isn't meant to be in the game.
