### ISSUE TITLE
Is this DivineRPG or AoA? I have them both - net.nevermine.resource.tribute.tributeHelper.setAll

### ISSUE THREAD

**Issue by ProsperCraft** [DivineRPG/DivineRPG#379]
https://gist.github.com/ProsperCraft/8f393912ca900358b255f27d5998c6f9

I am getting this in console with [1.7.10][SMP]DivineRPG-1.4.1.3 and AoA-2.4.B

**Comment by ProsperCraft** [comment]
I just got this perhaps it is related.

https://gist.github.com/ProsperCraft/7580924a8d6e013c7d1b611a4efa44c0

**Comment by Eternaldoom** [comment]
The first one is AoA, the second one is DRPG.

**Comment by LemADEC** [comment]
I bet this only happens right after a player fails to login or get kicked while connecting.

**Comment by AstralScourge** [comment]
Neither mod supports 1.7.10 anymore.
