### ISSUE TITLE
3D-file of the Enthralled Dramcryx

### ISSUE THREAD

**Issue by Syndesi** [DivineRPG/DivineRPG#383]
Hi,

today I created a printable 3D-file of the Enthralled Dramcryx and wanted to give you the rights of the file :D 
[Dramcryx.zip](https://github.com/DivineRPG/DivineRPG/files/1549654/Dramcryx.zip)

P.S.: Maybe the scaling isn't right, but it can be changed in nearly every software :)

**Comment by Eternaldoom** [comment]
Oh my goodness! Thanks!
