### ISSUE TITLE
Mobs not spawning in DVRPG Dimensions

### ISSUE THREAD

**Issue by jfrogale** [DivineRPG/DivineRPG#386]
I've been using this mod for a while, and I've encountered the same issue in each and every one of my worlds: dimension-specific mobs never spawn in their dimensions (or anywhere, for that matter). Only recently (as in a few hours before I wrote this) have Eden mobs spawned in the Eden dimension, and the blue ones in their dimension, but the Appalachia and Skythern dimensions still remain empty. Mortum is fine, oddly enough, and I have no idea what Vethea or the Dungeon look like in general (never bothered with them). Other mobs, such as Grimoire's of Gaia or (sometimes) vanilla mobs spawn like normal, and I know my issue isn't with mod downloads (i got it right from your MCForum post). Also, something of note is that, in my most recent world, the Skythern biome is named "Storage Cell," while every other main dimension was normal. If needed, I can provide the whole dimension/biome ID list. Thank you in advance, and if one of the mods reads/answers this, then  I would like to say that y'all've done some amazing work with this mod, and I hope you guy(s) are doing well

**Comment by jfrogale** [comment]
I should probably mention that i've been using 1.4.0.5 for a while, and my switching to the latest build changed nothing

**Comment by AquosStormfront** [comment]
Ive had this issue too for a while now. Iceika has only vanilla mobs in it, and all of the divine dimensions are flooded with vanilla mobs

**Comment by LucasTaillebourg** [comment]
Hey, I do have the same issue on the latest version, is there any troubleshooting things to do , any solution or any update on this issue ?

**Comment by AstralScourge** [comment]
@LucasTaillebourg I advise making sure you do not have CustomMobSpawner or something else installed that can mess with spawns

**Comment by AstralScourge** [comment]
I'll assume the reaction means your problem is resolved.

As for the older posts, a biome conflict is the most likely cause of divine dimensions being filled with vanilla mobs, and possibly the first issue as well (which may be another mod messing with stuff). AntiIDConflict can help with that for 1.7.10 players, or you can update to 1.12 where biome id conflicts generally do not exist due to manually configured IDs being phased out.
