### ISSUE TITLE
Divine RPG extremely lags with Biomes'o'plenty

### ISSUE THREAD

**Issue by Begisso** [DivineRPG/DivineRPG#388]
10 fps max in every DRPG(1.12.2) dimension with biomes'o'plenty(1.12.2)
Lags disappeared when I disabled b'o'p. How I can play drpg with bop normally?

**Comment by NicosaurusRex99** [comment]
Wrong issue tracker but this was patched over here https://github.com/NicosaurusRex99/DivineRPG/issues/19
