### ISSUE TITLE
Divinerpg 1.4.1.4 stuff to potentially fix

### ISSUE THREAD

**Issue by velocityraptor-real** [DivineRPG/DivineRPG#389]
Forge version: forge-1.7.10-10.13.4.1448-1.7.10
DivineRPG version: [1.7.10][SMP]DivineRPG-1.4.1.4.jar
Link to crash log if applicable: (please use a paste site such as gist, do not attach the .txt or paste the log inline)

Steps to reproduce:

    kill wildfire in nether; place or remove Frozen wood slab; Hit or kill a Hell pig in the nether; try to craft with eucalyptus planks; break frosted door with Silk touch in Icekia or search in crative for the item

What I expected to happen:
Death soud of Wildfire; Frozen wood slabs making wood-sounds when placing or removing the blocks; Hell pigs having sounds; basic crafting with eucalyptus planks: sticks, crafting tables, etc. ; Frosted door item existing

What happened instead:
Death sound of Wildfire is a stevesound; Frozen wood slabs making stone sounds when placing or removing the blocks; Hell pigs making stevesounds; unable to craft sticks, crafting tables, etc. with eukalyptus planks; there is no Frosted door item

Potential fix:
Add death sound to Wildfire (maybe use the Wildfire-being-damaged-sound); use oak wood planks sound for the Frozen wood slabs; giving the Hell pig pig-like sounds; give to the eucalyptus planks basic crafting recipes; add Frosted door item to game

P.S: Love the game and play it more than any other mod. :)

**Comment by AstralScourge** [comment]
1.7.10 is no longer supported.
