### ISSUE TITLE
Parasecta

### ISSUE THREAD

**Issue by krwminer** [DivineRPG/DivineRPG#39]
When I exit from looking at my inventory see a Parasecta boss bar for a second and then it goes away.

I am using the latest NEI if that matters.

**Comment by Eternaldoom** [comment]
That's likely because NEI renders the boss in a spawner

**Comment by krwminer** [comment]
I believe I am always in Creative mode so it does not have any rendered spawners on the side. I will double check when I get home from work.

**Comment by krwminer** [comment]
I have not seen this again. Lets close it down. I can post it again if it pops up.
