### ISSUE TITLE
Can't fly with DivineRPG

### ISSUE THREAD

**Issue by MeXaHu3M** [DivineRPG/DivineRPG#392]
I can't fly using bat/ifrit/ghast morphs from metamorph and using angel ring from extrautilities2

**Comment by MeXaHu3M** [comment]
ifrit = blaze. Also GravitationSuite addon for industrial craft 2 add a gravitation chestplate, but it also can't fly. I'm playing on minecraft 1.12.2

**Comment by NicosaurusRex99** [comment]
Is this still present?

**Comment by MeXaHu3M** [comment]
Looks like it's ok now

пн, 27 июл. 2020 г. в 06:19, Naturix <notifications@github.com>:

**Comment by AstralScourge** [comment]
Thanks for letting us know.
