### ISSUE TITLE
List of suggestions/tweaks

### ISSUE THREAD

**Issue by DiamondWalker** [DivineRPG/DivineRPG#395]
This is a list of suggestions I have for the mod. lmk if I should make these several individual issues.

-rename heart of the sunstorm and heart of the termasect to heart of the eden and heart of the wildwood since the others are called heart of the apalachia and heart of the skythern. In addition it'd probably sound better if there were called eden heart, wildwood heard, etc since it fits more with the other twilight items

-make the twilight boss spawners release particles when the boss is spawning. The closer to spawn the more particles are released, and when the boss spawns there's a cloud of particles

-make the floating log parts floating under termasect rotate so that he has an animation

-make eternal archer's bows be apalachia bows as well as replacing his halite bow drop and give it to some other boss. Also, make him and his health bar purple so it fits

-give angelic armor its arcana consumption back. Alternatively give it a more unique flying mechanic like the valkyrie armor from aether. Unlimited creative flight is op

-undo the gen change for skythern. Seriously, I know its old gen wasn't that great but at least it wasn't generic sky dim levels of boring

-rework/replace awakened halite armor. While I like the idea of an end-game armor that combines several previous armor sets, I don't really like the way it's executed for two reasons:

1- it's just two random armor sets combined and buffed for no real reason. If it's a "final armor set" maybe it should have nerfed effects of all the major armor sets in the mod?

2- its recipe barely counts as an upgrade: once you get halite you just grind a bit more and get the awakened halite set. I was thinking maybe it could include some material unlocked post vethea (maybe per lady luna kill you wake up with one of these items added to your inventory?). Personally I'd make this be the awakened halite set:

recipe: halite armor surrounded by angelic, divine, vemos, and korma sets, with the remaining slots filled with the vethea material mentioned above.

ability: no fall damage + 3x jump height (higher than divine armor) + slow fall (gliding) + health and arcana regen + 16 melee damage

I feel this would make awakened halite more unique as well as being more of an actual upgrade (rather than just an extra grind)

**Comment by NicosaurusRex99** [comment]
hearts is something we will look into,

particles is a maybe but unlikely, will still discuss this,

rotating body parts is doable,

Health bar colors are based on mob color not dimension color but swapping its bows is possible

angelic is weak and we have talked balance we will **NOT** be making angelic consume arcana. this has been debated and we decided to weaken the armor and give it durability instead for a multitude of reasons, one being arcana is from the arcana dimension, not the overworld/nether/iceika, if you use that armor in a boss fight you obviously arent concerned about what armor is most efficient for the job

the dimension generation is sort of WIP

the awakened halite is something that will probably change we just need a good direction to take it

**Comment by AstralScourge** [comment]
> angelic is weak and we have talked balance we will NOT be making angelic consume arcana. this has been debated and we decided to weaken the armor and give it durability instead for a multitude of reasons, one being arcana is from the arcana dimension, not the overworld/nether/iceika, if you use that armor in a boss fight you obviously arent concerned about what armor is most efficient for the job

Just want to comment that I didn't really debate this, just haven't gotten around to anything yet. Also, arcana being only from the arcana dimension (and vethea I guess) is a problem in itself in my opinion.

**Comment by DiamondWalker** [comment]
> 
> particles is a maybe but unlikely, will still discuss this,

Doesnt have to be particles, but it'd be nice if there was some kind of spawn animation. It looks weird just having to block do an invisible countdown before farting out a boss. Now that I think about it this applies to most bosses.
> 
> Health bar colors are based on mob color not dimension color but swapping its bows is possible

I meant changing his body color as well, since rn it looks like he was just taken from wildwood and dumped in apalachia. This also applied when it used to be one of the mortum bosses

> 
> angelic is weak and we have talked balance we will **NOT** be making angelic consume arcana. this has been debated and we decided to weaken the armor and give it durability instead for a multitude of reasons, one being arcana is from the arcana dimension, not the overworld/nether/iceika, if you use that armor in a boss fight you obviously arent concerned about what armor is most efficient for the job

I can see where you're coming from, but infinite creative flight is still **_REALLY_** OP. It pretty much makes you invincible since you can fly over everything, and what you can't fly over can easily be dodged. I'd still add some kind of time limit and/or movement speed punishment.

**Comment by NicosaurusRex99** [comment]
i think we just disagree on how OP flight is.

**Comment by NicosaurusRex99** [comment]
Not specifically rejected, just closing since this isnt an issue its just suggestions. In future i can just search for suggestions via tags if i feel like changes are needed.
