### ISSUE TITLE
Continuous Update Error

### ISSUE THREAD

**Issue by DieDae** [DivineRPG/DivineRPG#396]
[Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.io.FileNotFoundException: https://raw.githubusercontent.com/DivineRPG/DivineRPG/master/Version.txt

Any way to fix this so it stops spamming my log in Divine Journey?

**Comment by AstralScourge** [comment]
What version of DivineRPG is Divine Journey using?

**Comment by DieDae** [comment]
1.4.1.3

**Comment by AstralScourge** [comment]
How often is it spamming?

**Comment by DieDae** [comment]
Every time someone joins.

**Comment by AstralScourge** [comment]
1.7.10 isn't supported anymore. That's just what the update checker in that DRPG version does
