### ISSUE TITLE
Sponge incompatibility

### ISSUE THREAD

**Issue by Bennyboy1695** [DivineRPG/DivineRPG#398]
**DivineRPG version**
1.6.4.1

**Describe the bug**
When the mod is loaded in an environment with Sponge the structures for Iceika and Vethea error with a null pointer exception

**To reproduce**
Put the mod and Sponge in an environment together and let the worlds load

**Expected behavior**
The structures to not error out :P

**Additional context**
The issue was discovered in the celestial journey modpack.

Iceika error: https://gist.github.com/Bennyboy1695/d8648576de02ab5958a01ebcb783c579
Vethea error: https://gist.github.com/Bennyboy1695/f5c3389c1e32b2390cc113216954e13b

**Comment by AstralScourge** [comment]
SpongeForge is not supported. It's difficult to debug crashes caused by it as it rewrites large amounts of vanilla stuff
