### ISSUE TITLE
Shadow Armor Step Assist breaking on Dimension Change

### ISSUE THREAD

**Issue by Shadowsoftime99** [DivineRPG/DivineRPG#400]
**DivineRPG version**
DRPG 1.6.1.4, Minecraft 1.12.2

**Describe the bug**
The title. Basically, if you are wearing Shadow Armor and change your dimension, the speed still works fine but the step assist gimmick doesn't. This is fixed by taking a piece of the armor off and putting back on, to "reset" the set bonus or something.

**To reproduce**
1. Wear full Shadow Armor. Run around, take note of the step assist moving you up 1-block ledges for free.
2. Go to any other dimension (which one isn't important, the act of changing dimensions is the trigger. You can go from elsewhere into the Overworld if you want)
3. Try to use the step assist in the new dimension.

**Expected behavior**
Step assist stays on and keeps doing its thing, without having to take off and put back on a piece of the armor set.

**Comment by velocityraptor-real** [comment]
You will also notice that with other armor buffs

**Comment by NicosaurusRex99** [comment]
Since we are unable to modify 1.12.2 source anymore i am forced to close this issue.
This issue isnt game breaking which is good
