### ISSUE TITLE
No DivineRPG items on server

### ISSUE THREAD

**Issue by ferforious** [DivineRPG/DivineRPG#401]
1) 1.7 (1.12.2)

No DivineRPG items on server. There are 3 pages with modded items,but they are empty, but everithing is fine in singleplayer

**Comment by NicosaurusRex99** [comment]
Sounds like you have only installed the mod on your client rather than both singleplayer and multiplayer

**Comment by NicosaurusRex99** [comment]
Is the issue still present?

**Comment by NicosaurusRex99** [comment]
Likely scenario is you forgot to install the mod server side, if this is not the case please reopen the report
