### ISSUE TITLE
Some suggestions for the mod.

### ISSUE THREAD

**Issue by KittyCat333** [DivineRPG/DivineRPG#407]
## **More configs.**
What I'd think DRPG would benefit from is more configuration.
**Weapon and armor config**
I'd really like to put divinerpg in my personal modpack, but I can't because the weapons/armors of it are way better than any of the mods i have in the modpack. I think a weapon/armor config would be a really good addition.
What I'd like to see in this config : 
Being able to change durability of weapons/armors
* Being able to change damage of weapons
* Being able to change armor/armor toughness of armors.
* Being able to remove the set bonuses of armors.
* Being able to remove the bonuses of weapons.
* Being able to change what ranged weapons require to fire.
* Being able to change the delay time of weapons

**Trade config**
Like, 7 arcanium for a completly useless crop? Seriously?
What I'd like to see in this config :
* Being able to change the input of an trade
* Being able to change the output of an trade
* Maybe being able to add new trades, though that might be difficult to add.
## **Some ideas for vethean weapons**
Right now, there in Vethea there are 3 melee weapons which all do the same thing. I suggest to add some abilities to them to make them different.
**Claws**
Make them give a 33% speed boost and a 25% higher jump when held.
**Hammers**
Make them give a 20% defense boost when held.
**Backswords**
Make them give a 25% strenght boost, but make the player move 12% slower when held.

I'll also suggest to buff cannons and nerf staffs slightly more.
**Cannons**
Increase their damage by 50% and make their projectile inflict poison for 5 seconds. And also make the hunger able to sell 2 acid for 1 yellow pearl to make their ammunition easier to get.
**Staffs**
Decrease their damage by 20%.
## **Boss spawning**
Make the bosses spawn 5 seconds after their spawning item has been used. This would give the players a little bit more preparation time.
## **Some uses to arcana crops**
What i think would be cool is if you could craft saplings of vethean trees in the overworld with arcana crops, for example 4 veilo + 4 lamona + 1 divine tree = a hyrewood sapling.
## **Some arcana tweaks**
* Make the parasecta altar room bigger for there to be space to fight the boss.
* Maybe its my luck that makes them so rare for me to find them, but make npcs rooms slightly more common.
* In Kazari's trades decrease the amount of collectors needed to buy unbreakable versions of the arcana blocks. 
* Make some of the mobs in arcana more unique, because all of the mobs in it currently are generic melee except for living statue, which is just a generic ranged.

Alright, that's the end of my suggestions to the mod.

**Comment by NicosaurusRex99** [comment]
Not specifically rejected, just closing since this isnt an issue its just suggestions. In future i can just search for suggestions via tags if i feel like changes are needed.
