### ISSUE TITLE
Ender Triplet Lag

### ISSUE THREAD

**Issue by WulfTheGod** [DivineRPG/DivineRPG#408]
**DivineRPG version**
1.7.1

**Describe the bug**
Whenever the Ender Triplet attacks you with a fireball, it drops everyone's FPS nearby dramatically.

**Comment by NicosaurusRex99** [comment]
I forgot, did we solve this in your dms?

**Comment by WulfTheGod** [comment]
Yes we did. It was a performance mod conflict. DivineRPG itself works fine.

**Comment by NicosaurusRex99** [comment]
cool cool
