### ISSUE TITLE
Server Wont Boot, (I'm very new to server set ups)

### ISSUE THREAD

**Issue by Forevera7x02** [DivineRPG/DivineRPG#409]
**DivineRPG version**
DivineRPG-1.7.1.jar

********************************** Not sure what any of this stuff means at all

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: divinerpg/objects/items/vethea/ItemMinersAmulet
    at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:89)
    at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:612)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)

**Comment by NicosaurusRex99** [comment]
What are you using to host your server?

**Comment by Forevera7x02** [comment]
> What are you using to host your server?

Scalacube, i just used this version (DivineRPG-1.12.2-1.5.2.jar) and it works perfectly fine im in server right now and its running

**Comment by NicosaurusRex99** [comment]
I mean like, forge, sponge, cauldron, catserver or others

**Comment by Forevera7x02** [comment]
I'm pretty sure I'm using Technic Launcher, if that's what you mean

**Comment by NicosaurusRex99** [comment]
Not that, could you send a log txt file?

**Comment by Forevera7x02** [comment]
I'm not exactly sure what a log txt file is, I'm very new to this and don't have much expiernce. I'm launching it through Tekxit-3 modpack off of technic

**Comment by NicosaurusRex99** [comment]
https://docs.mjrlegends.com/General%20Minecraft/crash-log/

Follow the Technic launcher guide

**Comment by Forevera7x02** [comment]
And my server host is ScalaCube is where I bought the ability to run the server

**Comment by Forevera7x02** [comment]
This? I don't think this is the right log, I can get a log copy showing all of it, or I can try of the correct log. But this is the crash log from the actual folder pretty sure it isn't mine tho.
https://pastebin.com/5SDkwN9E

**Comment by Forevera7x02** [comment]
I just download the crash file from Scalacube ill try and send that one im pretty sure this one the right one

**Comment by NicosaurusRex99** [comment]
That was the crash report. youre in the crash-reports folder. i need you to back out one layer enter the logs folder and send latest.txt

**Comment by Forevera7x02** [comment]
https://pastebin.com/hgJ8XQQP

**Comment by Forevera7x02** [comment]
that was the one from my server, and ok

**Comment by Forevera7x02** [comment]
I'm pretty sure that one is the (latest crash) I didn't have anything in my crash folder, I had to download that from ScalaCube because that shows what stopped my server from starting/crashing.

**Comment by NicosaurusRex99** [comment]
```Open the Launcher
Select the modpack and click on the small gearwheel below the modpack on the right site

Right click & select Open folder

Locate/Enter the logs folder.

Find file called latest.txt or debug.txt

Visit Pastebin.com & and paste the crash log contents and press Create New Paste at the bottom

Link the url link to anyone who wants to see the crash log```

**Comment by Forevera7x02** [comment]
It says I exceeded the maximum paste size

**Comment by NicosaurusRex99** [comment]
https://gist.github.com/
try this

**Comment by Forevera7x02** [comment]
There we go. https://gist.github.com/Forevera7x02/4223d2345cbd46a58a547e94412d67f3

**Comment by NicosaurusRex99** [comment]
```
[00:55:36] [Client thread/INFO]: [divinerpg.utils.attributes.ReflectionHelper:find:127]: java.lang.NoSuchFieldException: maximumValue
``` This makes me believe the config value for one of the mobs was set above 4096. thats an unrelated thing. Next this log youve sent doenst seem to have the issue


for now i just recommend using the version that did work for you while i figure out this issue

**Comment by Forevera7x02** [comment]
I have a friend that uses the version I tried to use on his server and it works for him. He's ALLOT better at this stuff than me, thanks for the help man 👍

**Comment by NicosaurusRex99** [comment]
closed because inactivity
