### ISSUE TITLE
Incorrect description of armor protection

### ISSUE THREAD

**Issue by shulitski** [DivineRPG/DivineRPG#413]
Arlemite armor is described as "85% Ranged Damage Protection" (ArmorRegistry.java). But it has a 0.2F multiplier (ArmorDescriptionRegistry.java). So the protection is 80%. 

Other armors have the same issues.

**Comment by NicosaurusRex99** [comment]
Since we are unable to modify 1.12.2 source anymore i am forced to close this issue.
i will take this into account for 1.16
