### ISSUE TITLE
Vemos armor unobtainable?

### ISSUE THREAD

**Issue by Terra-B-Welch** [DivineRPG/DivineRPG#418]
Not sure if Captain Merik or Datticon are supposed to sell it but neither are, Merik sells the korma set, but vemos is MIA from traders.

**Comment by shulitski** [comment]
The Vemos armor is sold by the War General.

**Comment by Terra-B-Welch** [comment]
war general? You mean captain merik? I just said I could not find the armor in his trade screen.

**Comment by NicosaurusRex99** [comment]
War general is a separate mob.
