### ISSUE TITLE
[Suggestion] Config for weapon stats?

### ISSUE THREAD

**Issue by Terra-B-Welch** [DivineRPG/DivineRPG#419]
We have a config for mob stats, why not one for weapon stats? Just a thought.

**Comment by NicosaurusRex99** [comment]
We have thought about it and decided against it

**Comment by Terra-B-Welch** [comment]
Guess I'll stop suggesting anything then if it'll just get denied.

I guess materialchanger will do your job for you -_-

and bows can be b e h i n d
