### ISSUE TITLE
No recipes for rupee tools

### ISSUE THREAD

**Issue by krwminer** [DivineRPG/DivineRPG#42]
No recipes for the rupee pickaxe, axe, shovel an hoe.

**Comment by ShadowOfStrelok** [comment]
i downloalded fix in my quickfix(rupee shickaxe crafting with arlemite instruments). and one more bug - divine shickaxe hasn't unlimited uses.

**Comment by ShadowOfStrelok** [comment]
but it need, because divine shickaxe crafting so hard.

**Comment by Eternaldoom** [comment]
I gave the divine shickaxe infinite uses a while ago. you might not have the latest src

**Comment by ShadowOfStrelok** [comment]
yes, i havent. its my fail
