### ISSUE TITLE
TileEntity missing a mapping

### ISSUE THREAD

**Issue by NikitaShokin** [DivineRPG/DivineRPG#422]
**DivineRPG version**
[1.4.7][V1.3.0.4][SMP]

**Describe the bug**
Server can't save the world cause class xolova.blued00r.divinerpg.entities.tileentities.TileEntityCoalStoneFurnace is missing a mapping

**Comment by NicosaurusRex99** [comment]
1.4.7 isnt supported anymore

**Comment by NikitaShokin** [comment]
Do you have it's sources?

**Comment by NicosaurusRex99** [comment]
If the branch isnt on this repo it is not available

**Comment by NikitaShokin** [comment]
I've fixed that.
Link to fixed mod: https://drive.google.com/file/d/1aaAHlXo51zTz5mrhESrJJR2lCTyJj33R/view?usp=sharing
You can upload it to curseforge I'm not against
