### ISSUE TITLE
Legacy mod fix

### ISSUE THREAD

**Issue by NikitaShokin** [DivineRPG/DivineRPG#423]
#422 fix
Link to fixed mod: https://github.com/NikitaShokin/Minecraft-by-Red-Lion/blob/master/mods/%5B1.4.7%5D%5BV1.3.0.4%5D%5BSMP%5DDivineRPG%20tileentity%20map%20fixed.jar?raw=true
You can upload it to curseforge I'm not against

**Comment by NicosaurusRex99** [comment]
Interested in your thoughts tslat

**Comment by NikitaShokin** [comment]
Excuse me, what does "tslat" means?
(I'm not native english speaker)

**Comment by NicosaurusRex99** [comment]
thats a person

**Comment by Tslat** [comment]
Yeah we don't support 1.4.7 anymore.
If we start to upload more versions like this then effectively we're supporting it, and that's a slippery slope.
