### ISSUE TITLE
Entities hitbox and rendering dissapearing when entering new dimension.

### ISSUE THREAD

**Issue by HurrycaneTheTiger** [DivineRPG/DivineRPG#424]
Whenever I come through a divine portal entities will disappear. The hitboxes and renderings will disappear but the entities can still interact with the environment and other entities. They also still produce sounds as well. F3+A doesn't fix it, F3+T fixes it occasionally as well as re-logging. Entering into a non-divine portal (such as nether, twilight forest, or aether) will load the entities back.

Infernal mobs also still apply the visual sparkles on infernal-affected mobs.

**Comment by NicosaurusRex99** [comment]
You probably have optifine installed. Optifine is known to do that to most entities

**Comment by HurrycaneTheTiger** [comment]
Is there a way to fix it within the mod? Or would that be an optifine issue to adress.

**Comment by NicosaurusRex99** [comment]
It's an optifine issue
