### ISSUE TITLE
Divine RPG Ticking entity crash

### ISSUE THREAD

**Issue by Handcrafted123** [DivineRPG/DivineRPG#426]
Hi guys,

So my issue is whenever I shoot a bow or an entity shoots a bow the arrow will not hit another entity, bounce off, and as soon as the arrow lands the game crashes. Does anyone have any fixes or know what is going on with it? 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  weaponlib (mw-1.11.7.7_mc1.12.2 .jar)
  TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  XaeroMinimapPlugin (Xaeros_Minimap_21.2.0_Forge_1.12.jar)
  OTGCorePlugin (OTG-Core.jar)
  XaeroWorldMapPlugin (XaerosWorldMap_1.11.10_Forge_1.12.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 3/31/21 2:03 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.gildedgames.the_aether.AetherEventHandler.onProjectileImpact(AetherEventHandler.java:318)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_336_AetherEventHandler_onProjectileImpact_ProjectileImpactEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.onProjectileImpact(ForgeEventFactory.java:745)
	at divinerpg.objects.entities.entity.projectiles.EntityDivineArrow.func_70071_h_(EntityDivineArrow.java:223)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.gildedgames.the_aether.AetherEventHandler.onProjectileImpact(AetherEventHandler.java:318)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_336_AetherEventHandler_onProjectileImpact_ProjectileImpactEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.onProjectileImpact(ForgeEventFactory.java:745)
	at divinerpg.objects.entities.entity.projectiles.EntityDivineArrow.func_70071_h_(EntityDivineArrow.java:223)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: divinerpg:arrow_shot (divinerpg.objects.entities.entity.projectiles.EntityDivineArrow)
	Entity ID: 1133
	Entity Name: entity.divinerpg.arrow_shot.name
	Entity's Exact location: 231.84, 69.75, 235.76
	Entity's Block location: World: (231,69,235), Chunk: (at 7,4,11 in 14,14; contains blocks 224,0,224 to 239,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 1.15, -0.88, 2.59
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['Handcrafted_'/965, l='New World', x=229.50, y=69.87, z=230.50]]
	Chunk stats: ServerChunkCache: 321 Drop: 0
	Level seed: 6224474803308415881
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (228,64,232), Chunk: (at 4,4,8 in 14,14; contains blocks 224,0,224 to 239,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 851 game time, 851 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 28169 (now: false), thunder time: 144752 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.14.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2610732648 bytes (2489 MB) / 4563402752 bytes (4352 MB) up to 5368709120 bytes (5120 MB)
	JVM Flags: 7 total; -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 20, tallocated: 86
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_G5 33 mods loaded, 33 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version       | Source                                        | Signature                                |
	|:------ |:-------------------- |:------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft            | 1.12.2        | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                  | 9.42          | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                  | 8.0.99.99     | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                | 14.23.5.2854  | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | otgcore              | 1.12.2-v9.3   | minecraft.jar                                 | None                                     |
	| LCHIJA | xaerominimap_core    | 1.12.2-1.0    | minecraft.jar                                 | None                                     |
	| LCHIJA | xaeroworldmap_core   | 1.12.2-1.0    | minecraft.jar                                 | None                                     |
	| LCHIJA | aether_legacy        | 1.5.0         | aether-1.12.2-v1.5.0.jar                      | None                                     |
	| LCHIJA | bearwithme           | 1.12.2-1.3.1  | bearwithme-1.12.2-1.3.1.jar                   | None                                     |
	| LCHIJA | bettercaves          | 1.12.2        | bettercaves-1.12.2-1.5.0.jar                  | None                                     |
	| LCHIJA | betternether         | 0.1.5         | betternether-0.1.5-1.12.2.jar                 | None                                     |
	| LCHIJA | openterraingenerator | v9.3          | OpenTerrainGenerator-1.12.2-v9.3.jar          | None                                     |
	| LCHIJA | biomebundle          | 5.1           | Biome_Bundle-1.12.2-v6.1.jar                  | None                                     |
	| LCHIJA | codechickenlib       | 3.2.3.358     | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | divinerpg            | 1.12.2-1.6    | DivineRPG-1.12.2-1.6.jar                      | None                                     |
	| LCHIJA | orelib               | 3.6.0.1       | OreLib-1.12.2-3.6.0.1.jar                     | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | dsurround            | 3.6.1.0       | DynamicSurroundings-1.12.2-3.6.1.0.jar        | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | engineersdecor       | 1.1.2         | engineersdecor-1.12.2-1.1.2.jar               | ed58ed655893ced6280650866985abcae2bf7559 |
	| LCHIJA | familiarfauna        | 1.0.11        | Familiar-Fauna-Mod-1.12.2.jar                 | None                                     |
	| LCHIJA | cfm                  | 6.3.1         | furniture-6.3.1-1.12.2.jar                    | None                                     |
	| LCHIJA | ic2                  | 2.8.221-ex112 | industrialcraft-2-2.8.221-ex112.jar           | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | jei                  | 4.16.1.301    | jei_1.12.2-4.16.1.301.jar                     | None                                     |
	| LCHIJA | libraryex            | 1.2.1         | LibraryEx-1.12.2-1.2.1.jar                    | None                                     |
	| LCHIJA | lost_aether          | 1.0.2         | lost-aether-content-1.12.2-1.0.2.jar          | None                                     |
	| LCHIJA | moremobss            | 1.0.0         | More+Mobs+1.12.2.jar                          | None                                     |
	| LCHIJA | mw                   | 1.11.7.7      | mw-1.11.7.7_mc1.12.2 .jar                     | None                                     |
	| LCHIJA | netherex             | 2.2.4         | NetherEx-1.12.2-2.2.4.jar                     | None                                     |
	| LCHIJA | nei                  | 2.4.3         | NotEnoughItems-1.12.2-2.4.3.245-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | soundfilters         | 0.12_for_1.12 | SoundFilters-0.12_for_1.12.jar                | None                                     |
	| LCHIJA | srparasites          | 1.8.2         | SRParasites-1.12.2v1.8.2.jar                  | None                                     |
	| LCHIJA | treechopper          | 1.2.4         | TreeChopper-1.12.2-1.2.4.jar                  | None                                     |
	| LCHIJA | xaerominimap         | 21.2.0        | Xaeros_Minimap_21.2.0_Forge_1.12.jar          | None                                     |
	| LCHIJA | xaeroworldmap        | 1.11.10       | XaerosWorldMap_1.11.10_Forge_1.12.jar         | None                                     |

	Loaded coremods (and transformers): 
weaponlib (mw-1.11.7.7_mc1.12.2 .jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  
XaeroMinimapPlugin (Xaeros_Minimap_21.2.0_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
  xaero.common.core.transformer.EntityPlayerTransformer
  xaero.common.core.transformer.AbstractClientPlayerTransformer
  xaero.common.core.transformer.WorldClientTransformer
  xaero.common.core.transformer.EntityPlayerSPTransformer
  xaero.common.core.transformer.PlayerListTransformer
  xaero.common.core.transformer.GuiIngameForgeTransformer
OTGCorePlugin (OTG-Core.jar)
  com.pg85.otg.forge.asm.excluded.OTGClassTransformer
XaeroWorldMapPlugin (XaerosWorldMap_1.11.10_Forge_1.12.jar)
  xaero.map.core.transformer.ChunkTransformer
  xaero.map.core.transformer.NetHandlerPlayClientTransformer
  xaero.map.core.transformer.EntityPlayerTransformer
  xaero.map.core.transformer.AbstractClientPlayerTransformer
  xaero.map.core.transformer.WorldClientTransformer
  xaero.map.core.transformer.PlayerListTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Handcrafted_'/965, l='New World', x=229.50, y=69.87, z=230.50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 INTEL-12.10.25
	OpenGlRenderer: Intel(R) Iris(TM) Plus Graphics 640
	OpenGlVendor: Intel Inc.
	CpuCount: 4

**Comment by NicosaurusRex99** [comment]
This is an aether bug we can't fix
