### ISSUE TITLE
Can not go back through portals on severs 

### ISSUE THREAD

**Issue by rayanfox25** [DivineRPG/DivineRPG#429]
Divine RPG 1.7.1
This is the version number on the mod file and is also viewable in-game. "Latest" or the Minecraft version are not acceptable answers.

**Describe the bug**
The bug I decoverd is you can not go back through portals once you enter a divine RPG dimension. It makes the sound like you whent through the portal but it doesn't teleport you . This seems to only happen on servers

**To reproduce**
You go through the portal on a server any divine RPG portal but you cannot go back through to the overworld

**Expected behavior**
You enter the portal but when you want to go back you go back to the overworld

**Screenshots**

**Additional context**
It seems to only happen on severs I'm using a magma based server which is using forge and bucket yeah

**Comment by NicosaurusRex99** [comment]
This issue happened when aether miss was installed. It's an aether issue

**Comment by rayanfox25** [comment]
Oh
