### ISSUE TITLE
Block disappears when placing on a door

### ISSUE THREAD

**Issue by Sargeanthost** [DivineRPG/DivineRPG#435]
**DivineRPG version**
1.7.1

**Describe the bug**
I right clicked a piece of dirt on a soul door and it made the placing sound and animation but it disappeared

**To reproduce**
See above

**Expected behavior**
Opens the door.

**Additional context**
It was a soul door in the war generals room

**Comment by NicosaurusRex99** [comment]
1. we arent working on 1.12.2 anymore
2. why did you close the issue? did you find the cause/solve the issue?

**Comment by Sargeanthost** [comment]
>  we arent working on 1.12.2 anymore, why did you close the issue? did you find the cause/solve the issue?

That's the reason 😅
