### ISSUE TITLE
Ticking entity crash

### ISSUE THREAD

**Issue by DeepStare2401** [DivineRPG/DivineRPG#438]
**DivineRPG version**
1.7.1

**Describe the bug**
When entering the Eden dimension, mobs from the Eden causes the server to crash

**To reproduce**
>Create portal
>Enter Eden
>Mobs start spawning
>Ticking entity crashes the server

**Expected behavior**
I excpected to, obviously, not crash the server at any point

**Screenshots**
Not a screenshot but i'll post the crash report here

[crash-2021-08-02_14.03.57-server.txt](https://github.com/DivineRPG/DivineRPG/files/6918856/crash-2021-08-02_14.03.57-server.txt)

**Additional context**
After succesfully deleting every cadillion cow with a command, anoother entity from the eden starts crashing the server again

**Comment by NicosaurusRex99** [comment]
This is a corail tombstone issue. Try a different grave mod

**Comment by DeepStare2401** [comment]
I'll try it out rn, I'll keep you updated

**Comment by DeepStare2401** [comment]
Everything works fine now! Thanks!
