### ISSUE TITLE
eden bugs

### ISSUE THREAD

**Issue by Pietonn** [DivineRPG/DivineRPG#439]
**DivineRPG version**
This is the version number on the mod file and is also viewable in-game. "Latest" or the Minecraft version are not acceptable answers.

**Describe the bug**

**To reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by NicosaurusRex99** [comment]
Very legit. Definitely can't fix

**Comment by Pietonn** [comment]
oh yall cant fix it?

**Comment by Tslat** [comment]
can't fix what

**Comment by Pietonn** [comment]
oh i see the problem I was editing the post and I thought yall could see what I was typing mb, I was just making a post about how there is some buggy things in the Eden like how not enough Eden ores spawns, to many mobs spawn, structures from other mods will spawn in the Eden, and the sun warrior has zombie sound affects just some stuff I noticed in the Eden

**Comment by NicosaurusRex99** [comment]
We can't tweak 1.12.2 or lower anyways

**Comment by Pietonn** [comment]
oh are you not working on that version anymore?

**Comment by NicosaurusRex99** [comment]
We physically cant

**Comment by Pietonn** [comment]
lmao what happened that you cant?

**Comment by NicosaurusRex99** [comment]
Forge doesn't support those versions anymore

**Comment by Tslat** [comment]
Ehhh forge does

It's just a pain to work with cus we need to change a bunch of toolchain stuff that really just isn't worth our time.

**Comment by NicosaurusRex99** [comment]
oof
