### ISSUE TITLE
[1.7.10]Ammo type tooltip and Efficiency tooltip appear incorrectly

### ISSUE THREAD

**Issue by ianlavr** [DivineRPG/DivineRPG#440]
**DivineRPG version**
[1.7.10][SMP]DivineRPG-1.4.1.5.jar

**Describe the bug**
Ammo type tooltip and Efficiency tooltip appear incorrectly

**To reproduce**
Steps to reproduce the behavior.

**Expected behavior**
Tooltips should appear normaly

**Screenshots**
![2021-09-08_15 55 58](https://user-images.githubusercontent.com/75268772/132523038-c695778b-2ab7-4427-8b5c-918039155531.png)
![2021-09-08_15 56 00](https://user-images.githubusercontent.com/75268772/132523084-8cf2601e-27b8-4428-8c63-202fca5b8cf2.png)

**Comment by NicosaurusRex99** [comment]
Unfortunately we won't/can't fix 1.7.10 anymore. It's playable which is the best we are going to offer

**Comment by ianlavr** [comment]
oh ok
