### ISSUE TITLE
Mysterious Clock, Call of the Watcher and Horde Horn don't get used up when using them from your off-hand

### ISSUE THREAD

**Issue by Atricos** [DivineRPG/DivineRPG#442]
**DivineRPG version**
1.7.1

**Describe the bug**
When using the Mysterious Clock, the Call of the Watcher or the Horde Horn in your off-hand, it doesn't use up the item, instead it deletes the item held in your main hand. (Or if nothing's held in your main hand, it simply lets you use the summoning item infinitely many times.)

**To reproduce**
1. Go into a world.
2. Get a Mysterious Clock.
3. Go into Survival mode.
4. Press "F" to put the Mysterious Clock in your off-hand.
5. Put something in your main hand (that doesn't have a right click functionality).
6. Right click the ground.

**Expected behavior**
The Mysterious Clock (/Call of the Watcher/Horde Horn) gets used up instead of your main hand item.

**Comment by Atricos** [comment]
1.7.1 is the newest 1.12.2 version on CurseForge: https://www.curseforge.com/minecraft/mc-mods/official-divinerpg/files
Are there are newer versions? Or why did I get the "old version" tag?

**Comment by NicosaurusRex99** [comment]
i am only working on 1.16 now since i cant modify 1.12 or lower anymore

**Comment by Atricos** [comment]
Can't modify? Why? :O

**Comment by NicosaurusRex99** [comment]
basically some stuff at forge changed and now I cant do much to change anything
