### ISSUE TITLE
Broken sharks and whales in new divine rpg ver. 1.7.1

### ISSUE THREAD

**Issue by KnifeWaifu** [DivineRPG/DivineRPG#444]
In the new mod version "1.7.1" the mobs "whale" and "shark" were broken, because of the update they now have only 10 health and they are completely harmless, although they still drop a drop. This error very badly breaks the balance.
![2021-10-12_15 04 05](https://user-images.githubusercontent.com/91790893/136953325-6f9eb999-f6f4-4805-917a-dabb4dafcd04.png)
![2021-10-12_15 04 12](https://user-images.githubusercontent.com/91790893/136953330-b0981da8-3aa2-4721-b0c3-4ba7a5a5cc97.png)

**Comment by NicosaurusRex99** [comment]
This is a known issue, but we cant modify 1.12.2 anymore and are focusing 100% on 1.16+

**Comment by KnifeWaifu** [comment]
Okie, thanks
