### ISSUE TITLE
1.16.5 Crash List

### ISSUE THREAD

**Issue by BigBillsHell** [DivineRPG/DivineRPG#450]
**DivineRPG version**

1.16.5

**Describe the bug**

1. Sorcerers in Mortum firing at creative players
2. Rainbour's having particle effects within a certain distance
3. Sorcerer's missing projectile textures when firing
4. the trees in Iceika are all the same tree ( unknown if it is intentional or not )
5. Mystic entities in Skythern firing at creative players, as well as missing projectile textures
6. Lorga Missing Textures and flying above while continuously being depleted health 
7. Temple Guardian crashes game upon spawn when using optifine 
8. Golem of Rejuvenation ticking entity crash upon attacking an entity
9. Saguaro Worm firing at creative players
10. Ayeraco entities aggressive at creative players
11. Sunstorm Ticking Entity Crash when hit / being aggressive with creative mode players
12. Sunstorm missing projectile textures
13. Termasect firing at creative mode players
14. Twilight Demon Machine Gun projectile crash
15.  Iceika having music even when the music is option is turned off.

**To reproduce**

1. Summon or go to the dimension where the entity resides, and get within aggro range.
2. Summon or go to the dimension where the entity resides, at a certain distance the particles will be seen.
3. Summon or go to the dimension where the entity resides, and get within aggro range. 
4. Go to the dimension, and observe the world gen.
5. Summon or go to the dimension where the entity resides, and get within aggro range.
6. Summon or encounter the entity.
7. Have Optifine installed, and encounter or summon the entity.
8. Get the Entity as a pet and attack an entity.
9. Summon or encounter the entity.
10. Summon or encounter the entity, does not need to be hit in order for it to become aggressive.
11. Summon the entity in creative mode, does not matter if you hit the entity or not when your creative as it will result in a crash regardless.
12.  Summon/Encounter the entity and observe.
13. Summon/Encounter the entity and observe.
14. Summon/Encounter the entity and observe, rare chances are when it starts firing you will have a few seconds before it crashes.
( also no smoke particles when firing, unknown if this is intentional or not. )

**Expected behavior**

1. Sorcerer's staying passive against creative mode players.
2. Rainbour's to have no rainbow particles when being within a certain range.
3. Sorcerer's having projectile textures upon firing.
4. Trees being there 1.12.2 and 1.7.10 counterpart where they are alot more thicker in terms of foliage, ( also daytime in Iceika? I thought it was usually nighttime there with the dark skybox? )
5. Mystic's staying passive against creative mode players and having projectile textures upon firing.
6. Having the Lorga having it's normal behavior like in 1.7.10 and 1.12.2.
7. Having the Temple Guardian not crash the game.
8. Having the Golem of Rejuvenation kill the entity and not crash the game.
9. Having the Saguaro worm not be aggressive against creative mode players.
10. Having the Ayeraco ( all variants ) not be aggressive against creative mode players.
11. Having the Sunstorm not crash the game.
12.  Sunstorm's having projectile textures upon firing.
13.  Having the Termasect not be aggressive against creative mode players.
14. Twilight Demon's projectiles not crashing the game as well as having smoke prior to older versions when firing.
15. Iceika not having music when the music option is turned off. 

**Screenshots**

Issue 4. 
![2021-12-25_19 20 42](https://user-images.githubusercontent.com/93220380/147383969-ee63f5dd-3d98-45ed-b241-f5f5a8b8f3d3.png)

Issue 14.
![Twilight Machine Gun](https://user-images.githubusercontent.com/93220380/147384085-f15d0659-af8f-4510-8940-7826c38835df.png)

**Additional context**

Issue 11: https://pastebin.com/2vwYXPYh

Issue 7: https://pastebin.com/eEDEJeis

Issue 14: https://pastebin.com/Eh5c1Zs5

Issue 8: https://pastebin.com/NBN2Y84n

**Comment by NicosaurusRex99** [comment]
Thank you for these

**Comment by NicosaurusRex99** [comment]
does the temple guardian issue occur without optifine?

**Comment by BigBillsHell** [comment]
yes unfortunately.

Temple Guardian Without Optifine issue: https://pastebin.com/B43UMi8K

**Comment by NicosaurusRex99** [comment]
figured out that issue and resolved it, going to fix more issues before posting that fix

**Comment by NicosaurusRex99** [comment]
ok so trees were a known thing, same issue in mortum, was a compromise we made to have a release this year. however there are new ones planned. that said, fixed 92f1bed
