### ISSUE TITLE
Lots of Pigs spawning in superflat worldtype [ 1.16.5 ]

### ISSUE THREAD

**Issue by BigBillsHell** [DivineRPG/DivineRPG#452]
**DivineRPG version**
1.16.5 Forge

**Describe the bug**
For some reason when you spawn in a superflat world, pigs just spawn **everywhere.**

**To reproduce**
go make a new world, with superflat as the worldtype, and observe.

**Expected behavior**
pigs only spawning in villages in the overworld, not everywhere

**Screenshots**

![2021-12-25_23 20 41](https://user-images.githubusercontent.com/93220380/147388273-cb479181-8bfd-4594-a578-201a19bcdb56.png)

**Additional context**
only mods installed are JEI, Torohealth, Optifine, and Better Configs.

**Comment by NicosaurusRex99** [comment]
I dont add pig spawns. kinda odd
