### ISSUE TITLE
Lady Luna not changing colors when fighting against [ 1.16.5]

### ISSUE THREAD

**Issue by BigBillsHell** [DivineRPG/DivineRPG#453]
**DivineRPG version**

1.16.5 Forge

**Describe the bug**
Unknown if it's not yet implemented or a bug, but when fighting Lady Luna, the usual color change does not happen and the boss
is just staying with one color.

**To reproduce**
Encounter or Summon then attack Lady Luna until the boss has changed phases

**Expected behavior**
To change the colors depending on what kind of damage you can deal to the boss

**Screenshots**
N/A

**Additional context**
N/A

**Comment by NicosaurusRex99** [comment]
This is a bug, thanks for the report
