### ISSUE TITLE
Vethea Portal Dupe Bug [1.16.5]

### ISSUE THREAD

**Issue by BigBillsHell** [DivineRPG/DivineRPG#454]
**DivineRPG version**
1.16.5 Forge

**Describe the bug**
When using the Nightmare Bed to transport to Vethea, it seems that each time you go back and in, the Portal is being made again, overlapping or being next to each other in Vethea.

**To reproduce**
Create a new world, make a nightmare bed, right click and go to vethea, once that happens, go into the portal and go back to vethea again via right clicking the bed.

**Expected behavior**
no dupe Portal spawn since it's in the same coordinates.

**Screenshots**

![image](https://user-images.githubusercontent.com/93220380/147388845-1be298e7-f389-414f-9ee1-134a667bc389.png)

**Additional context**
N/A

**Comment by Locomenmod** [comment]
Fixed in 2be2b8a7665a6bb3669df8d68a02f0f85598ac00
