### ISSUE TITLE
Ranged Weapon Issues [ 1.16.5 ]

### ISSUE THREAD

**Issue by BigBillsHell** [DivineRPG/DivineRPG#456]
**DivineRPG version**
Forge 1.16.5

**Describe the bug**

Ranged Weapon Issues:

- Firefly does not inflict damage when firing
projectiles and the projectiles do not home towards targets.

- General's Staff does not inflict damage
when firing projectiles and the projectiles
do not split into 5.

- Grenade Texture Bug: instead of a grenade
it's a snowball.

- Meriks Missile cannot fire projectiles.

- Meteor Mash's right click does not work.

- Serenade of Death's right click feature does not work.

- Serenade Striker's right click feature does not work, a flash occurs but no lightning strike.

- Staff of Starlight's right click feature does not work.

- Starlight's right click feature does not work.

- Bluefire Bow's Projectiles do not explode.

- Halite Bow does not charge faster.

- Hunter Bow does not poison entities shot.

- Icicle Bow does not charge faster.

- Inferno Bow does not ignite enemies.

- Shadow Bow does not charge faster.

- Skythern Bow does not charge faster.

- Twilight Bow does not charge faster.

- Wildwood Bow does not charge faster.

- Golden Fury is missing projectile textures.

- The bows all have the same damage ( excluding the Snowstorm Bow )

**To reproduce**
- Obtain the Weapons and use them.

**Expected behavior**

- For them to work normally.

**Screenshots**

Golden Fury Issue:
![image](https://user-images.githubusercontent.com/93220380/147403364-330cd5f2-6922-462d-a1ec-d543eabc37ff.png)

**Additional context**

N/A

**Comment by NicosaurusRex99** [comment]
List of stuff fixed: 
b328d34
6dd96c8
4f3cf16
d3611ed
b576c51
b1c2201


Firefly is the only fix left before i can close this
