### ISSUE TITLE
Armours have low durablity

### ISSUE THREAD

**Issue by Nifleer** [DivineRPG/DivineRPG#458]
**DivineRPG version**
This is the version number on the mod file and is also viewable in-game. "Latest" or the Minecraft version are not acceptable answers. Unfortunatley we cannot change versions below 1.16.5, feel free to leave a report but there is nothing we can do

**Describe the bug**
The armours are after like 10-20 hits already destroyed

**To reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Ringedtech203** [comment]
nice use of the template

**Comment by Nifleer** [comment]
@Ringedtech203 sorry it was my first time using this thing but I updatet it.

**Comment by NicosaurusRex99** [comment]
not a bug, this is intentional since the stuff is OP
