### ISSUE TITLE
Not infinite armor [ 1.16.5 ]

### ISSUE THREAD

**Issue by sanitarvdypke** [DivineRPG/DivineRPG#463]
**DivineRPG version**
This is the version number on the mod file and is also viewable in-game. "Latest" or the Minecraft version are not acceptable answers. Unfortunatley we cannot change versions below 1.16.5, feel free to leave a report but there is nothing we can do

**Describe the bug**

**To reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sanitarvdypke** [comment]
All armor, which is supposed to have infinite durability, has very little durability.
![screenshot 30-12-2021 004923](https://user-images.githubusercontent.com/70753332/147706934-e07a34cb-3cad-410e-ade4-817557645d49.png)

**Comment by Ringedtech203** [comment]
The durability amounts have already been fixed in dev

**Comment by Ringedtech203** [comment]
And I don't believe any armor has infinite durability anymore

**Comment by NicosaurusRex99** [comment]
already patched in dd1710e
