### ISSUE TITLE
Minecraft Crashes

### ISSUE THREAD

**Issue by Kailash8460** [DivineRPG/DivineRPG#465]
**DivineRPG version**
This is the version number of the mod file: 1.8.2

**The bug**
Hello, I found a bug in the divine RPG, when the mob (Wild Fire Archer, White Grizzle, etc) spawns, minecraft crashes. Checked without extra mods. Please fix it.

**Comment by NicosaurusRex99** [comment]
This is already fixed, the grizzle bug is fixed in 1.8.3 so you can get rid of that bug but the wildfire bug is fixed in 1.8.4 which is almost ready to release
