### ISSUE TITLE
DivineRPG 1.16.5 issue

### ISSUE THREAD

**Issue by ROBIN9Z** [DivineRPG/DivineRPG#469]
**DivineRPG version**

game version 1.16.5
mod version 1.8.6

**Describe the bug**
world destroyer enchantment not working
but it mining in torches 3x3 zone 
not blocks
**To reproduce**
mining 3x3

**Expected behavior**
3x3 mining

**Screenshots**
none

**Additional context**
none

**Comment by NicosaurusRex99** [comment]
Fixed in [7280591](https://github.com/DivineRPG/DivineRPG/commit/7280591d405cf04a6a61180f94998e3e62602dd9)
