### ISSUE TITLE
Flight bug

### ISSUE THREAD

**Issue by ROBIN9Z** [DivineRPG/DivineRPG#470]
**DivineRPG version**
game version1.16.5
mod verion 1.6.8
**Describe the bug**
If at first to wear the armor of an angel, fly and then change the armor set or u gonna be just without armor 
u still can fly
fixing when u rejoining 

**To reproduce**
I've put on my armor, I've flown, I've taken it off, but I can still fly

**Expected behavior**
no fly without armor

**Screenshots**
none

**Additional context**
none

**Comment by NicosaurusRex99** [comment]
Would you be able to test if this fixes your issue
https://www.dropbox.com/s/mjk8l2kgcczhy3z/DivineRPG-1.8.7.jar?dl=0
also version 1.6.7 isnt even out.. let alone 1.6.8

**Comment by ROBIN9Z** [comment]
Everything works as intended, thank you!

вт, 8 мар. 2022 г. в 10:51, Naturix ***@***.***>:

**Comment by ROBIN9Z** [comment]
now it works
and fix working great
 ty

**Comment by NicosaurusRex99** [comment]
Would you be able to test this revision of that
https://www.dropbox.com/s/nzo98e3wzfwkpvx/DivineRPG-1.8.7.jar?dl=0

**Comment by ROBIN9Z** [comment]
> Would you be able to test this revision of that https://www.dropbox.com/s/nzo98e3wzfwkpvx/DivineRPG-1.8.7.jar?dl=0

amazing !

**Comment by NicosaurusRex99** [comment]
This was actually fixed in f8e923f

**Comment by KiriniriK** [comment]
Hello. It seems to disable flying in creative mode now. Why did `!entity.isCreative() && !entity.isSpectator()` get deleted?
