### ISSUE TITLE
Проблемы в дивайн рпг: Если взять в левую руку мистические часы, то можно бесконечно призывать древнюю сущность (коричневый кузнечик)

### ISSUE THREAD

**Issue by amused92octopus** [DivineRPG/DivineRPG#471]
**DivineRPG version**
This is the version number on the mod file and is also viewable in-game. "Latest" or the Minecraft version are not acceptable answers. Unfortunatley we cannot change versions below 1.16.5, feel free to leave a report but there is nothing we can do

**Describe the bug**

**To reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Locomenmod** [comment]
Empty issue
