### ISSUE TITLE
Проблемы в дивайн рпг:

### ISSUE THREAD

**Issue by amused92octopus** [DivineRPG/DivineRPG#472]
Проблемы в дивайн рпг: 1 Если взять в левую руку мистические часы, то можно бесконечно призывать древнюю сущность (коричневый кузнечик). Также проблема с этим и другими боссами - они не нападают на игрока, бьют только если подойти, застревают и странно себя ведут. 2 Бос солнца в мире эден может призваться только один раз, после чего в любых алтарях он не  может призваться, но драгоценные куски эдена при этом тратятся. 3 не спавнятся руды в мире эден. 4 в аду не появляются монстры из дивайн рпг. 5.морские монстры нейтральны к игроку, нападает только синий крокодил. 6 Убогие текстуры ( исключения: текстуры и обновлённые 3д модели мобов - они выглядят потрясающе!). Я перерисовал несколько текстур, другие взял из майнкрафта и изменил в фотошопе, хочу обновления мода дивайн рпг во всех планах, включая текстуры блоков и предметов (могу скинуть некоторые текстуры). 7 После удара мечем с чарами "заговор огня" пропадают некоторые монстры: краб, томо Эдема (зелёная лягушка с антеннами) Король крабов. К сожалению, из-за того, что босса в эдеме повторно убить нельзя, монстры в аду не появляются, и руды эдема не генерируются, мод пройти НЕВОЗМОЖНО. Также мешают прохождению ранее перечисленные по номерам ошибки и недоработки. Надеюсь на светлое будущее мода Divine rpg, так как помню старые версии этого мода, когда таких серьёзных проблем не было.
ссылка на видео с проблемами https://www.youtube.com/watch?v=FHO0rqKfRqo , Большая часть мобов, которые спавнятся в аду - мобы из майнкрафт и advent of ascension, я старался это продемонстрировать. Scorcher не появился не разу, летал по всему аду.

**Comment by Locomenmod** [comment]
Можешь, пожалуйста, прислать лог касательно 2 пункта. Выводит какую-нибудь ошибку или нет?

**Comment by Locomenmod** [comment]
1. Исправлено в e632f20f258982e31f0714f0202b7b785be1cf1e
2. Жду от вас дополнительной информации по этой проблеме
3. Спаунятся, однако достаточно редко
4. У меня мобы появляются, не знаю почему вы не можете их найти
5. Они и есть нейтральны (WATER_CREATURE), однако да, я предложу пересмотреть это
6. Любые предложения касательно текстур, развития мода и т.п. вы можете оставить в дискорде, в канале #suggestions
7. У меня всё работает и никто не продает https://prnt.sc/mkDOCOM-g1P3 https://prnt.sc/hctOpRB4TM5F

**Comment by amused92octopus** [comment]
https://www.youtube.com/watch?v=FHO0rqKfRqo тут я все на видео снял. Босс в версии 1 8 7 стал лучше призываться и атаковать, а все остальные проблемы есть в видео.

**Comment by Locomenmod** [comment]
Суть проблемы со спаунером нам ясна, но прикрепите, пожалуйста, лог того, что происходит когда вы нажимаете на спаунер. Лог вы можете найти в папке, там где у вас расположена игра, в папке logs.

**Comment by volkovihae** [comment]
The problem with the creative was solved, but there was a problem of compatibility with other mods. So for example, you can not fly for a bat in vampirism!

**Comment by NicosaurusRex99** [comment]
Is that not sorted?

**Comment by volkovihae** [comment]
What is sorted?

**Comment by NicosaurusRex99** [comment]
Is the compatability issue resolved?
for me it is

**Comment by volkovihae** [comment]
Not resolved. Watching it right now on 1.8.8

**Comment by maxanier** [comment]
Regarding the flight issue:
This seems to be related to the angelic armor functionality. The code permanently disables flying while the armor is not fully equipped. There must be a different solution for this.
[ArmorAbilitiesEvent ](https://github.com/DivineRPG/DivineRPG/blob/1c3ef733340b93027db2415f7530c994b0bfc6af/src/main/java/divinerpg/events/ArmorAbilitiesEvent.java#L276-L286)

**Comment by NicosaurusRex99** [comment]
Fixed in [22e4059](https://github.com/DivineRPG/DivineRPG/commit/22e40594f57461efffc3a20003ca3547538bf6c7)
