### ISSUE TITLE
Flight bug fix in 1.8.7 seems to disable flying in Creative and Spectator mode not wearing Angelic armour [1.16.5]

### ISSUE THREAD

**Issue by Jstamz** [DivineRPG/DivineRPG#474]
Hello. It seems to disable flying in creative mode now. Why did `!entity.isCreative() && !entity.isSpectator()` get deleted?

_Originally posted by @KiriniriK in https://github.com/DivineRPG/DivineRPG/issues/470#issuecomment-1065878005_

**Comment by NicosaurusRex99** [comment]
Reported in #472 English translation is #473
