### ISSUE TITLE
Можешь, пожалуйста, прислать лог касательно 2 пункта. Выводит какую-нибудь ошибку или нет?

### ISSUE THREAD

**Issue by amused92octopus** [DivineRPG/DivineRPG#475]
Можешь, пожалуйста, прислать лог касательно 2 пункта. Выводит какую-нибудь ошибку или нет?

https://www.youtube.com/watch?v=FHO0rqKfRqo тут я все на видео снял. Босс в версии 1 8 7 стал лучше призываться и атаковать, а все остальные проблемы есть в видео.

**Comment by Locomenmod** [comment]
Пожалуйста, не создавайте новые issue для ответов на сообщения. Issue стоит создавать только для того, чтобы сообщить о новых проблемах.
