### ISSUE TITLE
Latest update broke something.

### ISSUE THREAD

**Issue by TrueGuardian32** [DivineRPG/DivineRPG#476]
**DivineRPG version**
1.8.7

**Describe the bug**

Flight is disabled in creative and spectator mode.

**To reproduce**
Steps to reproduce the behavior.

Turn on spectator mode, fall into the void.

**Expected behavior**
Fly when in spectator mode.

**Screenshots**

**Additional context**

**Comment by Locomenmod** [comment]
Fixed in 0a56be20afaa767eb90083d0faa205242c5fcdb4

**Comment by TrueGuardian32** [comment]
> Fixed in [0a56be2](https://github.com/DivineRPG/DivineRPG/commit/0a56be20afaa767eb90083d0faa205242c5fcdb4)

Where can I get that version?

**Comment by NicosaurusRex99** [comment]
its not out yet
