### ISSUE TITLE
Jack o man spawn rate

### ISSUE THREAD

**Issue by Swifty744** [DivineRPG/DivineRPG#477]
**DivineRPG version**
Latest version

**Describe the bug**
Jack 'o' man keep spawning too frequently. It's a great trader and all but don't need it spawning every what feels like 5 minutes

**To reproduce**
Not sure, it just happens. I have built a small town not sure if it spawns more frequently due to the biome im in either (plains) in biomes you'll go but nothing special

**Expected behavior**
The jack o man needs to be changed to once every 6-10 in game days.

**Screenshots**
https://prnt.sc/_VIBQIm6AcEm - theres just too many

**Additional context**
It's more of an annoyance. I was hoping there was a setting in the config to turn the spawn rate down

**Comment by NicosaurusRex99** [comment]
[a5d2747](https://github.com/DivineRPG/DivineRPG/commit/a5d2747f27dd228c196db57f56c88f5a339bacef)
