### ISSUE TITLE
Flight Disabled In Other Mods?

### ISSUE THREAD

**Issue by TrueGuardian32** [DivineRPG/DivineRPG#478]
**DivineRPG version**
This is the version number on the mod file and is also viewable in-game. "Latest" or the Minecraft version are not acceptable answers. Unfortunatley we cannot change versions below 1.16.5, feel free to leave a report but there is nothing we can do
1.8.8
**Describe the bug**
With this mod flight seems to be disabled in all other mods, which is really annoying when your a Vampire who finally managed to get to the level of becoming a bat. So I started testing with other mods, Angel Ring? Flight Disabled, Orb of Temporary Flight? Flight Disabled.

**To reproduce**
Steps to reproduce the behavior.
Use a flight item from any other mod. I tested with Forbidden and Arcana and Vampirism thus far. 

**Expected behavior**
Fly
**Screenshots**

**Additional context**
I just wanted to know if this is intentional or not, if so, why? Shouldn't the players themselves have a choice on whether they want to fly with other mods or not? It may allow cheesing in the mod because how powerful flight can be, but it should be the players choice right?

**Comment by Ringedtech203** [comment]
Duplicate of #472

**Comment by TrueGuardian32** [comment]
Ah didn't notice the topic got added to that.
