### ISSUE TITLE
Arcana bugs

### ISSUE THREAD

**Issue by hjbaa** [DivineRPG/DivineRPG#484]
**DivineRPG version**
1.8.10, minecraft 1.16.5

**Describe the bug**

1. You can still break unbreakable doors in Arcana using rive enchantment
2. Some of mob spawners spawns at y = 1 (right above the void)
3. Weird traders spawning (I didn't see any of them even where they should be)

**To reproduce**
1. Place torch above the door

![like this](https://user-images.githubusercontent.com/81980753/161950428-bbb8e0d4-f7ad-405f-bdfe-6650d3f9a03c.png) 

and break it using rive (2 or 3) enchantment.

2. Find specific rooms, where spawners could spawn 

![like this](https://user-images.githubusercontent.com/81980753/161951235-e6291c02-70d3-489f-a7ce-f3115a75d151.png)

3. Go to Arcana

**Expected behavior**
1) Doors are unbreakable
2) You can't fall into the void
3) Trades appear

**Screenshots**
[Video with 1st and 2nd bug](https://youtu.be/smYGQWe10tI)

**Comment by hjbaa** [comment]
There is also another small bug when mobs appear above the roof of the arcana
[screenshot](https://prnt.sc/UCzHZruiosA4)

**Comment by NicosaurusRex99** [comment]
not uber concerning that last one, but still could be optimized

**Comment by NicosaurusRex99** [comment]
trader mobs have a spawner block inside trader rooms so thats not an uber issue, would just be a case of waiting a few minutes

**Comment by NicosaurusRex99** [comment]
Fixed in 5879736
