### ISSUE TITLE
Arcana & vethea traders bugs

### ISSUE THREAD

**Issue by hjbaa** [DivineRPG/DivineRPG#485]
**DivineRPG version**
1.8.10, minecraft v. 1.16.5

**Describe the bug**
1. Traders spawn very rarely even where they should be. For example, having flown about 20 Hunger huts, I found only one. Roughly speaking, this is the same bug as in the Arcana.
2. Even if you find a trader, his trade window closes immediately after clicking on the RMB. This only works with naturally spawned traders, if you spawn them using spawn egg, it will be ok
3. When you die in vethea you respawn in overworld
4. Traders have no animations & they don't move

**To reproduce**
Visit Vethea or Arcana

**Expected behavior**
1. They should spawn in their huts
2. You can trade with them without any problems
3. You will respawn in Vethea (comparing with previous versions of DivineRPG)
4. Traders have animations 

**Screenshots**
[Video](https://youtu.be/ayDlAvkGYQ4)

**Additional context**

**Comment by NicosaurusRex99** [comment]
Additional info. Traders respawn after time (there is a hidden block that spawns them in if there are none, it just fires slowly as to not case too many mobs being around. That said, ill reduce the spawn timer
