### ISSUE TITLE
Rive enchantment doesn't work

### ISSUE THREAD

**Issue by hjbaa** [DivineRPG/DivineRPG#489]
**DivineRPG version**
1.8.11

**Describe the bug**
Rive enchantment doesn't work at all. You break exactly 1 block as if there is no enchantment on your tool

**To reproduce**
Enchant any of the tools to rive enchantment (any level)

**Expected behavior**
Rive 1 breaks 3x3x1 area
Rive 2 breaks 3x3x2 area
Rive 3 breaks 3x3x3 area

**Comment by NicosaurusRex99** [comment]
Had my if logic backwards. Fixed and update is released
