### ISSUE TITLE
Ticking entity crash (Frost)

### ISSUE THREAD

**Issue by Niketats** [DivineRPG/DivineRPG#492]
**DivineRPG version**
1.8.14

**Describe the bug**
Crash when just walking around cold biomes

**To reproduce**
i'm not sure
There is crash report
[crash-2022-04-25_18.21.43-server.txt](https://github.com/DivineRPG/DivineRPG/files/8555963/crash-2022-04-25_18.21.43-server.txt)

**Comment by NicosaurusRex99** [comment]
Thanks for the report. I forgot to add a null checker on the frosts target entity. Will patch tomorrow

**Comment by Thorson123** [comment]
Its not just the frost btw its any mob that flies and shoots projectiles: fractite, ender triplets, scorcher, dissiment, etc

**Comment by NicosaurusRex99** [comment]
It'll be any that implement IRangedMob
