### ISSUE TITLE
Rive enchantment doesn't work on many blocks

### ISSUE THREAD

**Issue by hjbaa** [DivineRPG/DivineRPG#494]
**DivineRPG version**
1.8.14

**Describe the bug**
Using rive enchanment, some of blocks does not break in 3x3 area:

- blackstone
- obsidian
- furnace
- end stone
- Nether quartz ore
- Any of quartz block variations
- Any of stone bricks variations
- Any terracota
- Any purpur blocks
- Nether bricks
- Prismarine blocks
- Glass
- etc

**To reproduce**
Break any of these block with rive 

**Expected behavior**
Blocks will break in area

**Comment by NicosaurusRex99** [comment]
Rive will not work on tile entities and it only breaks blocks that it is 1, the effective tool, so axe for wood, pick for stone. and also if it has the right mining level, so iron tools to break diamond ore and what not

**Comment by hjbaa** [comment]
@NicosaurusRex99, https://www.youtube.com/watch?v=flgsVhRPL3g
breaking terracota with halite terraformer, dream pickaxe and netherite pickaxe
