### ISSUE TITLE
Iceika portal cannot be activated

### ISSUE THREAD

**Issue by hjbaa** [DivineRPG/DivineRPG#495]
**DivineRPG version**
1.8.17

**Describe the bug**
Iceika portal cannot be activated

**To reproduce**
Make nether-like portal from snow blocks, then throw snowball on one of the edges

**Expected behavior**
Iceika portal would be activated

**Screenshots**
https://youtu.be/6-7f8BWuD3Q

**Additional context**
As you can see in the video, other portals can be activated, but not iceika portal

**Comment by RickieGamer** [comment]
You’re meant to use a snow globe to light the portal, not snow balls
