### ISSUE TITLE
Rive enchantment bug

### ISSUE THREAD

**Issue by hjbaa** [DivineRPG/DivineRPG#496]
**DivineRPG version**
1.8.17

**Describe the bug**
Rive doesn't work on many blocks:

- blackstone
- obsidian
- furnace
- end stone
- Nether quartz ore
- Any of quartz block variations
- Any of stone bricks variations
- Any terracota
- Any purpur blocks
- Nether bricks
- Prismarine blocks
- Glass
- etc

**To reproduce**
Break one of these blocks with tool, enchanted for rive

**Expected behavior**
Any blocks that are not indestructible, are not nile entities must be destroyed. Also you need right tools & right mining level.

**Screenshots**
https://youtu.be/flgsVhRPL3g

**Additional context**
A good example of how it should work is version 1.8.9, but in this version, absolutely any blocks break (including indestructible and tile entities)

In the video, I break terracotta with pickaxes (right mining level & efficiency) and halite terraformer enchanted on rive 3.

**Comment by NicosaurusRex99** [comment]
Ive tweaked it a bit but any tile entity (furnaces included) will not break [cee561c](https://github.com/DivineRPG/DivineRPG/commit/cee561c9ee1c9ab53559a78fbc2f7eb2c3a7f58f)
