### ISSUE TITLE
[SUGGESTION] Way to deactivate Cave Crawler's & Rotatick's

### ISSUE THREAD

**Issue by Gaminguide1000** [DivineRPG/DivineRPG#497]
Im currently building an Underground Base in Survival. Okay, cool. The problem wit hthis is, that there are many cave crawlers & rotaticks. I searched all DivineRPG configs, bgut couldnt find any where i could deactivate spwning of them.

**Comment by Gaminguide1000** [comment]
Same counts for every mob spawning in the underground regardless of light level

**Comment by NicosaurusRex99** [comment]
Best I can do is suggest mcjtys miss in control
