### ISSUE TITLE
Cannot mining Wildwood Ore

### ISSUE THREAD

**Issue by Mega0335** [DivineRPG/DivineRPG#498]
**DivineRPG version**
1.8.16 through 1.8.18

**Describe the bug**
Cannot mining Wildwood Ore using Rupee or better pickaxe.

If need more information, please let me know.

**Comment by NicosaurusRex99** [comment]
You need an Eden pick to mine the wildwood. You need a wildwood pick to mine Apalachian ore. You need apalachia ore to mine skythern and you need skythern pick to mine mortum ore

**Comment by Mega0335** [comment]
I got it, Thank you very much!!
