### ISSUE TITLE
Armors still don't have armor toughness

### ISSUE THREAD

**Issue by EatingSilencer** [DivineRPG/DivineRPG#503]
**DivineRPG version**
This is the version number on the mod file and is also viewable in-game. "Latest" or the Minecraft version are not acceptable answers. Unfortunatley we cannot change versions below 1.16.5, feel free to leave a report but there is nothing we can do
1.8.19

**Describe the bug**
Same issue as last time.

**Comment by NicosaurusRex99** [comment]
#499
