### ISSUE TITLE
Silk Touch not functioning on twilight ores in 1.8.19

### ISSUE THREAD

**Issue by Pricerocks** [DivineRPG/DivineRPG#504]
**DivineRPG version**
This is the version number on the mod file and is also viewable in-game. "Latest" or the Minecraft version are not acceptable answers. Unfortunatley we cannot change versions below 1.16.5, feel free to leave a report but there is nothing we can do

1.8.19

**Describe the bug**

Silk Touch doesn't work on Twilight dimension ores, drops 1 fragment instead.

**To reproduce**
Steps to reproduce the behavior.

Mine any twilight ore with a silk touch pickaxe

**Expected behavior**

For twilight ores to drop themselves mined with silk touch

**Screenshots**
n/a
**Additional context**
n/a

**Comment by NicosaurusRex99** [comment]
This is intentional due to a dupe bug
