### ISSUE TITLE
Armours durability.

### ISSUE THREAD

**Issue by VilgelmSkht** [DivineRPG/DivineRPG#505]
Minecraft 1.16.5 DivineRPG 1.8.19

So, I made a Eden Armour and its Durability is 340? It crocked in like 10 minutes in fighting with mobs. Other Armour have the same problem. What is the problem?

![2022-05-21_00 56 02](https://user-images.githubusercontent.com/105949194/169609404-65e105aa-4805-488c-a04a-13e6a2ef5a96.png)

**Comment by NicosaurusRex99** [comment]
Im not going to make values crazy high like i assume youre wanting but ive tweaked some
