### ISSUE TITLE
Unique mobs in Edem (and Iceika) are not spawning

### ISSUE THREAD

**Issue by Kre4** [DivineRPG/DivineRPG#506]
**Versions**
Minecraft - 1.16.5
DivineRPG - 1.8.20
Forge (on server) - 36.2.34
Also, there are datapacks, "new in town" and "TreeCapitator" on server.

**Describe the bug**
One day me and my friends have discovered that unique mobs are not spawning in otherworlds, but there are zombies, crabs and creepers.  Why is it going that way?

**Screenshots**
![2022-06-17_23 54 47](https://user-images.githubusercontent.com/37481171/174400493-1c812f4c-f035-41ce-b873-c616313c420e.png)
![2022-06-17_23 54 59](https://user-images.githubusercontent.com/37481171/174401868-001b71f8-782c-48c7-aeaa-9c7eb682f614.png)

**Comment by EatingSilencer** [comment]
What biome does it say you are in?

**Comment by Kre4** [comment]
lol, ocean...
![2022-06-19_13 52 02](https://user-images.githubusercontent.com/37481171/174480434-d01e79bd-e333-4533-995c-f16e2cef3520.png)

**Comment by EatingSilencer** [comment]
Somehow the biome got messed up.

Is the biome messed up when you try the dimensions in a new world?

**Comment by Natedogwoooof** [comment]
Same here but I'm on a version 1.12.2 and the biomes both say the correct ones that they should but still no Divine RPG mobs in sight the only ones in Ikea were the ones that were spawning in the houses and dungeons

**Comment by NicosaurusRex99** [comment]
> Same here but I'm on a version 1.12.2 and the biomes both say the correct ones that they should but still no Divine RPG mobs in sight the only ones in Ikea were the ones that were spawning in the houses and dungeons

1.12.2 Custom Mob Spawner mod is the only mod we know that causes this... that said 1.12.2...
