### ISSUE TITLE
Creative invenotry

### ISSUE THREAD

**Issue by Shadow232** [DivineRPG/DivineRPG#51]
If you open creative inventory and begin thumb through pages of inventory, game client will crash.

error log:

http://pastebin.com/HqZ8cxeK

**Comment by RadioactiveStud** [comment]
Works for me. What forge are you using? You cut that part out of the crash report.

**Comment by Shadow232** [comment]
forge 1277

**Comment by RadioactiveStud** [comment]
Probably not the problem, but I am using forge 1230. Does it crash if you only use DivineRPG without any other mods? Does it crash every time?

**Comment by Shadow232** [comment]
maybe you are right, because before it i played in forge 1230 :) Close it. But it crashe every time :)

**Comment by Eternaldoom** [comment]
This sounds like it's caused by another mod. Even in newer forge builds, I'm not getting this error.

**Comment by RadioactiveStud** [comment]
Closed until it can be reproduced.
