### ISSUE TITLE
Stop Crabs Spawning on/in Player Structures

### ISSUE THREAD

**Issue by sup3rmanzzz** [DivineRPG/DivineRPG#510]
King Crabs and Crabs can seemingly spawn on any block as they're currently the only mobs that can spawn in my base high off (y: 200) the ground and made mostly of glass and marble. The base is above a beach. Since no other mobs can spawn in range of me this leads to tens of crabs spawning in literally every area of the place, it's ridiculous. I tried to go into the files manually to disable the mob but there's seemingly no convenient way to do that (perhaps config options to disable specific mobs could be useful?). 

With peaceful mobs in Minecraft isn't it standard that they can only spawn on certain blocks? Maybe the crabs can be limited to sand/gravel or whatever it is that are common to beaches. 

I know there is another ticket of the same issue, it was closed with the solution being "just build out of slabs" (paraphrasing). That's a ridiculous restriction to place on the player in order for them not to have crabs. I'm playing in a pretty bloated modpack with hundreds of added mobs, and these god forsaken crabs are the only things that can just spawn wherever the hell they want.

**Comment by NicosaurusRex99** [comment]
Crabs have the same restrictions as other mobs, the only difference is crabs have a smaller hitbox and can fit in more areas

**Comment by sup3rmanzzz** [comment]
![image](https://user-images.githubusercontent.com/13978885/184726667-6d396f7a-4907-4857-8119-ddbef9135c0f.png)

**Comment by Ringedtech203** [comment]
crabs can spawn on any blocks in 1.12 for some reason, unfortunately as it is an issue for 1.12 we cannot update it to fix that. if you are on singleplayer the best I can suggest is giving yourself a megatorch or ask for other ideas on the DJ2 discord

**Comment by NicosaurusRex99** [comment]
oh 1.12.2

**Comment by sup3rmanzzz** [comment]
Okay fair enough, thanks for the help guys
