### ISSUE TITLE
Why the main boss of wild forest flying away during the fight?

### ISSUE THREAD

**Issue by PMasevich** [DivineRPG/DivineRPG#511]
**1.8.20-1.8.24**
Minecraft 1.16.5

**Describe the bug**
During the fight with boss of wild forest he gradually flying from me away (in the sky). I have no angels armor and I don't know how I can reach the next dimension.

**To reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by NicosaurusRex99** [comment]
Fixed in [22d4fb4](https://github.com/DivineRPG/DivineRPG/commit/22d4fb495b68557adec134e3f850ad7094b105cd)
