### ISSUE TITLE
No Aquatic Creature Spawns in 1.8.5

### ISSUE THREAD

**Issue by murderkaiser** [DivineRPG/DivineRPG#512]
**DivineRPG version**
1.8.5

**Describe the bug**
There are frankly no aquatic creatures - no crabs, whales, or sharks spawn when I start new games. I've looked through all of the biomes, for countless hours on end - no aforementioned creatures to be found. I see that there are recipes for the materials that they drop (I use a recipe-showing mod, JustEnoughItems), but the creatures are nowhere to be found.

**To reproduce**
I'm not sure - just play the version of the game?

**Expected behavior**
I expected there to be crabs and other aquatic creatures, haha.

**Screenshots**
-

**Additional context**
-

**Comment by NicosaurusRex99** [comment]
thats a really outdated version. use 1.8.25


https://divine-rpg.fandom.com/wiki/Version_History
notice literally the next version increased water mob spawns... that said even thats out of date

**Comment by murderkaiser** [comment]
Thanks so much, I never noticed that!

One last question - if I update straight to the latest version, will this also update my save files - as in, will I be able to play them, or will it cause some compatibility / chunk spawning issues, and it will only work with new game seeds?

Sorry if it's a dumb question, I lack the tech-savviness to comprehend it, haha.

**Comment by NicosaurusRex99** [comment]
should be fine but if youre worried make a backup

**Comment by murderkaiser** [comment]
Thank you very much, I appreciate the answer! All the best!
