### ISSUE TITLE
Rive ench breaks indestructible blocks

### ISSUE THREAD

**Issue by hjbaa** [DivineRPG/DivineRPG#513]
**Game version**
1.9.1, latest for minecraft 1.19.2

**Describe the bug**
You can break any indestructible block using tool with rive enchantment

**To reproduce**
Break block nearby indestructible block

**Expected behavior**
indestructible blocks are not destroyed

**Comment by NicosaurusRex99** [comment]
thanks for the report. will be in the next alpha
