### ISSUE TITLE
[1.19.2] - A feature cycle was found (pneumaticcraft:oil_lake and divinerpg:tar_lake conflict)

### ISSUE THREAD

**Issue by aking4125** [DivineRPG/DivineRPG#516]
**DivineRPG version 1.9.1**

Upon world creation. The game crashes with the error "_A feature cycle was found_". Installing the mod **[Cyanide](https://www.curseforge.com/minecraft/mc-mods/cyanide-forge)** allowed me to identify the error was between Pneumaticcraft and DivineRPG. Removing DRPG allows the world to generate normally.

Without Cyanide installed: [crash-2022-10-09_08.38.41-server.txt](https://github.com/DivineRPG/DivineRPG/files/9741699/crash-2022-10-09_08.38.41-server.txt)

With Cyanide Installed: [crash-2022-10-09_08.59.42-server.txt](https://github.com/DivineRPG/DivineRPG/files/9741700/crash-2022-10-09_08.59.42-server.txt)

Attempt to blacklist Pneumaticcraft oil lakes in their config: [crash-2022-10-09_09.18.42-server.txt](https://github.com/DivineRPG/DivineRPG/files/9741701/crash-2022-10-09_09.18.42-server.txt)

Any ideas?

**Comment by Thezapman1** [comment]
Try updating Pneumaticraft to their test build version: pneumaticcraft-repressurized-1.19.2-4.1.2-145

You can find it on their github, it made generating the world work for me with both mods and include the config settings for pneumaticraft

**Comment by NicosaurusRex99** [comment]
fixed in 1.9.2
