### ISSUE TITLE
Minecraft1.19 divine RPG welcome message

### ISSUE THREAD

**Issue by uhloin** [DivineRPG/DivineRPG#518]
Every time game loaded I have message "This build ... is alpha..."
I found option in config to turn off welcome messages but it does not work.
May be it is because message is not for "welcome" but for pain in eyes :)

**Comment by NicosaurusRex99** [comment]
This is very intentional. It's only sent to the client side so only you will see it.

**Comment by uhloin** [comment]
I would prefer do not see it. At least once but not every time. I use 50+ mods, some of them in alpha mode but only one use such obtrusive warning.
