### ISSUE TITLE
(1.19.2-1.9.5) NPE Enitity crash

### ISSUE THREAD

**Issue by RickieGamer** [DivineRPG/DivineRPG#520]
**DivineRPG version**
DivineRPG-1.9.5

**Describe the bug**
Something shooting is crashing the game, only a client side crash

[crash-2022-10-27_20.49.26-client.txt](https://github.com/DivineRPG/DivineRPG/files/9884486/crash-2022-10-27_20.49.26-client.txt)

**Additional context**
I was summoning bosses in mortum, unsure which boss is cause the crash

**Comment by NicosaurusRex99** [comment]
Fixed will be in next patch
