### ISSUE TITLE
Some of DivineRPG's recipes conflict with itself

### ISSUE THREAD

**Issue by pupnewfster** [DivineRPG/DivineRPG#522]
**DivineRPG version** 1.9.6.1
**Forge version** 43.1.47

**Describe the bug**
Some of DivineRPG's recipes conflict with itself.
- Torridite Ingot has a shapeless recipe creating Torridite Nuggets and a different shapeless recipe creating Torridite Bricks
- There are two identical recipes to craft the Arcanium Torch

**To reproduce**
1. Look at the above listed recipes in JEI

**Comment by NicosaurusRex99** [comment]
Thanks for the report, fix will be in the next release
