### ISSUE TITLE
1.19.2 Server Side Questions - Testing with End and World Generation

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [DivineRPG/DivineRPG#523]
So not saying this mod is the cause but everything was working till we reached the end. These were all the mods present that had been changed or added after the crash/hangs began. 

At any rate Thutmose creator of Pokecube said this specific issue https://gist.github.com/P3rf3ctXZer0/f4c2a6542f128e3cfc8506ced422fbad

Has to do with lighting and the player that first managed the crash was in the end after having defeated the ender dragon.

{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}

# 1.19.2 [24.0.0 ``A New Journey``]

## Legend

* [C] means client
- [S] means server
* [U] means universal aka client and server
- [W] means world save file

### These new annotations mark where the changes are so I can fully grasp all possible changes for future content. This helps me debug issues.

##Performance Status

- Forge Version: 43.1.47 - https://maven.minecraftforge.net/net/minecraftforge/forge/1.19.2-43.1.47/forge-1.19.2-43.1.47-changelog.txt
* Mod Count Ingame [315]
- FPS average [60] to [Unlimited]
* Java Args [``-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:InitiatingHeapOccupancyPercent=15 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true``] and Java Version [17x64] JDK or JRE https://adoptium.net/temurin/releases

##### [C]

- JadeAddons-1.19.2-forge-3.0.1
- Neat-1.19-32

##### [U]

- DivineRPG-1.9.6.1 (A huge rpg based mod with lots of unique features.)
- dynamic_player_progression_and_player_difficulty_1.19.2-3.9.0 (The game is tailored to your skill.) (Removed after issues)
- pipez-1.19.2-1.0.0
- pokecube_compat-1.19.2-1.0.3 (Removed after issues)
- pokecube-aio-1.19.2-3.19.2 (Removed after issues)
- pokecube-level-restriction-1.19.2-1.2.0 (Removed after issues)

##### [C]

- RubidiumExtra-1.19.2-0.4.11.44

##### [U]

- allthemodium-2.0.9-1.19.2-43.0.7
- appliedcooking-2.0.2
- appliedenergistics2-forge-12.8.4
- Applied-Mekanistics-1.3.3
- ars_instrumentum-1.19.2-3.2.0
- ars_nouveau-1.19.2-3.4.6
- collective-1.19.2-5.13
- domum_ornamentum-1.19-1.0.67-ALPHA-universal
- geckolib-forge-1.19-3.1.34
- HammerLib-1.19.2-19.2.37
- IC2Classic-1.19.2-2.0.1
- immersive_paintings-0.3.1+1.19.2
- jei-1.19.2-forge-11.4.0.279
- MCDoom-Forge-1.19.2-4.2.19
- megacells-forge-1.5.3-1.19.2
- minecolonies-1.19.2-1.0.1088-ALPHA
- modonomicon-1.19.2-1.6.0
- moonlight-1.19.2-2.1.4-forge
- occultism-1.19.2-1.48.0
- Platter-1.19-v2
- spoornarmorattributes-2.0.8-1.19-forge

## Mods-On-Standby

- ChunkByChunk-forge-1.19.2-1.9.0.jar.disabled (Crashes with IC2 and other mods.)

## Notes

- DivineRPG, Dynamic Difficulty and Pokecube + addons are restored.

{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}{}

**Comment by NicosaurusRex99** [comment]
could i get a full log?

**Comment by P3rf3ctXZer0** [comment]
Um no. Cause I deleted it. I should have kept it but I was really tired. Apologies. Its why I am not saying for sure your mod. I will test it more later. I will make version 24.0.1 available to the public again on curseforge ... only problem is you probably also need my world. The one that crashed was deleted. (It is so much work to upkeep a modpack.)

**Comment by P3rf3ctXZer0** [comment]
https://www.curseforge.com/minecraft/modpacks/fiction-friction/files/4061535

**Comment by NicosaurusRex99** [comment]
i cant promise ill find the cause but ill look into it tomorrow

**Comment by NicosaurusRex99** [comment]
if the issue persists, reopen the issue

**Comment by P3rf3ctXZer0** [comment]
How has testing gone?

**Comment by NicosaurusRex99** [comment]
Pack didn't load. There's too many issues

**Comment by P3rf3ctXZer0** [comment]
That is curious cause I mean 23.0.0 works fine. In fact it works so well I opted to labeling it stable and decided I should start a new branch dedicated to Quality Assurance.
