### ISSUE TITLE
[1.19.2] Dungeon of Mystery merchant issue

### ISSUE THREAD

**Issue by Fikys2277** [DivineRPG/DivineRPG#524]
DivineRPG version: 1.9.6.1

Only Lord Watticus appears in the Dungeon of Secrets. Merchants such as Lord of War, Captain Merik and others do not appear.

I thought I would go into the dimension right now and start bargaining to get items, but in the end I didn’t find anyone except Watticus

**Comment by velocityraptor-real** [comment]
they are encaged in spawner blocks you need to right click in order to spawn them

**Comment by Fikys2277** [comment]
> they are encaged in spawner blocks you need to right click in order to spawn them

thank you very much

**Comment by Fikys2277** [comment]
there are no imprisoned merchants either

**Comment by velocityraptor-real** [comment]
will be fixed in next version
