### ISSUE TITLE
Arlemite armor set decreases ranged damage dealt by player wearing it

### ISSUE THREAD

**Issue by wgos** [DivineRPG/DivineRPG#531]
**Minecraft version**
1.19.2

**DivineRPG version**
1.9.6.1

**Describe the bug**
Arlemite armor set decreases ranged damage dealt by player

**To reproduce**
1. Wear full Arlemite set to get bonus
2. Attack mob with ranged weapon

**Expected behavior**
According to description of Arlemite set it should provide "85% Ranged Damage Protection" and I assume that this should apply to only player wearing it but not the targets. Either description should be changed or resistance applied to player only

**Video**
https://youtu.be/ZKozl2yMQ98

**Additional context**
I assume that Corrupted armor set will increase ranged damage dealt **_to_** player but I didn't really checked for it.

Mod list: https://dpaste.org/GkzSP/raw

**Comment by NicosaurusRex99** [comment]
Fixed will be in next patch
