### ISSUE TITLE
Не прорисовывается текстура мобов, как исправить?

### ISSUE THREAD

**Issue by Berserker29** [DivineRPG/DivineRPG#533]
добрый день, у меня проблема
не прорисовывается текстурка мобов, что делать в такой ситуации если это только у меня?
и как скоро вы решите эту проблему если она у всех?
просто не комфортно играть с такими вот ошибками
![2022-11-27_02 27 29](https://user-images.githubusercontent.com/119140139/204112849-a001e309-4921-4c8a-b459-1430e004cafa.png)
![2022-11-27_02 25 32](https://user-images.githubusercontent.com/119140139/204112850-9404e428-4c72-4793-87a2-597b6e5e51d4.png)
![2022-11-27_02 25 42](https://user-images.githubusercontent.com/119140139/204112852-099be7a2-50f4-47ca-8d64-1aec91db13b5.png)

**Comment by WangJingwei2** [comment]
Такая же проблема с Гласайдом, жди патч. Как скоро - спроси у самих разработчиков мода.

**Comment by NicosaurusRex99** [comment]
фикс почти готов

(Google translate: the fix is almost ready)
