### ISSUE TITLE
DivineRPG (1.7.10) crashes with 1Legends mods in server sided minecraft

### ISSUE THREAD

**Issue by YehiaShalaby** [DivineRPG/DivineRPG#535]
Here is my crash 
[crash-2023-01-02_19.50.27-server.txt](https://github.com/DivineRPG/DivineRPG/files/10333914/crash-2023-01-02_19.50.27-server.txt)

**Comment by Ringedtech203** [comment]
go into the DivineRPG config file and change I:"Eden dimension ID"=50 to a different number

**Comment by YehiaShalaby** [comment]
man thx for the help. Your guys are the greatest.
