### ISSUE TITLE
Server-forge 43.2.0

### ISSUE THREAD

**Issue by Laminatik** [DivineRPG/DivineRPG#542]
Problem: for example "Sunstorm", this spawner just take Eden Chunk and doesn't send any messege and 
does not summon the boss.
Version of: DivineRPG-1.9.6.3.jar
Server-forge: 43.2.0
Settings of server and mod cfg: default
Note: This issue only on server, in single player all work good.

**Comment by NicosaurusRex99** [comment]
update to 1.9.7.
