### ISSUE TITLE
Dimensions Portals repeated themselves..

### ISSUE THREAD

**Issue by LonelyAngelKritZa01** [DivineRPG/DivineRPG#544]
Can someone help me when I enter any Divine RPG Dimension Portals and come back to Overworld. It just spawn another ones next to them. I want it to have one not repeated. How can I fix this?
![Screenshot (11)](https://user-images.githubusercontent.com/117886766/212075256-71e24ab9-5dd8-4046-9f1b-6dd705c9dee6.png)
![Screenshot (9)](https://user-images.githubusercontent.com/117886766/212075287-4df42717-6260-48a8-9b6f-b9d3e48ad1b0.png)

![Screenshot (10)](https://user-images.githubusercontent.com/117886766/212075210-4ad5e4b5-25dc-4507-b61c-74a7a84198e3.png)

**Comment by LonelyAngelKritZa01** [comment]
![Screenshot (10)](https://user-images.githubusercontent.com/117886766/212075449-8e4d4779-3ef7-4b2e-8c6d-c70d3283f956.png)

**Comment by LonelyAngelKritZa01** [comment]
Sorry again, I have another problem. Now I can't even enter my game... 
![Screenshot (12)](https://user-images.githubusercontent.com/117886766/212361843-c781d620-d783-431c-86a3-91224f5f2aed.png)

![Screenshot (13)](https://user-images.githubusercontent.com/117886766/212361888-dba70492-4238-4486-aa3d-f8a468d247be.png)

![Screenshot (14)](https://user-images.githubusercontent.com/117886766/212361918-9335e7e8-2f33-4717-af06-cedd007a76d7.png)

**Comment by NicosaurusRex99** [comment]
second issue says insufficient memory. try allocate more

**Comment by LonelyAngelKritZa01** [comment]
How? I don't know how to fix that. Can you help me?. Maybe because I downloaded those 64 mods..... Sorry to waste your time. I don't know really how to fix it.
Another 3 pics.
![Screenshot (15)](https://user-images.githubusercontent.com/117886766/212363411-0a96148c-7987-4ddb-b98e-d29e6fcc2d6a.png)

![Screenshot (16)](https://user-images.githubusercontent.com/117886766/212363496-33c95968-05e6-4fe4-837b-3e03eea4be8a.png)

![Screenshot (17)](https://user-images.githubusercontent.com/117886766/212363546-29aa646e-ea1f-4ef7-8c35-5649421fcdda.png)
__

**Comment by NicosaurusRex99** [comment]
go to edit profile.

**Comment by NicosaurusRex99** [comment]
from there send a screenshot, im not familiar with this launcher

**Comment by LonelyAngelKritZa01** [comment]
I must say this first. I am one of the players that didn't buy the official one, my family are so poor. I have no money and even skills to fix it myself. I like to downloaded it from any free launcher websites. I say this first because I don't know you can fix this or not when it isn't about an official bought one. Sorry again. It's a Titan Minecraft Launcher with the Mythic MC server with it.

![Screenshot (18)](https://user-images.githubusercontent.com/117886766/212365445-86e7ecdc-eb1e-4d69-b910-be5af96b7459.png)

![Screenshot (19)](https://user-images.githubusercontent.com/117886766/212365466-ccaa4ad7-8525-4eb7-b835-8bcea939ad47.png)

**Comment by NicosaurusRex99** [comment]
ok, so tick the JVM arguements box, the first one that says `-Xmx2G` change the 2 to a 4 (if you have 4 gb ram)

**Comment by NicosaurusRex99** [comment]
if that doesnt fix it, there was alot of logging from geckolib so maybe that (a few different mods use geckolib)

**Comment by LonelyAngelKritZa01** [comment]
Still don't work. Seem like I need to remove gecklolib along with mods that required it.... Also, the bug about the portals you will fix them right?

**Comment by NicosaurusRex99** [comment]
not in 1.19.2, we are focused on 1.19.3. but its noted for 1.19.3

**Comment by LonelyAngelKritZa01** [comment]
Okay...
Um, it show this up. What's it? Have I need to update drivers. Are they free?

![Screenshot (20)](https://user-images.githubusercontent.com/117886766/212367483-af37986d-9ba9-4991-9853-9e5b56b33970.png)

**Comment by NicosaurusRex99** [comment]
i have no idea, i use the curseforge launcher which does everything for me
