### ISSUE TITLE
Dimension ID 50 Problem

### ISSUE THREAD

**Issue by Controllerss** [DivineRPG/DivineRPG#545]
I dont know what to do everytime i try start up the launcher its keeps saying Failed to register dimension for id 50, One is already registered, can someone help and thx.

**Comment by NicosaurusRex99** [comment]
i can tell youre using a really old game version.
if its 1.6.2 or 1.6.4 install this mod
https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1291014-idfix-and-idfix-minus-mods-for-resolving-id

however if its 1.7.10 install this one
https://www.curseforge.com/minecraft/mc-mods/anti-id-conflict/files
