### ISSUE TITLE
Eden Boss not spawning

### ISSUE THREAD

**Issue by NikkitaAurion** [DivineRPG/DivineRPG#546]
The Spawner took my eden chunk and didn't spawn anything or give a message

**Comment by NikkitaAurion** [comment]
then tells me i need one to use on it and it does nothing

**Comment by NicosaurusRex99** [comment]
Fixed in [aadac50](https://github.com/DivineRPG/DivineRPG/commit/aadac502862a6b9a2d86d075441bede592b7ab45)
