### ISSUE TITLE
divinerpg:demon_furnace

### ISSUE THREAD

**Issue by ghost** [DivineRPG/DivineRPG#549]
1.19.2
![image](https://user-images.githubusercontent.com/83486178/218941559-fdb05dcb-b7df-465f-876e-721253969e00.png)

**Comment by NicosaurusRex99** [comment]
is your issue that the particle is wrong side?

**Comment by ghost** [comment]
The texture is wrong

**Comment by NicosaurusRex99** [comment]
go to the other side

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/83486178/218941846-2900bcab-6354-4045-a329-62ae0b2c10d6.png)
![image](https://user-images.githubusercontent.com/83486178/218941867-c239a58a-0d03-48c0-b273-969afe24a81b.png)

**Comment by ghost** [comment]
In the wrong direction

**Comment by NicosaurusRex99** [comment]
the placement is reversed is kinda what i think youve noticed

**Comment by ghost** [comment]
Particle formation is correct

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/83486178/218942079-eafa0024-b667-40fe-90fa-7d0d70a0ce10.png)

**Comment by NicosaurusRex99** [comment]
the issue is more with how it rotates when placed, ill fix this

**Comment by ghost** [comment]
> 问题更多的是它在放置时如何旋转，病了解决这个问题

![image](https://user-images.githubusercontent.com/83486178/236470828-a17b9a9d-8759-4388-bfbb-3ba01bc9f917.png)
![image](https://user-images.githubusercontent.com/83486178/236470843-7ac4f57b-54b2-401e-8f9e-6ba037e8bd27.png)
![image](https://user-images.githubusercontent.com/83486178/236470853-366b20cb-7c7a-49a2-b965-9f8e5a3aea5e.png)
![image](https://user-images.githubusercontent.com/83486178/236470876-fcda35d1-e3a7-4e61-ac62-c2b8f9f440e2.png)
