### ISSUE TITLE
Question - You have not abandoned 1.19.2 Have you?

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [DivineRPG/DivineRPG#550]
Many mods are skipping 1.19.3 despite the clear fixes and are jumping straight to 1.20 are you still keeping up 1.19.2?

**Comment by NicosaurusRex99** [comment]
> Many mods are skipping 1.19.3 despite the clear fixes and are jumping straight to 1.20 are you still keeping up 1.19.2?

We're working on 1.19.3. there is a base version out at the moment but more content is on the works

**Comment by P3rf3ctXZer0** [comment]
So yes 1.19.2 is being halted? Is that what you are saying?

**Comment by NicosaurusRex99** [comment]
> So yes 1.19.2 is being halted? Is that what you are saying?

I'm not opposed to doing some bug fixes because some other stuff is a bit more time consuming. Especially as the known bugs have been fixed on 1.19.3
