### ISSUE TITLE
Pickaxe are invalid and cannot destroy blocks.

### ISSUE THREAD

**Issue by ghost** [DivineRPG/DivineRPG#551]
Pickaxe are invalid and cannot destroy blocks.

**Comment by ghost** [comment]
1.19.2

**Comment by NicosaurusRex99** [comment]
Noted. Thanks for report

**Comment by NicosaurusRex99** [comment]
fixed in [c09fe29](https://github.com/DivineRPG/DivineRPG/commit/c09fe29d266386e0537a25fcd5aff1ca22c93f47)
