### ISSUE TITLE
background

### ISSUE THREAD

**Issue by ghost** [DivineRPG/DivineRPG#555]
All RPG achievement backgrounds are missing
![image](https://user-images.githubusercontent.com/83486178/222966729-a3411798-4a25-416a-8a3a-9d5518103315.png)
![image](https://user-images.githubusercontent.com/83486178/222966756-531378c3-559d-459e-aee0-f25ecfcdfb06.png)

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/83486178/222966802-6ee38409-6712-465c-8e0d-f91bcb77a640.png)
![image](https://user-images.githubusercontent.com/83486178/222966806-68c74e14-62e5-4a86-83f0-581573856ddb.png)
![image](https://user-images.githubusercontent.com/83486178/222966828-281a79c7-da86-4026-a91b-63ffb61a783e.png)

**Comment by NicosaurusRex99** [comment]
This is 1.19.2?

**Comment by ghost** [comment]
> 这是 1.19.2？

1.19.2

**Comment by NicosaurusRex99** [comment]
Fixed in [7c316c9](https://github.com/DivineRPG/DivineRPG/commit/7c316c99eb25ff046d203217897812d1722c3c42)
