### ISSUE TITLE
1.19.2 crash divinerpg:eden_tomo

### ISSUE THREAD

**Issue by ghost** [DivineRPG/DivineRPG#556]
https://gist.github.com/FanRenLa/de92c4031bba2e25f4fe2437cd6ef140

**Comment by NicosaurusRex99** [comment]
does this occur on 1.9.6.7. youre using an older version

**Comment by ghost** [comment]
unknown; This is from my modpack feedback and is not my result.

**Comment by NicosaurusRex99** [comment]
ive not had this issue before and need a bit more info

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/83486178/224495567-27b40b20-cd13-411e-8480-878434216783.png)

**Comment by ghost** [comment]
Isn't that the latest version?

**Comment by NicosaurusRex99** [comment]
yes. but the log you sent has 1.9.6.6
![image](https://user-images.githubusercontent.com/11579935/224495636-884451b3-969d-4c0f-8ee1-c48852fb3680.png)

**Comment by ghost** [comment]
Sorry, I forgot someone else sent it to me.

**Comment by ghost** [comment]
My test results say it doesn't crash

**Comment by NicosaurusRex99** [comment]
¯\_(ツ)_/¯

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/83486178/224496098-4c9d29d5-0da0-49dd-8c9b-6aacc98141fd.png)

**Comment by ghost** [comment]
But his game crashed

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/83486178/224496243-7346e8e4-8c6d-4f0c-932c-dfceeb4573ed.png)
He's fine again

**Comment by NicosaurusRex99** [comment]
hmm

**Comment by ghost** [comment]
end
