### ISSUE TITLE
А new version

### ISSUE THREAD

**Issue by oleg12054** [DivineRPG/DivineRPG#557]
Why was this mod moved from 1.16.5 to 1.19.2. And 1.18.2 is missing. Will these versions be added? Can I wait for those versions that were skipped?

**Comment by NicosaurusRex99** [comment]
1.18 is skipped. We don't have a bigger enough team to support lesser versions

**Comment by oleg12054** [comment]
Thanks for the answer. Is it possible to simply transfer versions without their support?
