### ISSUE TITLE
Ticking entity crash on player when crafting/adding SOME swords

### ISSUE THREAD

**Issue by Simhans** [DivineRPG/DivineRPG#558]
Expected behaviour:

When crafting Ender sword and adding it to inventory the game should not crash.

Additional info: 

I've spawned in both Ender sword and Divine sword which leads to an instant ticking entity crash. No other items from the mod exhibit this error, except some but not all swords. 

Crash log:
[Docs Link because of comment length limit](https://docs.google.com/document/d/1gsCnwBx0zinjUFjd17Ft7hHjVzcHBClTCKEW3JaqEkY/edit?usp=drivesdk)

**Comment by NicosaurusRex99** [comment]
just posting this here so i can see it later
https://gist.github.com/NicosaurusRex99/9cba9b20c6f63a0f0a740b910a9b73c7
