### ISSUE TITLE
No Reciepe

### ISSUE THREAD

**Issue by Shadow232** [DivineRPG/DivineRPG#56]
Moon clock and Mysterios clock dont have reciepe

addition:
Rupee pickaxe, Rupee axe, Rupee shovel, Rupee hoe dont have reciepe.

**Comment by Eternaldoom** [comment]
Moon clocks are vethean, you get them by trading with the hunger. I'll take a look at mysterious clocks.

**Comment by Shadow232** [comment]
ok thx, than more addition:
Korma and Vemos armor sets dont have reciepe

**Comment by Eternaldoom** [comment]
You get them by trading with arcana NPCs.

**Comment by Shadow232** [comment]
Than, need to check armor for balance. I weared halit armor and it was too stupid me killed like kid :D
