### ISSUE TITLE
I have an issue when i pass to another dimension

### ISSUE THREAD

**Issue by imFrankii** [DivineRPG/DivineRPG#560]
The game got a crash, and this is the crash.txt:

Ticking entity

java.lang.ClassCastException: class divinerpg.entities.projectile.EntityDivineArrow cannot be cast to class net.minecraft.world.entity.LivingEntity (divinerpg.entities.projectile.EntityDivineArrow is in module divinerpg@1.9.7 of loader 'TRANSFORMER' @2b44605c; net.minecraft.world.entity.LivingEntity is in module minecraft@1.19.3 of loader 'TRANSFORMER' @2b44605c)

If anyone can give me any solution I would really appreciate it, the error occurs as soon as I pass a portal, for now I only tried with Iceika and Eden, and honestly I don't have any more ideas

**Comment by NicosaurusRex99** [comment]
try version [DivineRPG-1.10.0.1](https://www.curseforge.com/minecraft/mc-mods/official-divinerpg/files/4468915)
it is also 1.19.3 but its our latest file

**Comment by imFrankii** [comment]
Thank you! but I still have the same problem, the first error occurred with a previous version, I don't remember which one, and yesterday I installed 1.10.0.1, which is the latest version, but the problem continued, I only went to the eden portal and the iceika, and the error continued in both

**Comment by imFrankii** [comment]
I figured out that the problem occurs when the SunArchers shoot their arrows, "DivineArrow", I think these are the ones that make my game crash

**Comment by NicosaurusRex99** [comment]
could you send a full log so i can see more info

**Comment by imFrankii** [comment]
I made the mobs appear in the overworld so that they shoot the arrows, and it doesn't crash, only in the other dimensions, I attach the .txt below:


[crash-2023-04-13_00.33.28-server.txt](https://github.com/DivineRPG/DivineRPG/files/11224865/crash-2023-04-13_00.33.28-server.txt)

**Comment by NicosaurusRex99** [comment]
it would seem that nether dungeons mod is doing something with the death event.

**Comment by imFrankii** [comment]
I'm going to try deleting the nether dungeons, I'll let you know anything

**Comment by imFrankii** [comment]
ready! I deleted the other mod and it seems that there was a problem between files that made it crash, for now I had no problem, thanks!
