### ISSUE TITLE
Teaker Staff BUG

### ISSUE THREAD

**Issue by Annijang** [DivineRPG/DivineRPG#564]
"Teaker Staff" will cause the game to crash when it hits an entity.

"Evernight"the right click also crashes.

![image](https://user-images.githubusercontent.com/75552974/233767154-7b797b1c-8a97-4796-a401-d29e95a1e460.png)

Minecraft: 1.19.4
Forge: 45.0.42
Mod: DivineRPG-1.10.2.jar

debug:
[debug.log](https://github.com/DivineRPG/DivineRPG/files/11300422/debug.log)

latest: 
[latest.log](https://github.com/DivineRPG/DivineRPG/files/11300423/latest.log)

**Comment by NicosaurusRex99** [comment]
This appears as if it is a multi mc issue

**Comment by andres19992** [comment]
What do you mean by this? I'm also having this issue. Is it fixed?
