### ISSUE TITLE
Ender Sword of any kind causes a client side crash

### ISSUE THREAD

**Issue by zstorm4** [DivineRPG/DivineRPG#569]
Replicated on 2 different machines. For whatever reason, a player crafting or adding any of the variations of the ender sword cause the game to crash.  Attaching both crash reports. 

Exit crash code -1, launcher reports null string passed.

Attaching both crash reports. 
[kkhonsuu crash.txt](https://github.com/DivineRPG/DivineRPG/files/11326427/kkhonsuu.crash.txt)
[zstorm4 crash.txt](https://github.com/DivineRPG/DivineRPG/files/11326425/zstorm4.crash.txt)

**Comment by NicosaurusRex99** [comment]
You are running a 1.19.3 file in a 1.19.2 environment. this is your issue

**Comment by zstorm4** [comment]
What no? I'm running 1.9.6.8 which curseforge shows as you releasing on March 29th? I do have gecko lib but that's part of another modpack?

![Screenshot_20230429-084238_Hancom Office Editor.jpg](https://user-images.githubusercontent.com/11667457/235306105-efbefcec-353a-46a1-9ce1-ee9ece1a2b2d.jpg)

![Screenshot_20230429-084218_Chrome.jpg](https://user-images.githubusercontent.com/11667457/235306104-5120320b-90b2-4d1c-9b97-47b8cff23ea0.jpg)

**Comment by NicosaurusRex99** [comment]
I based my reply on the log
![image](https://user-images.githubusercontent.com/11579935/235306244-12e4ae84-1bc2-4638-aa8d-ab6e6c76f509.png)
![image](https://user-images.githubusercontent.com/11579935/235306283-ef81fccd-f899-426a-8866-d85f097f36b7.png)

**Comment by NicosaurusRex99** [comment]
this would make sense because the creative tab system changed between those 2 versions

**Comment by zstorm4** [comment]
Ok read both logs. Need to go yell at kkhonsuu b/c he's not deleting jars out of his mods folder apparently. 

Would also like to add, divine rpg wouldn't have even started. You managed to catch user error, but the bug persists across two machines. My install is fine.

**Comment by NicosaurusRex99** [comment]
either way, try the new version we just uploaded. should fix some stuff

**Comment by zstorm4** [comment]
Alright, updated server and client (on my machine) with 1.9.6.8 .jar file, still crashes. Attaching new log (and as a sanity check, triple checked my machine. We are not running a version of divine rpg for 1.19.3) 

User adds or crafts any color ender sword, instant crash.

MC crash message
![image](https://user-images.githubusercontent.com/11667457/235331380-651af97a-bda6-4c77-8cdb-9de4b2b43db4.png)


[crash-2023-04-29_20.34.36-client.txt](https://github.com/DivineRPG/DivineRPG/files/11360410/crash-2023-04-29_20.34.36-client.txt)

**Comment by NicosaurusRex99** [comment]
does this issue occur when running only DivineRPG?

**Comment by TotallyNottJack** [comment]
> does this issue occur when running only DivineRPG?

I can confirm no. I have a bunch of mods and installs and it has been working completely fine until I crafted an Ender Sword. Now it just crashes every time I open the world 

I'm using the most recent 1.19.2 version :)

**Comment by NicosaurusRex99** [comment]
So it requires other mods installed for it to happen?
