### ISSUE TITLE
No defeated message

### ISSUE THREAD

**Issue by krwminer** [DivineRPG/DivineRPG#57]
No defeated message for killing a DRPG mob with a bow.

**Comment by RadioactiveStud** [comment]
Works for me on MP and SMP after I remove the code where it checks for the config option. Bug probably caused by #59.

**Comment by krwminer** [comment]
I will double check when I get home. This was only happening with a bow, (could be other ranged weapons too). It worked fine for killing things with normal mele, (i.e. a sword).

**Comment by RadioactiveStud** [comment]
Well it was working with a bow for me. What bow did you use?

**Comment by krwminer** [comment]
Normal vanilla bow. I will test again with the latest version when I get home and close it if I can't reproduce it anymore.

**Comment by krwminer** [comment]
I tested it in single player and it works. I will re-open if I see it again with more detail.
