### ISSUE TITLE
Vethea not returning items after death

### ISSUE THREAD

**Issue by alphalee65** [DivineRPG/DivineRPG#572]
Im running a server with divinerpg and also keepinventory on. 2 player went into Vethea via the bed and then died. They were returned to world spawn and dont get their items back. One player however went into the dimension with teleport command to player and died but did receive his items back. While in Vethea, items such as charms and backpacks in separate inventory slots are still able to be accessed. Levels are also carried over both worlds If anyone knows whats going on please do help as this is frustrating for us who grinded for the gear thanks.

**Comment by alphalee65** [comment]
After some further testing on the server, we realized that the whoever died in vethea will get the items of the last person who entered vethea but also before that someone also did lose their inventory despite being the one going in and out.

**Comment by NicosaurusRex99** [comment]
we have potentially fixed the wrong person getting the other persons loot in [db0025b](https://github.com/DivineRPG/DivineRPG/commit/db0025b3c65f429bb265c26dd6b10b147e17d0cc)
however the first issue of not getting items after death is going to need more investigation
