### ISSUE TITLE
Game crashing when Ender Sword is in inventory 

### ISSUE THREAD

**Issue by TotallyNottJack** [DivineRPG/DivineRPG#575]
So this has been posted before but for some reason the thread was closed however the issue still remains for myself and hopefully other people as well (hopefully because I really don't want to be the only person with this issue)

Playing latest version on 1.19.2

I have a world that I've had for a while and everything was running smoothly as ever, what is happening though is after farming the ender shards to craft the Ender Sword, my game just crashed. I proceeded to load back into a game but what is happening is my world loads in but immediately crashes. It looks like the it loads up fine but when when spawning the inventory it just breaks. 
Now I believe crafting the item in question is fine as I was able to drag it around after crafting it, it was just when I placed it in my inventory that it crashed. I'm going to load up a creative world and test it to see if it it just the item going into the inventory that is doing it, I'll update the thread with what I find :)

**Comment by NicosaurusRex99** [comment]
I will need logging to find out why. #569 was closed because originally they sent a log with a 1.19.3 file running in a 1.19.2 environment which caused the creative tabs to break, then zstorm closed it after we established this only occurs with other mods installed. if you have more info than previously provided ill happily take a look

**Comment by TotallyNottJack** [comment]
> I will need logging to find out why. #569 was closed because originally they sent a log with a 1.19.3 file running in a 1.19.2 environment which caused the creative tabs to break, then zstorm closed it after we established this only occurs with other mods installed. if you have more info than previously provided ill happily take a look

is it a crash log you need?

**Comment by NicosaurusRex99** [comment]
crash log or a debug.log

**Comment by TotallyNottJack** [comment]
[crash-2023-05-07_04.36.27-server.txt](https://github.com/DivineRPG/DivineRPG/files/11413863/crash-2023-05-07_04.36.27-server.txt)

I believe this will work, let me know if this is right :)

**Comment by NicosaurusRex99** [comment]
Does this still occur without visual workbench? thats the first mod i see thats common between you and the other one that seems like it might do stuff involving crafting.

**Comment by TotallyNottJack** [comment]
> Does this still occur without visual workbench? thats the first mod i see thats common between you and the other one that seems like it might do stuff involving crafting.

I'll set up a world without it and craft the item to find out for you, give me a couple minutes

**Comment by TotallyNottJack** [comment]
> 
Loaded up a new world, took the crafting items in my inventory, putting them in the grid, it was fine, I crafted the ender sword and it was fine, until I put it in my inventory. It froze and crashed immediately. 
[crash report.txt](https://github.com/DivineRPG/DivineRPG/files/11413902/crash.report.txt)

**Comment by NicosaurusRex99** [comment]
Is it possible for you to send a curseforge modpack export? or a modpack name?

**Comment by TotallyNottJack** [comment]
> 

I'll see if I can figure out how to go about doing this, give me a few minutes

**Comment by TotallyNottJack** [comment]
> Is it possible for you to send a curseforge modpack export? or a modpack name?

[test (2).zip](https://github.com/DivineRPG/DivineRPG/files/11413954/test.2.zip)
I THINK I did this correctly..  If not I basically took what was on Better Minecraft Forge Edition 1.19.2 and added some stuff of my own, DivineRPG, Ore Excavation, Mekanism and their add ons and Refined Storage. There is probably some more stuff but I cannot remember them sorry :( I should also mention that I basically made my own profile with these mods so I'm not modifying an existing mod pack

**Comment by NicosaurusRex99** [comment]
the zip isnt exactly what i needed. but ill just go with the better minecraft forge edition tip

**Comment by TotallyNottJack** [comment]
> 

Let me know what you find, sorry the zip isn't what you need. I'm very new at this

**Comment by NicosaurusRex99** [comment]
its ok, youre still being quite helpful

**Comment by NicosaurusRex99** [comment]
So its nothing to do with crafting, its just the item being in the inventory

**Comment by TotallyNottJack** [comment]
> So its nothing to do with crafting, its just the item being in the inventory

That's what I thought, you're actually able to drag it around the screen you just can't place it in your inventory. Is there a mod in that list that's conflicting with it?

**Comment by NicosaurusRex99** [comment]
yes, im going through the log trying to find any hints as to what it could be but not seeing anything obvious so im thinking im going to just start removing mods 1 by 1 based on if i think they would do it and then testing

**Comment by TotallyNottJack** [comment]
> 

Good luck with that, there is a lot of mods to go through

**Comment by NicosaurusRex99** [comment]
Things broke when i started because everything relies on everything in that pack

**Comment by TotallyNottJack** [comment]
How is the investigation going?

**Comment by NicosaurusRex99** [comment]
> How is the investigation going?
> 

Whatever it is. It's not obvious

**Comment by mxnmnm** [comment]
This seems to be an issue with good endings, which is probably related to this crash: https://github.com/0rc1nus/GoodEnding/issues/7

**Comment by TotallyNottJack** [comment]
> This seems to be an issue with good endings, which is probably related to this crash: [0rc1nus/GoodEnding#7](https://github.com/0rc1nus/GoodEnding/issues/7)

I can take a looksie

**Comment by TotallyNottJack** [comment]
So I did some testing and it wasn't just any of the Ender Swords that had this issue, it was also any of the Divine Swords. This was however fixed with the removal of Good Endings. That looks like it has the issue, thankfully this mod doesn't effect anything in my world when I removed it so I can play my save again ^^
