### ISSUE TITLE
Server crashing after Amthirmis Staff was used

### ISSUE THREAD

**Issue by brunopires97** [DivineRPG/DivineRPG#577]
I tried to use the **Amthirmis Staff** in a **skeleton** mob then immediately the **server crashed** and I literally cannot play anymore because the server is not even being able to start (it's **automatically crashing** after I try to turn on again, even if I try to delete the mod from the server) and I don't have any backup.
I saw in the crash report log and the it's returning this error:
`java.lang.NullPointerException: Cannot invoke "net.minecraft.world.damagesource.DamageSource.m_269533_(net.minecraft.tags.TagKey)" because "p_20122_" is null`

I also attached the crash report file here.
The minecraft version I'm using is **1.19.4**.

[crash-2023-05-16_14.29.06-server.txt](https://github.com/DivineRPG/DivineRPG/files/11489148/crash-2023-05-16_14.29.06-server.txt)

**Comment by NicosaurusRex99** [comment]
that refers to this line.
https://github.com/DivineRPG/DivineRPG/blob/1.19.4/src/main/java/divinerpg/entities/projectile/EntityBouncingProjectile.java#LL42C59-L42C59
Thanks for the report

**Comment by NicosaurusRex99** [comment]
This was fixed in 8536bf4 but it is not released yet
