### ISSUE TITLE
Client crash when going to the nether

### ISSUE THREAD

**Issue by Freddy6676** [DivineRPG/DivineRPG#578]
Whenever travelling to and/or from the nether, the client crashes due to a ticking entity error.  The nether is the only dimension that has been traveled to by the player, so I can't be sure that this happens for all dimensions. The crash report for the issue is attached below, and I'd like to thank you in advance for your time in this issue and your stellar work on this mod!
[crash-2023-05-11_21.21.16-client.txt](https://github.com/DivineRPG/DivineRPG/files/11506134/crash-2023-05-11_21.21.16-client.txt)

**Comment by NicosaurusRex99** [comment]
We have had issues with ItShallNotTick. try again without it
