### ISSUE TITLE
spike blocks crashes the game

### ISSUE THREAD

**Issue by monke-dong** [DivineRPG/DivineRPG#579]
whenever the player or a mob steps on a (hot) spike block, on the first damage tic the game crashes

[crash-2023-05-18_21.53.30-client.txt](https://github.com/DivineRPG/DivineRPG/files/11512554/crash-2023-05-18_21.53.30-client.txt)

**Comment by NicosaurusRex99** [comment]
This should be fixed in version 1.10.3
