### ISSUE TITLE
Enthralled Dramcryx hits you

### ISSUE THREAD

**Issue by krwminer** [DivineRPG/DivineRPG#58]
Enthralled Dramcryx will hit you even if one block separates you

**Comment by Eternaldoom** [comment]
Screenshot of what you mean?

**Comment by krwminer** [comment]
The attack range of the Enthralled Dramcryx extends out further than it should.

Spawn an Ethralled Dramcryx in a 5x5 glass cube. Poke a 1 block hole in the middle of one side so it can see you. Walk up to the hole and you will be hit before you run up against the side of glass cube with the hole in it.

The Rotatick attack range also extends out further than a block.

I will get you screenshots still if you would like.

**Comment by Eternaldoom** [comment]
Nah that's ok.
