### ISSUE TITLE
divinerpg:demon_furnace

### ISSUE THREAD

**Issue by ghost** [DivineRPG/DivineRPG#580]
https://github.com/DivineRPG/DivineRPG/issues/549

**Comment by ghost** [comment]
The problem seems to persist
My screenshots might be a little messy
Maybe you can go and see for yourself

**Comment by NicosaurusRex99** [comment]
this doesnt exist in 1.19.4 version 1.10.3
![2023-05-20_14 29 41](https://github.com/DivineRPG/DivineRPG/assets/11579935/586327e1-bd8c-4554-8719-6a9359953b90)

**Comment by NicosaurusRex99** [comment]
although, there is technically an issue that the top 2 spikes are upside down
