### ISSUE TITLE
Usage of deprecated tool tags.

### ISSUE THREAD

**Issue by bconlon1** [DivineRPG/DivineRPG#581]
Forge has marked their tool tags as deprecated and planned for removal as of 1.19.4: https://github.com/MinecraftForge/MinecraftForge/blob/9abfcbc90b3dc5d7f53fa6227676f81742f4b105/src/main/java/net/minecraftforge/common/Tags.java#L454

It is probably not a good idea to continue to add them to the Vanilla tool tags, like in here: https://github.com/DivineRPG/DivineRPG/blob/88dd02419b7fe11979685030db77de15dd38bd2a/src/main/resources/data/minecraft/tags/items/pickaxes.json#L4

I believe this to be the root of an incompatibility bug that's been found between The Aether and DivineRPG, since the issue is happening with items we add to the Vanilla `pickaxes` tag not being found in the tag, and we have since also removed them from the Forge tag after those tags were deprecated. While I am still not 100% sure on this being the root of the issue, since the Forge tag still links back up to the vanilla tag (https://github.com/MinecraftForge/MinecraftForge/blob/1.19.x/src/generated/resources/data/forge/tags/items/tools/pickaxes.json) meaning its weird that there's still an incompatibility here, this should still likely be changed regardless since it will break in the future one way or another.

**Comment by NicosaurusRex99** [comment]
if this is the issue it should be fixed in the next build
bea28f0
if not its something else
