### ISSUE TITLE
[Feature Request] Better Combat support

### ISSUE THREAD

**Issue by MrKashew** [DivineRPG/DivineRPG#588]
A small amount seem to be parsed by better combat
Would be quite exciting to see all these unique weapons function with integration to this mod, most can use sword presets etc im sure
[If you are interested](https://github.com/ZsoltMolnarrr/BetterCombat#-integrate-your-mod)

**Comment by NicosaurusRex99** [comment]
ive added this to our todo, im going to close this issue report but just know its something im planning on looking into
