### ISSUE TITLE
Divine RPG X Oh The Biomes We Go! Combination

### ISSUE THREAD

**Issue by BorisBircan** [DivineRPG/DivineRPG#590]
Hey, I just download All The Mods 8 modpack and added Divine RPG into it. I didnt see any Divine mobs around yet. I couldnt find anything about spawn configs on both mods.. 
So I wanted to ask you guys, Is there any way to combine these mod (or modpack) with DivineRPG mod correctly..
Thank you!..

**Comment by NicosaurusRex99** [comment]
ive added this to our todo so im going to close this issue. just know that it is something we are willing to look into
