### ISSUE TITLE
mob jack o man appears too often in my world

### ISSUE THREAD

**Issue by Plauer64** [DivineRPG/DivineRPG#593]
mob jack o man appears too often in my world 
![image](https://github.com/DivineRPG/DivineRPG/assets/139633965/52fd763e-4f5c-4977-98d8-353429e3defa)

**Comment by Plauer64** [comment]
check minimap

**Comment by NicosaurusRex99** [comment]
we dont support 1.12.2 anymore. we dont have a dev team large enough to do so
