### ISSUE TITLE
Hell's pig causing crash on server side

### ISSUE THREAD

**Issue by Ookamiko** [DivineRPG/DivineRPG#596]
Hello,

Since I installed DivineRPG mod on my server, each time a Hell's Pig receive damage from player or other source, my server crash. It's a bit of an issue 'cause now, none of my player can go to the nether to be sure to not crash the server. I saw that the bug existed on an previous version of this mod and was normally fixed so is there something that I done wrong ?
You can find the crash report here :
[crash-2023-07-17_09.01.46-server.txt](https://github.com/DivineRPG/DivineRPG/files/12142246/crash-2023-07-17_09.01.46-server.txt)

Thanks for the mod by the way ;-)

Best Regards

**Comment by NicosaurusRex99** [comment]
Try run it without Canary

**Comment by Ookamiko** [comment]
I tried without canary mod but still the same result
[Uploading crash-2023-07-29_07.48.45-server.txt…]()

**Comment by NicosaurusRex99** [comment]
dl link doesnt work

**Comment by Ookamiko** [comment]
Sorry, here a new link for the crash report
[crash-2023-07-29_07.48.45-server.txt](https://github.com/DivineRPG/DivineRPG/files/12212068/crash-2023-07-29_07.48.45-server.txt)

**Comment by NicosaurusRex99** [comment]
We have had alot of mods like rubidium and other performance tweaking mods cause issues.

**Comment by Ookamiko** [comment]
Is there something I can attempt to prevent this bug for occuring ?

**Comment by velocityraptor-real** [comment]
you can disable the mobs' spawns with a mob spawning controller mod. or you can wait until next update, where we have attempted to fix this

**Comment by NicosaurusRex99** [comment]
seems fixed
