### ISSUE TITLE
Armor colors not working

### ISSUE THREAD

**Issue by MuyBano** [DivineRPG/DivineRPG#598]
None of the armor colors work.  Not for ender armor or rupee armor.  On version 1.10.5 for Minecraft version 1.20.1

![image](https://github.com/DivineRPG/DivineRPG/assets/70288275/d7199c2a-ac49-409c-8e8a-78220f9b8c53)

**Comment by NicosaurusRex99** [comment]
Fixed in 51855ca. Will be in the next update
