### ISSUE TITLE
Everything in a Present Box vanishes on MP after logoff

### ISSUE THREAD

**Issue by krwminer** [DivineRPG/DivineRPG#60]
When you put something in a Present Box, log off and join the server again, the Present Box is empty.

**Comment by Eternaldoom** [comment]
Umm... the present box hasn't actually been added yet.

**Comment by krwminer** [comment]
I have crafted the blue and red one so far. I assume all colors are craftable. It looks like it is working, (placeable, open/close, move items in and out), so I thought it was completed. (Until of course it lost items after logging off... :O)

**Comment by Eternaldoom** [comment]
Whaaaaa? What is the actual name of the block?

**Comment by krwminer** [comment]
"Present Box"

It looks like a wrapped Christmas present.

**Comment by krwminer** [comment]
lol. It looks like it is from Chisel. My mistake. Sorry to scare you. ;)

**Comment by Eternaldoom** [comment]
No problem. DRPG actually has a present box too, it just hasn't been added yet.
