### ISSUE TITLE
Compatible with biome mods

### ISSUE THREAD

**Issue by VadimFlex** [DivineRPG/DivineRPG#600]
With the Extrabiomes xl mod, there were problems with spawning mobs. In the tundra biome , in addition to mobs of cold biomes , mobs from the desert will spawn .Version 1.4.1.5. minecraft version 1.7.10.
![2023-08-09_00 01 46](https://github.com/DivineRPG/DivineRPG/assets/132595752/51fbd32c-166e-4f5a-8a04-9d4a49ee1c7e)
![2023-08-09_00 01 38](https://github.com/DivineRPG/DivineRPG/assets/132595752/28496052-b5de-4b2b-8120-f6c6784cd91a)

**Comment by VadimFlex** [comment]
Do you no longer support this version?

**Comment by NicosaurusRex99** [comment]
We support 1.19.2 and 1.20.1 only because resources are limited
