### ISSUE TITLE
How to properly update/fix ru_ru.json localization file

### ISSUE THREAD

**Issue by Igneaalis** [DivineRPG/DivineRPG#602]
I want to contribute and fix ru_ru.json language a little bit. But there are a lot of branches for different versions. I don't think I should create PR for every version. What's the right way to change ru_ru.json? I would PR to the 1.20 version but I play in the 1.19.2 version and I want these changes to be applied for my version too. I changed this already locally but it will be nice if I could help everyone else.

I want to fix this line:
\- 571: "item.divinerpg.raw_realmite": "Необработанный арлемит",
\+ 571: "item.divinerpg.raw_realmite": "Необработанный реалмит",

**Comment by NicosaurusRex99** [comment]
for personal use a resource pack is probably the best option however if @Locomenmod says this change is good, im happy to add it to 1.20.1

**Comment by Locomenmod** [comment]
Within a week I will update the Russian localization with all the changes that occurred while I was away.
Everything will be fixed in the new version, as for the old version, if @NicosaurusRex99 plans to support them as well, then I will be happy to update it as well.

**Comment by NicosaurusRex99** [comment]
at the moment we are supporting 1.19.2 and 1.20.1 but primarily 1.20.1.
Essentially 1.19.2 is in a stage where if major bugs appear we will fix them but 1.20.1 will get both fixes and new content
