### ISSUE TITLE
Updated Server to lastest update now Server wont load

### ISSUE THREAD

**Issue by logixcraft** [DivineRPG/DivineRPG#604]
[debug-1.log.gz](https://github.com/DivineRPG/DivineRPG/files/12504516/debug-1.log.gz)
[2023-09-02-1.log.gz](https://github.com/DivineRPG/DivineRPG/files/12504517/2023-09-02-1.log.gz)

I updated the server to the latest version now it wont load.

**Comment by NicosaurusRex99** [comment]
Send me your level.dat and ill resolve this

**Comment by NicosaurusRex99** [comment]
A Possible fix is using the optimize button on your world but if that doesnt work try the next thing as follows

You can resolve this issue by deleting this file. You will need [NBT Explorer](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-tools/1262665-nbtexplorer-nbt-editor-for-windows-and-mac) to do this.  level.dat/worldgensettings/dimensions/divinerpg:iceika/generator/biome:source.

Please ensure before doing this that you have backed up your files
