### ISSUE TITLE
1.10.6.1 Crash and Nether Spawns

### ISSUE THREAD

**Issue by Malefactor2000** [DivineRPG/DivineRPG#606]
Replaced 1.10.5 with 1.10.6.1 and it broke the game. Wouldn't start in safe mode (due to mods etc) and wouldn't launch game at all. Am very much looking forward to an update (as this one stated in fixes) includes Nether Spawn update as currently I am unable to progress due to Ghasts etc not spawning.

**Comment by NicosaurusRex99** [comment]
Probably the same as #604 
Please try the fix mentioned there
