### ISSUE TITLE
Server wont boot after updating DivineRPG 

### ISSUE THREAD

**Issue by logixcraft** [DivineRPG/DivineRPG#607]
I wanted to rebuild my server to make sure It was a real issue and not something I fucked up.  Still crashing after updating

log.log
debug.log
level.dat

are all attached.

[report.zip](https://github.com/DivineRPG/DivineRPG/files/12552022/report.zip)

**Comment by NicosaurusRex99** [comment]
[use_this_leveldat.zip](https://github.com/DivineRPG/DivineRPG/files/12552036/use_this_leveldat.zip)
use this level.dat

**Comment by logixcraft** [comment]
That fixed it thank you very much for the quick turnaround.
