### ISSUE TITLE
[1.20.1] Incomplete world check in the Vethea inventory saving event

### ISSUE THREAD

**Issue by lMozGl** [DivineRPG/DivineRPG#609]
ForgeVersion: 47.2.1
Core: Mohist

When teleporting between other worlds, it saves and returns inventory, which results in duplicate inventory if you drop an item on the ground. Since it considers any world to be the main(overworld)

**Comment by NicosaurusRex99** [comment]
What version of divine RPG are you using?

**Comment by lMozGl** [comment]
DivineRPG-1.10.6.1

**Comment by NicosaurusRex99** [comment]
A temp fix i would suggest is going into the config file and setting saferVetheanInventory to true
