### ISSUE TITLE
Spawn mobs

### ISSUE THREAD

**Issue by Magomed2213** [DivineRPG/DivineRPG#611]
Mobs from the mod appear very rarely, made a special room at a height of 11, with a little light still did not help, appear only mobs from the vanilla version and rarely from the mod 
Game version 1.20.1
Forge version 47.1.43
Mod version 1.10.6.1

I apologize for my English I translate through a translator

![Снимок экрана (3)](https://github.com/DivineRPG/DivineRPG/assets/148139116/0593e4b7-1979-4bf3-a700-147d41f2908e)

**Comment by NicosaurusRex99** [comment]
Dark mobs spawn mostly in deepslate now
