### ISSUE TITLE
Questions about the mod in version 1.16.5

### ISSUE THREAD

**Issue by GuicarlosB** [DivineRPG/DivineRPG#612]
I'm playing the mod in version 1.16.5, it changed a lot from 1.12.2, and I wanted to know how I can make an even bigger spawn in Enthralled Dramcryx mod Divine RPG?

**Comment by NicosaurusRex99** [comment]
You need to make a custom datapack that tweaks spawnrates.
Datapacks found here [https://github.com/DivineRPG/DivineRPG/tree/1.16x/src/main/resources/data](url)
Datapack guide found here [https://minecraft.fandom.com/wiki/Tutorials/Creating_a_data_pack](url)
