### ISSUE TITLE
1.20.2 | Problems with Arcananium handler

### ISSUE THREAD

**Issue by Kvakochka** [DivineRPG/DivineRPG#614]
When you put raw arcanium and the collector into the Arcane Extractor, it is thrown out of the extractor and the arcanium with the collector inside disappears
https://youtu.be/37ssQRDViHk

**Comment by velocityraptor-real** [comment]
Cannot reproduce bug in latest version. you might be using an older version of divinerpg. also I recommend using a **Neoforge 1.20.1** installation. 1.20.2 is not working well aswell as standard forge
