### ISSUE TITLE
 DRPG in the_ End causes a crash

### ISSUE THREAD

**Issue by Mnibr** [DivineRPG/DivineRPG#615]
DRPG caused a crash in the final destination
When I save the archive at the end, it causes a crash (unknown reason)
This is my error report
[错误报告-2023-11-29_0.32.55.zip](https://github.com/DivineRPG/DivineRPG/files/13490728/-2023-11-29_0.32.55.zip)

**Comment by Mnibr** [comment]
Due to language reading issues in Windows, this error report may have some impact on reading. I hope this will not affect your ability to fix bugs

**Comment by Mnibr** [comment]
By the way, the Forge version is 47.2.0, and the Minecraft version is 1.20.1

**Comment by NicosaurusRex99** [comment]
I believe that this is a known epic fight incompatability
