### ISSUE TITLE
1.20.1 Possible conflict with Nature's Aura

### ISSUE THREAD

**Issue by Gamerbolts** [DivineRPG/DivineRPG#616]
Hello, I have a heavily modded version of ATM9. The latest update for DivineRPG caused crashes when I tried loading into my world. It looks like it might be conflicting with Ellpecks Nature's Aura. Here is my log and crash log. Let me know if it looks like it is on their side and if so I'll post this to their github. Thanks!

[crash-2023-12-03_10.43.52-server.txt](https://github.com/DivineRPG/DivineRPG/files/13539594/crash-2023-12-03_10.43.52-server.txt)
[latest.log](https://github.com/DivineRPG/DivineRPG/files/13539595/latest.log)

**Comment by velocityraptor-real** [comment]
This issue is something I observed aswell and it seems to ba a fault of the DivineRPG soultrap chunk capability. Will be fixed soon.

**Comment by Gamerbolts** [comment]
Will wait for the update. Thanks so much!

**Comment by velocityraptor-real** [comment]
Fixed with update 1.10.7.1
