### ISSUE TITLE
Not starting in a modpack

### ISSUE THREAD

**Issue by AnChedraui** [DivineRPG/DivineRPG#618]
Not sure of where exactly is the issue, but wanted to share it.

Minecraft 1.20.1

Forge loader

[https://pastebin.com/hUPeYZfB](url)

**Comment by NicosaurusRex99** [comment]
im going to suggest this is an issue with dungeonsartifacts. Specifically here `has been registered twice, using the names duneons:blacksmith and dungeonsartifacts:anvil_poi.`

> Caused by: java.lang.IllegalArgumentException: The object PoiType[matchingStates=[Block{minecraft:anvil}[facing=east], Block{minecraft:anvil}[facing=north], Block{minecraft:anvil}[facing=west], Block{minecraft:anvil}[facing=south]], maxTickets=1, validRange=1]{763c4fd5} has been registered twice, using the names duneons:blacksmith and dungeonsartifacts:anvil_poi. (Other object at this id is PoiType[matchingStates=[Block{minecraft:anvil}[facing=east], Block{minecraft:anvil}[facing=north], Block{minecraft:anvil}[facing=west], Block{minecraft:anvil}[facing=south]], maxTickets=1, validRange=1]{bf68ea5})
> 		at TRANSFORMER/forge@47.2.0/net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:429)
> 		at TRANSFORMER/forge@47.2.0/net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:394)
> 		at TRANSFORMER/forge@47.2.0/net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:130)
> 		at TRANSFORMER/forge@47.2.0/net.minecraftforge.registries.RegisterEvent.register(RegisterEvent.java:59)
> 		at TRANSFORMER/forge@47.2.0/net.minecraftforge.registries.DeferredRegister.addEntries(DeferredRegister.java:386)
> 		at TRANSFORMER/forge@47.2.0/net.minecraftforge.registries.DeferredRegister$EventDispatcher.handleEvent(DeferredRegister.java:328)
> 		at TRANSFORMER/forge@47.2.0/net.minecraftforge.registries.__EventDispatcher_handleEvent_RegisterEvent.invoke(.dynamic)
> 		at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
> 		at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
> 		at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
> 		at LAYER PLUGIN/javafmllanguage@1.20.1-47.2.0/net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:107)
> 		... 34 more
