### ISSUE TITLE
The Eyes Blindness

### ISSUE THREAD

**Issue by krwminer** [DivineRPG/DivineRPG#62]
The Blindness III you get from The Eye starts at 3 seconds and does not tick down or ever go away till you log off the server. Once you logoff/on again it starts ticking down to zero and the Blindness III goes away.

**Comment by Eternaldoom** [comment]
Does it go away if you kill the eye?

**Comment by krwminer** [comment]
I will test this one for more details. I might have missed killing an Eye when several of them spawned.

Are you suppose to be blind until every Eye that you have looked at or attacked is dead? What if the Eye despawns?

As I said, I will do more testing when I get home.

**Comment by krwminer** [comment]
O.K. Once you attack and Eye or it sees you you have to kill that Eye before the blindness wears off.

I assume that is how it is suppose to work so I will close this. I must have missed killing an Eye before.
