### ISSUE TITLE
[1.20.1] Artifacts + DivineRPG duping items that are in artifact slots.

### ISSUE THREAD

**Issue by AXYEPO** [DivineRPG/DivineRPG#623]
Playing on version 1.20.1 I found the problem of duping items that are in slots for artifacts when you enter the portal after defeating the dragon. Can this be fixed?

**Comment by AXYEPO** [comment]
The latest version without this bug is "DivineRPG-1.10.6.1.jar". Everything above this version has this bug.

**Comment by TonimatasDEV** [comment]
Same problem with 1.10.7.2

**Comment by NicosaurusRex99** [comment]
i wouldnt have expected it to be fixed in 1.10.7.2. I will mark it fixed when the issue is fixed

**Comment by tixomirof** [comment]
Same issue happens if you enable gamerule keepInventory true and die

**Comment by vjperez724** [comment]
Just a warning to anyone using a backpack mod that goes in a curios slot.  Duplicating the backpack will delete all items in the backpack, at least with Sophisticated Backpacks.  I haven't tried other mods.

**Comment by Greenjiao** [comment]
hope fixed，thanks contributor

**Comment by velocityraptor-real** [comment]
should be fixed in latest version: DivineRPG 1.10.7.4.
