### ISSUE TITLE
game crashed idk y

### ISSUE THREAD

**Issue by nshiva123** [DivineRPG/DivineRPG#624]
when am using this modpack https://www.curseforge.com/minecraft/modpacks/lookin-creat-ive
[crash-2023-12-29_21.20.08-fml.txt](https://github.com/DivineRPG/DivineRPG/files/13794712/crash-2023-12-29_21.20.08-fml.txt)

**Comment by NicosaurusRex99** [comment]
This is because you seem to be using a 1.19.2 mod in a 1.19.1 modpack.
