### ISSUE TITLE
DivineRPG mobs in custom caves

### ISSUE THREAD

**Issue by uhloin** [DivineRPG/DivineRPG#625]
The Eye, Dramcryx and other DRPG cave monsters are not suitable for cave biomes from other mods. How about make some whitelist/blacklist for spawn such mobs in the custom biomes? Or exclude them only from non-vanilla cave sub-biomes only.

Surface biomes of mods are good for DRPG:
Biomes o Plenty, Oh The Biomes You Go, Regions Unexplored, Endless Biomes

Biomes/areas of mods are bad for DRPG:
Alex's Caves, Deeper and Darker, Kobolds, Galosphere, Ars Nouveau (archwood forest)

**Comment by AndreyBobrovski** [comment]
подтверждаю, играю на версии 1.16.5 в Create Above and Betond с добавлением Divine RPG. Абсолютно нет спавна пещерных мобов, королевских крабов.

**Comment by l1lsk9ty** [comment]
Такая же проблема, делаю ферму для мобов, вообще никого не появляется, хотя высота мира подходит (на 6 высоте), играю на версии 1.20.1. Разработчики, прошу решить проблему

**Comment by NicosaurusRex99** [comment]
> The Eye, Dramcryx and other DRPG cave monsters are not suitable for cave biomes from other mods. How about make some whitelist/blacklist for spawn such mobs in the custom biomes? Or exclude them only from non-vanilla cave sub-biomes only.

This exists. This is why minecraft converted to [datapacks](https://minecraft.wiki/w/Tutorials/Creating_a_data_pack)
