### ISSUE TITLE
WorldGenSettings: No key preset in MapLike

### ISSUE THREAD

**Issue by Waterhorse928** [DivineRPG/DivineRPG#628]
After an update to a custom modpack, I started getting world gen errors I think in relation to DivineRPG. This only happens with old worlds before the update, new ones work fine.
[latest.log](https://github.com/DivineRPG/DivineRPG/files/13951975/latest.log)
Here's the modlist
![image](https://github.com/DivineRPG/DivineRPG/assets/72754883/d59be7d0-d01e-4c31-93ff-481dc19ca97d)

**Comment by Waterhorse928** [comment]
oooh interesting, rolling back to 1.10.6.1 works just fine. I'll just stay there for now

**Comment by NicosaurusRex99** [comment]
Refer to #604 Its matches the description of the issue
