### ISSUE TITLE
What's about Kitra? CAn I summon and fight this boss?

### ISSUE THREAD

**Issue by Zimber303** [DivineRPG/DivineRPG#629]
It is not an issue, it is a question

**Comment by Zimber303** [comment]
And can I ask more questons, is the Cauldron fish and Mamoth are spawnable?

**Comment by NicosaurusRex99** [comment]
Kill 100 protected mobs (usually fish) in the boneyard biome in Iceland. Magic damage only

**Comment by Zimber303** [comment]
Protected mobs? And what's about Cauldron fish and Mamoth
