### ISSUE TITLE
Issue of mob spawning

### ISSUE THREAD

**Issue by Bagumchuk** [DivineRPG/DivineRPG#630]
Hi! I was playing on the 1.12.1 version, where it was possible to create a DRPG mob cave at the height of 13-16 blocks, but now it is not working even on the height of  "-45". Can you please help with new approximate heights of DRPG mobs spawns, or if this method was nerfed, can you explain new rules of spawn of mobs?

**Comment by NicosaurusRex99** [comment]
db2d36f
 We have since buffed the spawn rates but that version isnt out. basically the same spawn rules except heights are now more in deepslate levels now
