### ISSUE TITLE
Teleportation crystal light levels zero

### ISSUE THREAD

**Issue by Blueneko8648** [DivineRPG/DivineRPG#633]
Using the latest release of 1.16.5, then teleporting using the teleportation crystal for spawn and the teleporter for a custom location (64 use). The client light will become zero for all light sources from blocks modded or not. Use for a second time fixes the light. This also means that mobs spawn at those locations.

**Comment by Blueneko8648** [comment]
The same thing goes for the teleportation star

**Comment by NicosaurusRex99** [comment]
This just sounds like a client sided issue because light levels shouldnt change from an item (unless you have dynamic lighting). Does the issue go away when you save and quit then rejoin the world

**Comment by Blueneko8648** [comment]
Relogging fixes it the first time but the second use turns all signs, chests, and heads back, after 2mins idle, it turns several more blocks turn dark like beds the book for enchantment table, a single chunk, and the client light is still zero.
![17071984874916278185479121370588](https://github.com/DivineRPG/DivineRPG/assets/158619861/bd93ec91-ba60-4895-a11d-c9245f8e410a)

**Comment by Blueneko8648** [comment]
The server side gives a light value but mobs still spawned even right next to a light source like a sea lanterns and lamps
