### ISSUE TITLE
Game items causing game crashes and unknown text errors

### ISSUE THREAD

**Issue by catmoon233** [DivineRPG/DivineRPG#634]
[crash-2024-02-06_13.16.14-client.txt](https://github.com/DivineRPG/DivineRPG/files/14241535/crash-2024-02-06_13.16.14-client.txt)
Based on the log files, it can be determined that the Bedrock Sword item caused an unknown text error, and I also saw error messages for the EpicFit mod. Later, when I moved the mouse over the item in that mod, the game crashed

**Comment by NicosaurusRex99** [comment]
This is an incompatability with epic fight same as #631
