### ISSUE TITLE
Possible conflict with Aether Mod

### ISSUE THREAD

**Issue by Fxkz** [DivineRPG/DivineRPG#636]
I want to add Divine RPG to my modpack, but am running into the problem that Minecraft is not responding. Through the method of disabling mods I realized that this is due to a conflict with the Aether mod, however there is no error in the logs: 
[18:46:49] [modloading-worker-0/INFO] [di.DivineRPG/]: [DivineRPG] Registered events
[18:46:49] [modloading-worker-0/INFO] [di.DivineRPG/]: [DivineRPG] Registered networking
After then Minecraft then hangs with a white screen before loading and does not respond
Are the mods really incompatible or is there some solution to this problem?

UPD: Version 1.9.6.9 works fine, the problem is probably in 1.9.6.11

**Comment by NicosaurusRex99** [comment]
This is likely related to #604

**Comment by Fxkz** [comment]
As I understand it, the level.dat file should be in the game world file, but my problem is that I can't log into the game itself to at least create that world.

**Comment by NicosaurusRex99** [comment]
i see, can you send a full log file

**Comment by Fxkz** [comment]
I reinstalled REI, added some libraries - some of that solved the problem. You can close the ticket
