### ISSUE TITLE
Entities spawn like crazy in twilight dimensions

### ISSUE THREAD

**Issue by Rick-300** [DivineRPG/DivineRPG#637]
Basically, there is a spot in the Eden dimension of my world flooded with laggy glinthops. All they do is be persistent and basically unkillable due to their behavior.
As angered as I am right now, I kindly request a fix for this specific issue. Maybe a despawn script?

**Comment by Rick-300** [comment]
![2024-03-02_18 29 41](https://github.com/DivineRPG/DivineRPG/assets/157910615/4f558559-2471-415b-946b-dd29ba39f469)
And here's a screenshot of the problem at hand, F3 Screen included

**Comment by Rick-300** [comment]
Oops, accidentally closed the issue

**Comment by NicosaurusRex99** [comment]
weird that its only glinthop, thanks for the report. can you send a log please

**Comment by Rick-300** [comment]
Unfortunately, the damage has already been done. In other words, the glinthops have already been spawned in that spot. I don't think the log will do anything to help the issue or identify it.
