### ISSUE TITLE
Inferno Bow arrow crashes the Game when I hit a Entity

### ISSUE THREAD

**Issue by Mhssans** [DivineRPG/DivineRPG#638]
So on my gameplay I craft a inferno bow, which I try to test it out on a zombie, but for some reasons the game freezes and crashes

**Comment by teily1337** [comment]
[crash-2024-03-27_12.52.19-server.txt](https://github.com/DivineRPG/DivineRPG/files/14771516/crash-2024-03-27_12.52.19-server.txt)

Same crash

**Comment by velocityraptor-real** [comment]
you seem to be using a slightly older version. cannot reproduce bug in lates version: DivineRPG 1.10.7.4
