### ISSUE TITLE
DivineRPG-1.10.7.3 MC 1.20.1 inventory is missing or out of sync with different dimensions 

### ISSUE THREAD

**Issue by Lindsaydoodle** [DivineRPG/DivineRPG#639]
It was tested on both the Mohist - 1.20.1-598 core and the forge server core 47.2.0

How I tested and over which worlds I have a journeymap and essentials mod and there are warps there and there:
- journeymap (the procedure of actions):
1. I put an end to overworld
2. I go to hell and put a period there
3. In overworld, I take 1 block of land and enter hell in the 1st slot
4. In hell, I move the block to the 9th slot and teleport to overworld and see that the block is moving to the 1st slot

If you die in hell with the loss of inventory and in the usual way get resources and click on any item in the inventory to clean up the entire inventory

Absolutely the same happens if you use essentials

modlist:
DivineRPG 
Journeymap

Initially I thought it was journeymap, but after going through the mods, it turned out that it was DivineRPG(

I did not want to write initially because I thought that it would not interfere, but when the inventory was cleaned 2 times it became super not pleasant (

there is also a DivineRPG-compatibility on curseforge, but it has the same bug

**Comment by NicosaurusRex99** [comment]
It wont get your items back but if you go into the config file and change saferVetheanInventory to true this should fix it (will change the way you use the nightmare bed but all info is in game)

**Comment by Lindsaydoodle** [comment]
work!
