### ISSUE TITLE
The Arcane extractor removes items when you try to craft in it

### ISSUE THREAD

**Issue by BazZziliuS** [DivineRPG/DivineRPG#640]
DivineRPG-1.10.7.3

![image](https://github.com/DivineRPG/DivineRPG/assets/18011884/8eb87c88-6f6c-4080-bf6a-405117ef7400)

The Arcane extractor removes items when you try to craft in it

The problem occurs on a server with the Mohist core

**Comment by velocityraptor-real** [comment]
Works as intended in a standard Neoforge 1.20.1 installation. We sadly do not support Mohist mod conflicts.
