### ISSUE TITLE
JEI breaks because of bedrock sword. MC 1.20.1

### ISSUE THREAD

**Issue by ItzzS4dJ1** [DivineRPG/DivineRPG#644]
![image](https://github.com/DivineRPG/DivineRPG/assets/145474834/e4126ffc-015b-4855-9546-69de9963e2df)
Bedrock sword breaks the JEI tooltip and I cant check recipes of different items because of that.
![image](https://github.com/DivineRPG/DivineRPG/assets/145474834/1718d40e-1c72-476a-9d1d-3357c719d2c0)

**Comment by Zwey6754** [comment]
if you have Epic Fight, then delete it, it's a conflict between these mods
