### ISSUE TITLE
1.20.1 (DivineRPG 1.10.6.1) | infusion table duping all crafts

### ISSUE THREAD

**Issue by 1lore** [DivineRPG/DivineRPG#647]
when you crafting anything in infusion table you have to dupe all crafts when placing ingredients and removing one of them, then taking an crafted item.
works with every single craft in that tile
## meta :

`'divinerpg:infusion_table'`

## Steps to reproduce

1.
![image](https://github.com/Gravity-Craft/Supports/assets/157323835/661efb75-1e1e-40c3-8e5f-8805c2e44f33)
2.
![image](https://github.com/Gravity-Craft/Supports/assets/157323835/67b8ec23-9e0c-42a4-a116-03627f6b809b)
3.
![image](https://github.com/Gravity-Craft/Supports/assets/157323835/08902bd3-a34e-42b0-989d-876bc9a4a245)
4.
![image](https://github.com/DivineRPG/DivineRPG/assets/157323835/29edfc7d-b541-4eee-8ef9-456b6078bc24)
(not visual dupe)

**Comment by velocityraptor-real** [comment]
fixed in latest version
