### ISSUE TITLE
[Suggestion] Incorrect/Misleading Tooltips

### ISSUE THREAD

**Issue by Afrocntrik** [DivineRPG/DivineRPG#648]
1. First line in tooltip states `4.0 Ranged Damage`, however last line has `+7 Attack Damage` but it does do **+4 Damage**
![image](https://github.com/DivineRPG/DivineRPG/assets/11052983/6467c9be-8128-4a5a-9a78-02aca91c34c7)
[RangedWeaponAPI](https://github.com/FabricExtras/RangedWeaponAPI) licensed under MIT for Fabric has a customizable system for ranged weaponry additionally in-depth documentation example of vanilla changes:
![ezgif-3-627d7b8ced](https://github.com/DivineRPG/DivineRPG/assets/11052983/94ce110e-741c-4666-a491-2f80b659a78c)

2. Why is it _'Infinite Uses'_? [Unbreakable](https://minecraft.fandom.com/wiki/Tutorials/Command_NBT_tags) is a tag already in the game
![image](https://github.com/DivineRPG/DivineRPG/assets/11052983/04349781-de8a-44f6-9466-f948c38c91b4)
3. _Example below_ for **Arcana** and **Ammo** to be in more clear & in line with Vanilla Tooltips
![ezgif-4-a5f95fcdb5](https://github.com/DivineRPG/DivineRPG/assets/11052983/5dd15ac4-46b9-4999-bdf5-4c8b1c7f1b27)

**Comment by Afrocntrik** [comment]
4. Additional _Example below_ for **Armor** and **Full Set Bonus** Vanilla Inspired (utilized [Formatting codes](https://minecraft.fandom.com/wiki/Formatting_codes) and [`en_us.json`](https://gist.github.com/Afrocntrik/6e64e2578ed2ab34bacd6e1005aebc72) edits)
![ezgif-7-4cbf800d87](https://github.com/DivineRPG/DivineRPG/assets/11052983/0c1e44c5-5435-4b21-a000-092648a793bb)
My linked [`en_us.json`](https://gist.github.com/Afrocntrik/6e64e2578ed2ab34bacd6e1005aebc72) does have some ideas for tooltip restructure but unfortunately some of them do not work with just formatting codes due to the `%s` ignoring the format so that is why I am asking for this fix to be considered I did my best to provide examples as well as

**Comment by NicosaurusRex99** [comment]
1. is ranged the other is melee. 
1b. We are neoforge not fabric, additionally we dont wish to use required libraries as additional downloads can confuse users. 
2. This was more of a legacy thing that we should probably address, 
3. could look into that
4. another thing we could look into

Thanks for the feedback

**Comment by Afrocntrik** [comment]
My apologies @NicosaurusRex99 I was not implying to utilize a library, I do understand not wanting to confuse users I was suggesting implementing a similar system using their API as an inspiration. I understand **Attack Damage** is a vanilla attribute which happens to be melee yet items such as the _Eden Blitz, Wildwood Blitz, Mortum Blitz etc._ have listed 
`When in Off Hand: +Attack Damage` resulting in holding the weapon in my off hand and punching causing me to do
**+14 Attack Damage** with my fist, that was intended?
![2024-05-09_01 33 56](https://github.com/DivineRPG/DivineRPG/assets/11052983/0acc41d5-3c8c-45c2-90e0-a062b36371f1)

**Comment by NicosaurusRex99** [comment]
The offhand stat boost is unintentional. As for the bow stuff I believe pegas has been working on that for the next update

**Comment by NicosaurusRex99** [comment]
should be fixed now
