### ISSUE TITLE
Mobs are not spawning in DivineRPG dimensions.

### ISSUE THREAD

**Issue by Gavvit** [DivineRPG/DivineRPG#652]
I was playing with friends, until we realized that when we were in the Eden dimension, the mobs with the drops necessary to enter the next dimension were not spawning, only dragons from the Ice and Fire Mod. But in the Iceika dimension, peaceful NPCs and mobs appeared that appear through spawners only, these were the gele archers. I tried changing the IDs of the mod's dimensions, however, the mobs continued not to spawn. Among the dimension mods we are using are DivineRPG and Twilight Forest. Can anyone help?

**Comment by velocityraptor-real** [comment]
You most likely have messed up spawn rates by another mod. Which version of DivineRPG are you using?

**Comment by Gavvit** [comment]
> Você provavelmente atrapalhou as taxas de spawn com outro mod. Qual versão do DivineRPG você está usando?

DivineRPG 1.7.1
