### ISSUE TITLE
[1.19.2] Armor Perks not working/reducing damage/very rare mob spawns

### ISSUE THREAD

**Issue by Spookygalore** [DivineRPG/DivineRPG#653]
- Frozen Armor not freezing mobs within 6 blocks as stated in the full perks
- Rupee Armor not reducing damage (compared using frozen vs rupee armor, ender cube damage both does 1 heart of damage when wearing both armor
- Full set arlemite armor not reducing ranged damage and wearing the full set also reduces the damage of bow down extremely (vanilla Power V bow takes 4-5 to kill a single zombie
- Scorching sword impossible to create as scorcher not spawning in the nether
- Cyclops not spawning and or very rare spawning in overworld
- Traders not spawning in overworld 
- Armor not protecting/damaging reducing despite being very expensive (Watcher boss does 7 hearts of damage while wearing full enchanted protection IV elite realmite armor)

**Comment by velocityraptor-real** [comment]
DivineRPG for mc 1.19.2 is currently not being supported as our dev team is to small to support many versions. Most of these issues are fixed for DivineRPG 1.20.1, but I will check if any of those persist even in the most recent version.

**Comment by Spookygalore** [comment]
I see, I was actually trying to load 1.20.1 but it crashed when starting up, what forge version supports 1.20.1?
