### ISSUE TITLE
[1.20.1] Overworld Rare/small spawning rate 

### ISSUE THREAD

**Issue by Spookygalore** [DivineRPG/DivineRPG#654]
It takes ages to find even 1 or 2 cyclops along with crabs and king crabs however there was many glacons I ran into so I was not sure if the spawn rate was nerfed or not. I compared this with 1.16.2 and 1.12.2 and the spawn rate was very high with both cyclops and crabs, they would even spawn in counts of 3 or 2 and would see them very often. 1.20.1 would spawn only 1 or sometimes 2 but very randomly after traveling a hundreds of blocks/chunks some more often then not but still very rare

**Comment by velocityraptor-real** [comment]
you find more spawns by waiting near a spawnable area than travelling, because the surface gets more time in which it can attempt spawning an entity. also in my experience both crabs and cyclops are quite common.
