### ISSUE TITLE
[1.20.1] Armor breaking very fast against DivineRPG mobs

### ISSUE THREAD

**Issue by Spookygalore** [DivineRPG/DivineRPG#657]
I know the DivineRPG mobs are supposed to be very strong but the armor such as Eden, wildwood, Appalachia etc armor seems to breaks very quickly even with unbreaking lll. It’s pretty odd considering that the grind for this armor takes a very long time. Unless that’s how the armor is balanced, but a majority of the time I find my armor breaking very quickly when fighting DivineRPG mobs in the dimensions

**Comment by NicosaurusRex99** [comment]
Mending and unbreaking exist. Repair materials arent super expensive either
