### ISSUE TITLE
[1.20.2]Neoforge can‘t load DivineRPG 1.10.7.3

### ISSUE THREAD

**Issue by dongdong25000** [DivineRPG/DivineRPG#658]
![X85Z@9B)2K4KGAATJ{}UN_O](https://github.com/DivineRPG/DivineRPG/assets/138014027/c7fea0ea-a65e-4f01-9d8d-964ce8a5762e)

**Comment by velocityraptor-real** [comment]
please use 1.20.1 Neoforge instead. we also have a newer version available: DivineRPG 1.10.7.3
