### ISSUE TITLE
[1.20.1] Advanced Cori one shot kills player with any armor set

### ISSUE THREAD

**Issue by Spookygalore** [DivineRPG/DivineRPG#659]
The advanced Cori will kill you in one shot once engaged even with any armor/ and or the modded armor sets in DivineRPG, makes exploring the skythern dimension impossible to explore. Overall making progression in the mod impossible. I also could not find the config to edits its damage output in the config files. Also one shots even with enchanted armor 

I attached a video using apalachia armor since that’s the set before skythern: https://drive.google.com/file/d/1Y4xGMT8dDivFB5Zs8swcYf39XDcUuWTX/view?usp=drivesdk

**Comment by velocityraptor-real** [comment]
Advanced coris do not one hit players with apalachia armor in latest version: DivineRPG 1.10.7.4
