### ISSUE TITLE
Spawn mobs bug ?

### ISSUE THREAD

**Issue by Matheusgarcia2000** [DivineRPG/DivineRPG#662]
Does anyone know if the light level influences the spawn of mobs in the divine rpg? I noticed that when I illuminate the caves the spawn stopped occurring. And also what is the best Y to enter these mobs? I'm playing on Minecraft version 1.20.1 and the encounters I had with them were very rare. Thanks!

**Comment by velocityraptor-real** [comment]
Not a bug. Works as intended. Different mobs have different spawn conditions. Overworld cave mobs for example only spawn in dark areas, and some deep cave mobs only spawn below y = 0.
