### ISSUE TITLE
Help me solve the problem why the game crashes after I killed the dragon and jumped into the portal

### ISSUE THREAD

**Issue by Zweki67** [DivineRPG/DivineRPG#669]
[crash-2024-08-18_07_54_08-server.txt](https://github.com/user-attachments/files/16647296/crash-2024-08-18_07_54_08-server.txt)

**Comment by NicosaurusRex99** [comment]
could be 2 things. 1 if youve edited the config option for safe vethea swaps you may have put a capital letter in the true or false area, it should all be lower case. 
2. if your config option for safe vethea swaps is set to false swap it to true

**Comment by Zweki67** [comment]
> could be 2 things. 1 if youve edited the config option for safe vethea swaps you may have put a capital letter in the true or false area, it should all be lower case. 2. if your config option for safe vethea swaps is set to false swap it to true

But I didn’t touch the configs or configure DivineRPG

**Comment by NicosaurusRex99** [comment]
So my second suggestion is what id like you to try then get back to me

**Comment by Zweki67** [comment]
> So my second suggestion is what id like you to try then get back to me


Okay, how do I do this?

**Comment by Zweki67** [comment]
Everything seems to be figured out, I’m running to check

**Comment by Zweki67** [comment]
Thank you very much, it really helped!

**Comment by Xplodin** [comment]
this is still an issue regardless of config

**Comment by NicosaurusRex99** [comment]
Update to DivineRPG version 1.10.7.6. should be fixed

**Comment by raamochka** [comment]
I can’t access the server after moving from the End to the Overworld. I’ve identified the problem but can’t figure out how to fix it. There are probably two possible causes:

If you’ve edited the configuration parameter for Vethea’s secure exchanges, you might have used capital letters in the true or false field — everything must be in lowercase.

If the configuration parameter for Vethea’s secure exchanges is set to false, change it to true.
