### ISSUE TITLE
Bug with divine bow`s

### ISSUE THREAD

**Issue by Shadow232** [DivineRPG/DivineRPG#67]
Bug with divine bow`s:

Take item frame, put it to wall, after that put to frame any item, after take bow from divineRPG mod and just pull to frame, item will drop.

**Comment by RadioactiveStud** [comment]
I don't understand. Item frames work fine for me.

**Comment by Eternaldoom** [comment]
This isn't a real issue. You are either shooting an arrow at the frame, making it drop, or replacing the item with a bow. Both of these are intended vanilla mechanics.
