### ISSUE TITLE
Ender Triplets (And Watchers) in Thaumcraft 4 Dimension

### ISSUE THREAD

**Issue by ReberSob** [DivineRPG/DivineRPG#671]
Ender Triplets and Ender Watchers spawn in Thaumcraft 4 Dimension
Game version: 1.7.10
Mod version: 1.4.1.5
Biome: Eldritch 

How to fix it?

Cfg:
DRPG
dimension {
   ### dimension {
    I:"Apalachia biome ID"=250
    I:"Apalachia dimension ID"=52
    I:"Arcana biome ID"=249
    I:"Arcana dimension ID"=56
    I:"Eden biome ID"=248
    I:"Eden dimension ID"=50
    I:"Iceika biome ID"=247
    I:"Iceika dimension ID"=57
    B:"Keep loading Apalachia"=false
    B:"Keep loading Arcana"=false
    B:"Keep loading Eden"=false
    B:"Keep loading Iceika"=false
    B:"Keep loading Mortum"=false
    B:"Keep loading Skythern"=false
    B:"Keep loading The Wildwood"=false
    B:"Keep loading Vethea"=false
    I:"Mortum biome ID"=246
    I:"Mortum dimension ID"=54
    I:"Skythern biome ID"=245
    I:"Skythern dimension ID"=53
    I:"Vethea biome ID"=244
    I:"Vethea dimension ID"=55
    I:"Wildwood biome ID"=243
    I:"Wildwood dimension ID"=51

Thaum
### biomes {
    # Eerie biome id
    I:biome_eerie=194

    # Eldritch Lands biome id
    I:biome_eldritch=200

    # Magical Forest biome id
    I:biome_magical_forest=193

    # Taint biome id
    I:biome_taint=192

    # higher values increases number of magical forest biomes. If you are using biome addon mods you probably want to increase this weight quite a bit
    I:magical_forest_biome_weight=5
    I:outer_lands_dim=-42

    # higher values increases number of taint biomes. If you are using biome addon mods you probably want to increase this weight quite a bit
    I:taint_biome_weight=2

**Comment by NicosaurusRex99** [comment]
Triplets and watchers spawn in any biome that fits in the end type. so eldritch biome clearly uses the end type

**Comment by ReberSob** [comment]
> Triplets and watchers spawn in any biome that fits in the end type. so eldritch biome clearly uses the end type

How to change it?
