### ISSUE TITLE
Mobs not spawning in overworld 

### ISSUE THREAD

**Issue by Sorex20** [DivineRPG/DivineRPG#675]
I downloaded DivineRPG for 1.16.5, created world and there is no mobs, only in dimensions, what should i do?

**Comment by NicosaurusRex99** [comment]
I would like a bit more info. What version of forge, What version of divinerpg, what other mods do you have installed, is this server or just your pc?

**Comment by Sorex20** [comment]
> I would like a bit more info. What version of forge, What version of divinerpg, what other mods do you have installed, is this server or just your pc?

I think i found that problem was in another mod, so i guess problem solved
