### ISSUE TITLE
Divine RPG Potentially causing my game to crash?

### ISSUE THREAD

**Issue by Progglee** [DivineRPG/DivineRPG#677]
Hello,

I was just leaving the end and got to that loading screen and then my game crashed I have attached the crash report below. Any help would be greatly appreciated thank you :D 
I would have pasted the crash report but there is too many characters haha

This is the first part of the crash report.
The game crashed whilst colliding entity with block
Error: java.lang.NullPointerException: Cannot invoke "divinerpg.capability.DimensionalInventory.saveInventory(net.minecraft.world.entity.player.Player, String)" because "d" is null

The full one is below 

[crash-2024-10-02_18.22.01-server.txt](https://github.com/user-attachments/files/17234112/crash-2024-10-02_18.22.01-server.txt)

**Comment by NicosaurusRex99** [comment]
in the config options try change saferVetheaInventory to true and see if it still happens

**Comment by Rattle189** [comment]
Experienced the same issue moments ago and changing that in the configuration file has helped fixed this issue for my server.

**Comment by NicosaurusRex99** [comment]
Update to DivineRPG version 1.10.7.6. should be fixed Same as #669
