### ISSUE TITLE
How to remove biome conditions for mobs?

### ISSUE THREAD

**Issue by Necumate** [DivineRPG/DivineRPG#683]
Is it possible to make Enthralled Dramcryx to spawn regardless the type of cave?
I have same issue where's 4 worldgen mod installed (Regions Unexplored, terralith+tectonic, biomes o plenty), so it's significally reduce spawnrate. Unfortunately, i can't get how to use Incontrol

**Comment by NicosaurusRex99** [comment]
override the datapacks
