### ISSUE TITLE
Crash issues on minecraft 1.7.10

### ISSUE THREAD

**Issue by ShepHardT800** [DivineRPG/DivineRPG#688]
I played minecraft version 1.7.10 and encountered a problem that in Eden the game starts to lag terribly and then crashes. Through experience, I found out that the problem is due to the Bunnies. Also in the Dungeon of Arcana the game lags and crashes due to the arcanium extractor. I know there was an update recently that fixed old bugs, but it didn't fix my problem personally.
And yes, these bugs exist even without any additional mods.

**Comment by NicosaurusRex99** [comment]
The bunny is a known bug, can you send a crash report through please

**Comment by ShepHardT800** [comment]
[Uploading latest.log…]()
[Uploading hs_err_pid20901.log…]()

**Comment by ShepHardT800** [comment]
[latest.log.zip](https://github.com/user-attachments/files/17878352/latest.log.zip)
[hs_err_pid20901.log.zip](https://github.com/user-attachments/files/17878354/hs_err_pid20901.log.zip)

**Comment by charleadev** [comment]
bunnies lagging in 1.7.10 is a known issue and idk how to fix it. as for the arcanium extractor/demon furnace/other model-based blocks you can fix this by updating your java/allocating more memory to the game. in the meantime i'd recommend installing the BadMobs mod to disable Bunnies from spawning

**Comment by ShepHardT800** [comment]
Yes, I understand you. But is it possible to recreate the mob again, or then you will have to rewrite the entire mod code? Or have you already tried this option but it didn't work?

**Comment by NicosaurusRex99** [comment]
> Yes, I understand you. But is it possible to recreate the mob again, or then you will have to rewrite the entire mod code? Or have you already tried this option but it didn't work?

Its not quite as easy as just "recreate" it but we can look into what causes it

**Comment by NicosaurusRex99** [comment]
Either way i have refactored some things in the bunny. It probably wont make a major difference but only time will tell

e2ebaa6

**Comment by charleadev** [comment]
i just playtested it and i didnt notice any lag even after spawning over 20 bunnies so i think its fixed now

**Comment by NicosaurusRex99** [comment]
Additionally ive tried to make some changes in the arcanium extractor, no promises that itll make your game run any better but ive tried
[27d5dee](https://github.com/DivineRPG/DivineRPG/commit/27d5dee90a0ee4440c3df06edf0af04c8f07674b)

**Comment by ShepHardT800** [comment]
Tbh I don't know much about Github. Should I wait for an update on Curseforge or can I download the patched version directly from GitHub?

**Comment by charleadev** [comment]
the patched version has already been built, im just waiting for velocity to upload it on github

**Comment by NicosaurusRex99** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/official-divinerpg/files/5935793
Should be fixed here
