### ISSUE TITLE
Crash on server when you portal 

### ISSUE THREAD

**Issue by Gasai2225** [DivineRPG/DivineRPG#689]
Kicks the player out and prevents them from entering when teleporting from the ender world to the normal world through a portal
[server_log.txt](https://github.com/user-attachments/files/17923954/server_log.txt)

**Comment by NicosaurusRex99** [comment]
Same as #669
Change the config option for saferVetheaInventory to true and youll be fine

**Comment by Gasai2225** [comment]
THX, all works

**Comment by NicosaurusRex99** [comment]
Update to DivineRPG version 1.10.7.6. should be fixed
