### ISSUE TITLE
DivineRPG seems toe cause server DC on loading into Overworld after Ender Dragon kill.

### ISSUE THREAD

**Issue by Grootloops33** [DivineRPG/DivineRPG#691]
Exception caught during firing event: Cannot invoke "divinerpg.capability.DimensionalInventory.saveInventory(net.minecraft.world.entity.player.Player, String)" because "d" is null
Full stacktrace: https://pastebin.com/ySaNpi4Y

Not sure what is causing this, does not seem to cause a crash for everyone, just 1 player.

Full modlist: 
[FTB Teams (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-teams-forge)
[ModernFix (by embeddedt)](https://www.curseforge.com/minecraft/mc-mods/modernfix)
[Jumbo Furnace (by Commoble)](https://www.curseforge.com/minecraft/mc-mods/jumbo-furnace)
[Resourceful Config (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/resourceful-config)
[Moonlight Lib (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/selene)
[Bookshelf (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/bookshelf)
[ManyIdeas Doors (by GeheimagentNr1)](https://www.curseforge.com/minecraft/mc-mods/manyideas-doors)
[Unusual Fish Mod (by Coda1552)](https://www.curseforge.com/minecraft/mc-mods/unusual-fish-mod)
[Alex's Delight (by NCP_Bails)](https://www.curseforge.com/minecraft/mc-mods/alexs-delight)
[Additional Lanterns (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/additional-lanterns)
[Enchantment Descriptions (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions)
[Illagers Wear Armor (by almightytallestred)](https://www.curseforge.com/minecraft/mc-mods/illagers-wear-armor)
[Spice of Life: Carrot Edition (by lordcazsius)](https://www.curseforge.com/minecraft/mc-mods/spice-of-life-carrot-edition)
[FTB Ultimine (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-ultimine-forge)
[Explorer's Compass (by Chaosyr)](https://www.curseforge.com/minecraft/mc-mods/explorers-compass)
[Fusion (Connected Textures) (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/fusion-connected-textures)
[Fastload (by StockiesLad)](https://www.curseforge.com/minecraft/mc-mods/fastload)
[HT's TreeChop (by hammertater)](https://www.curseforge.com/minecraft/mc-mods/treechop)
[Apotheotic Additions (by Bryce792)](https://www.curseforge.com/minecraft/mc-mods/apotheotic-additions)
[Configured (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/configured)
[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[Create: New Age (by nullBlade)](https://www.curseforge.com/minecraft/mc-mods/create-new-age)
[Falling Leaves (NeoForge/Forge) (by Cheaterpaul)](https://www.curseforge.com/minecraft/mc-mods/falling-leaves-forge)
[Apotheosis (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/apotheosis)
[Large Meals (An Add-on for Farmer's Delight) (by LostWiz08)](https://www.curseforge.com/minecraft/mc-mods/large-meals-an-add-on-for-farmers-delight)
[Tetra (by mickelus)](https://www.curseforge.com/minecraft/mc-mods/tetra)
[Upgrade Aquatic (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/upgrade-aquatic)
[Tetra Extras (by Vinnaxy)](https://www.curseforge.com/minecraft/mc-mods/tetra-extras)
[Mouse Tweaks (by YaLTeR)](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)
[Max Health Fix (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/max-health-fix)
[SeasonHUD (by IanAnderson)](https://www.curseforge.com/minecraft/mc-mods/seasonhud)
[Create: Easy Structures (by M_Productions)](https://www.curseforge.com/minecraft/mc-mods/create-easy-structures)
[Lithostitched (by Apollo)](https://www.curseforge.com/minecraft/mc-mods/lithostitched)
[Terralith (by Starmute)](https://www.curseforge.com/minecraft/mc-mods/terralith)
[Searchables (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/searchables)
[Dynamic Lights (by atomicstrykergrumpy)](https://www.curseforge.com/minecraft/mc-mods/dynamic-lights)
[Auto Leveling (by Daripher)](https://www.curseforge.com/minecraft/mc-mods/auto-leveling)
[Apothic Attributes (AttributesLib) (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/apothic-attributes)
[Farmers Structures (by BlackAuresArt)](https://www.curseforge.com/minecraft/mc-mods/farmers-structures)
[Recipes Library (by GeheimagentNr1)](https://www.curseforge.com/minecraft/mc-mods/recipes-library)
[More Delight (Forge & Neoforge) (by axperty)](https://www.curseforge.com/minecraft/mc-mods/more-delight-forge)
[Icarus (by Cammie)](https://www.curseforge.com/minecraft/mc-mods/icarus)
[CraftTweaker (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/crafttweaker)
[Sword Displays (by sokratis12GR)](https://www.curseforge.com/minecraft/mc-mods/sword-displays)
[When Dungeons Arise - Forge! (by Aureljz)](https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise)
[AttributeFix (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/attributefix)
[Quark Delight (by nocubeyt)](https://www.curseforge.com/minecraft/mc-mods/quark-delight)
[Better Ping Display (by Quintinity)](https://www.curseforge.com/minecraft/mc-mods/better-ping-display)
[Immersive Armors [Fabric/Forge] (by Conczin)](https://www.curseforge.com/minecraft/mc-mods/immersive-armors)
[Gateways to Eternity (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/gateways-to-eternity)
[Almost Unified (by AlmostReliable)](https://www.curseforge.com/minecraft/mc-mods/almost-unified)
[JEITweaker (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/jeitweaker)
[Mendable Anvils (by MincraftEinstein)](https://www.curseforge.com/minecraft/mc-mods/mendable-anvils)
[Potion Blender (by motivational_dragon)](https://www.curseforge.com/minecraft/mc-mods/potion-blender)
[Curios API (Forge/NeoForge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curios)
[Athena (by CodexAdrian)](https://www.curseforge.com/minecraft/mc-mods/athena)
[Ice and Fire: Dragons (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragons)
[SuperMartijn642's Core Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib)
[Resourceful Lib (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/resourceful-lib)
[RightClickHarvest (by jamalam360)](https://www.curseforge.com/minecraft/mc-mods/rightclickharvest)
[Lionfish API (by mcl_ender)](https://www.curseforge.com/minecraft/mc-mods/lionfish-api)
[Create Deco (by talrey)](https://www.curseforge.com/minecraft/mc-mods/create-deco)
[Tetranomicon (by syrikalis)](https://www.curseforge.com/minecraft/mc-mods/tetranomicon)
[Ars Nouveau (by baileyholl2)](https://www.curseforge.com/minecraft/mc-mods/ars-nouveau)
[FTB Library (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-library-forge)
[Passive Skill Tree (by Daripher)](https://www.curseforge.com/minecraft/mc-mods/passive-skill-tree)
[Better Advancements (by way2muchnoise)](https://www.curseforge.com/minecraft/mc-mods/better-advancements)
[Iceberg [Neo/Forge] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/iceberg)
[Common Network (by Mysticdrew)](https://www.curseforge.com/minecraft/mc-mods/common-network)
[Kotlin for Forge (by thedarkcolour)](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge)
[Realm RPG: Sea Dwellers (by nocubeyt)](https://www.curseforge.com/minecraft/mc-mods/nocubes-sea-dwellers)
[My Nether's Delight (by soytutta)](https://www.curseforge.com/minecraft/mc-mods/my-nethers-delight)
[Waystones (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/waystones)
[Fancy Block Particles - Renewed (by Hantonik)](https://www.curseforge.com/minecraft/mc-mods/fbp-renewed)
[Citadel (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/citadel)
[Patchouli (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/patchouli)
[CreateTweaker (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/createtweaker)
[Loot Beams: Relooted! (by shiroroku)](https://www.curseforge.com/minecraft/mc-mods/loot-beams)
[Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)
[Corpse (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/corpse)
[Storage Drawers (by Texelsaur)](https://www.curseforge.com/minecraft/mc-mods/storage-drawers)
[Stony Cliffs Are Cool (by bebebea_loste)](https://www.curseforge.com/minecraft/mc-mods/stony-cliffs-are-cool)
[Zeta (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/zeta)
[TerraBlender (Forge) (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/terrablender)
[Puzzles Lib [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib)
[Nature's Compass (by Chaosyr)](https://www.curseforge.com/minecraft/mc-mods/natures-compass)
[Cultural Delights (by NCP_Bails)](https://www.curseforge.com/minecraft/mc-mods/cultural-delights)
[Embeddium (by FiniteReality)](https://www.curseforge.com/minecraft/mc-mods/embeddium)
[Blueprint (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/blueprint)
[Item Borders [Neo/Forge] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/item-borders)
[Create: Better Villager (by Reggarf)](https://www.curseforge.com/minecraft/mc-mods/create-better-villager)
[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Clean Swing Through Grass (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/clean-swing-through-grass)
[Create: Extended Cogwheels (by Rabbitminers)](https://www.curseforge.com/minecraft/mc-mods/create-extended-cogs)
[Item Production Lib (by Daripher)](https://www.curseforge.com/minecraft/mc-mods/item-production-lib)
[Fast Leaf Decay (by olafskiii)](https://www.curseforge.com/minecraft/mc-mods/fast-leaf-decay)
[Farmer's Respite (by lumpazl)](https://www.curseforge.com/minecraft/mc-mods/farmers-respite)
[Extended Crafting (by BlakeBr0)](https://www.curseforge.com/minecraft/mc-mods/extended-crafting)
[DivineRPG (Official) (by Velocityraptor)](https://www.curseforge.com/minecraft/mc-mods/official-divinerpg)
[Apothic Amendments - Enchanting (by MadSciSlack)](https://www.curseforge.com/minecraft/mc-mods/apothic-amendments-enchanting)
[First-person Model (Forge/Fabric) (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/first-person-model)
[Oculus (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/oculus)
[FerriteCore ((Neo)Forge) (by malte0811)](https://www.curseforge.com/minecraft/mc-mods/ferritecore)
[Storage Drawers Extras (by Texelsaur)](https://www.curseforge.com/minecraft/mc-mods/storage-drawers-extras)
[Botarium (by CodexAdrian)](https://www.curseforge.com/minecraft/mc-mods/botarium)
[Sophisticated Core (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-core)
[Celestisynth: Wishes and Hells (by aquextheseal)](https://www.curseforge.com/minecraft/mc-mods/celestisynth)
[Pehkui (by Virtuoel)](https://www.curseforge.com/minecraft/mc-mods/pehkui)
[FindMe (by Buuz135)](https://www.curseforge.com/minecraft/mc-mods/findme)
[Integrated API (by CraisinLord)](https://www.curseforge.com/minecraft/mc-mods/integrated-api)
[Serene Seasons (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/serene-seasons)
[Overflowing Bars [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/overflowing-bars)
[Jade 🔍 (by Snownee)](https://www.curseforge.com/minecraft/mc-mods/jade)
[Create: Connected (by Lysine)](https://www.curseforge.com/minecraft/mc-mods/create-connected)
[mutil (by mickelus)](https://www.curseforge.com/minecraft/mc-mods/mutil)
[Xaero's Minimap (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap)
[Just Enough Resources (JER) (by way2muchnoise)](https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer)
[Supplementaries (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/supplementaries)
[Embeddium++ (by SrRapero720)](https://www.curseforge.com/minecraft/mc-mods/embeddiumplus)
[Overloaded Armor Bar (by tfarecnim)](https://www.curseforge.com/minecraft/mc-mods/overloaded-armor-bar)
[Cucumber Library (by BlakeBr0)](https://www.curseforge.com/minecraft/mc-mods/cucumber)
[Lootr (Forge & NeoForge) (by Noobanidus)](https://www.curseforge.com/minecraft/mc-mods/lootr)
[Farmer's Delight (by vectorwing)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight)
[Chipped (by terrariumearth)](https://www.curseforge.com/minecraft/mc-mods/chipped)
[Create Slice & Dice (by possible_triangle)](https://www.curseforge.com/minecraft/mc-mods/slice-and-dice)
[Amendments (by plantspookable)](https://www.curseforge.com/minecraft/mc-mods/amendments)
[Sophisticated Storage (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-storage)
[Xaero's World Map (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map)
[Prism [Neo/Forge] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/prism-lib)
[Better Days (by wendall911)](https://www.curseforge.com/minecraft/mc-mods/betterdays)
[Just Zoom (by Keksuccino)](https://www.curseforge.com/minecraft/mc-mods/just-zoom)
[Immersive Aircraft [Fabric/Forge] (by Conczin)](https://www.curseforge.com/minecraft/mc-mods/immersive-aircraft)
[Create: Crystal Clear (by singularity_cyvack)](https://www.curseforge.com/minecraft/mc-mods/create-crystal-clear)
[Placebo (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/placebo)
[L_Ender 's Cataclysm (by mcl_ender)](https://www.curseforge.com/minecraft/mc-mods/lendercataclysm)
[Thaumon (by moonst0ne)](https://www.curseforge.com/minecraft/mc-mods/thaumon)
[Architectury API (Fabric/Forge/NeoForge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[Caelus API (Forge/NeoForge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/caelus)
[Integrated Dungeons and Structures (by CraisinLord)](https://www.curseforge.com/minecraft/mc-mods/idas)
[Realm RPG: Dragon Wyrms (by nocubeyt)](https://www.curseforge.com/minecraft/mc-mods/realm-rpg-dragon-wyrms)
[Botany Pots (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/botany-pots)
[Sophisticated Backpacks (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks)
[ChoiceTheorem's Overhauled Village (by ChoiceTheorem)](https://www.curseforge.com/minecraft/mc-mods/choicetheorems-overhauled-village)
[Summoning Rituals (by Relentless)](https://www.curseforge.com/minecraft/mc-mods/summoningrituals)
[Butcher's Delight (by onuadan)](https://www.curseforge.com/minecraft/mc-mods/butchers-delight)
[Balm (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm)
[Extreme sound muffler - (Neo)Forge (by LeoBeliik)](https://www.curseforge.com/minecraft/mc-mods/extreme-sound-muffler)
[Ars Elemental (by Alexth99)](https://www.curseforge.com/minecraft/mc-mods/ars-elemental)
[Create : Teleporters (by Chilllliii)](https://www.curseforge.com/minecraft/mc-mods/create-teleporters)
[Create: Vintage Improvements (by Negodya1)](https://www.curseforge.com/minecraft/mc-mods/create-vintage-improvements)
[Client Tweaks (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/client-tweaks)
[Tetra's Delight (by hyperlynx01)](https://www.curseforge.com/minecraft/mc-mods/tetras-delight)
[Deeper and Darker (by KyaniteMods)](https://www.curseforge.com/minecraft/mc-mods/deeperdarker)
[Konkrete [Forge/NeoForge] (by Keksuccino)](https://www.curseforge.com/minecraft/mc-mods/konkrete)
[End's Delight (by foggyhillside)](https://www.curseforge.com/minecraft/mc-mods/ends-delight)
[Integrated Stronghold (by CraisinLord)](https://www.curseforge.com/minecraft/mc-mods/integrated-stronghold)
[Ender's Delight (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/enders-delight)
[FTB Quests (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-quests-forge)
[Ocean's Delight (by scouter567)](https://www.curseforge.com/minecraft/mc-mods/oceans-delight)
[Attributizer (by TheRealJackiecrazy)](https://www.curseforge.com/minecraft/mc-mods/attributizer)
[Refined Storage (by raoulvdberge)](https://www.curseforge.com/minecraft/mc-mods/refined-storage)
[Cataclysm Apotheosis Addon (by kurokogedesu)](https://www.curseforge.com/minecraft/mc-mods/cataclysm-apotheosis-addon)
[MythicBotany (by noeppi_noeppi)](https://www.curseforge.com/minecraft/mc-mods/mythicbotany)
[More Tetra Materials (by Hydra_Gen)](https://www.curseforge.com/minecraft/mc-mods/more-tetra-materials)
[Tectonic (by Apollo)](https://www.curseforge.com/minecraft/mc-mods/tectonic)
[tetracelium (by mickelus)](https://www.curseforge.com/minecraft/mc-mods/tetracelium)
[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[Botania (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/botania)
[LibX (by noeppi_noeppi)](https://www.curseforge.com/minecraft/mc-mods/libx)
[Butcher's Delight Foods (by onuadan)](https://www.curseforge.com/minecraft/mc-mods/butchers-delight-foods)
[Domum Ornamentum (by OrionOnline)](https://www.curseforge.com/minecraft/mc-mods/domum-ornamentum)
[Underground Villages, Stoneholm (by Reggarf)](https://www.curseforge.com/minecraft/mc-mods/underground-villages-stoneholm)
[Controlling (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/controlling)
[ManyIdeas Core (by GeheimagentNr1)](https://www.curseforge.com/minecraft/mc-mods/manyideas-core)
[GlitchCore (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/glitchcore)
[Create Crafts & Additions (by MRHminer)](https://www.curseforge.com/minecraft/mc-mods/createaddition)
[Create Central Kitchen (by DragonsPlus)](https://www.curseforge.com/minecraft/mc-mods/create-central-kitchen)
[Quark (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/quark)
[playerAnimator (by KosmX)](https://www.curseforge.com/minecraft/mc-mods/playeranimator)
[Apotheotic Creation (by themaxpowa)](https://www.curseforge.com/minecraft/mc-mods/apotheotic-creation)
[Open Loader (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/open-loader)
[Monster Plus (by Nitespring)](https://www.curseforge.com/minecraft/mc-mods/monster-plus)
[Alex's Mobs (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/alexs-mobs)
[Create (by simibubi)](https://www.curseforge.com/minecraft/mc-mods/create)
[Polymorph (Fabric/Forge/Quilt) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/polymorph)

**Comment by NicosaurusRex99** [comment]
Same issue as #669

**Comment by NicosaurusRex99** [comment]
Update to DivineRPG version 1.10.7.6. should be fixed
