### ISSUE TITLE
The error remains divinerpg-1.10.7.6

### ISSUE THREAD

**Issue by oleg12054** [DivineRPG/DivineRPG#694]
error when switching from the ENDER world to the WORLD:

[latest.log](https://github.com/user-attachments/files/18064303/latest.log)
[latest0.log](https://github.com/user-attachments/files/18064432/latest0.log)

**Comment by oleg12054** [comment]
The problem is that some kind of error starts to loop because of this, the world "breaks down", the player does not fully load into the "WORLD" world he has crossed

**Comment by NicosaurusRex99** [comment]
This looks like its a issue with reskillable

**Comment by oleg12054** [comment]
You were right.
