### ISSUE TITLE
DivineRPG 1.10.7.6 works on forge but..

### ISSUE THREAD

**Issue by Xplodin** [DivineRPG/DivineRPG#698]
Its listed as NeoForge only and not both. which makes launchers decide to install the previous version (if on forge)
And the previous update has the vethea bug.

mc 1.20.1 forge 47.3.0
simple fix: make the last 1.20.1 file forge and neoforge compatible. They both work

**Comment by NicosaurusRex99** [comment]
We dont support forge anymore

**Comment by Xplodin** [comment]
Okay. My point still stands about compatibility. 
Leading existing forge users on 1.20.1 to be stuck with a 'broken' update is wild.
Only fix is disabling some option in the config which is what the neoforge update only did.

**Comment by NicosaurusRex99** [comment]
It works on older forge versions, thats the  real issue
