### ISSUE TITLE
Divine furnace small bug

### ISSUE THREAD

**Issue by Shadow232** [DivineRPG/DivineRPG#73]
Divine furnace small bug:
then you put item to fuel slot, this item removes automatically...

**Comment by RadioactiveStud** [comment]
Any item placed into invisible fuel slot will be deleted if you are cooking.

**Comment by Eternaldoom** [comment]
this is only with infinite fuel furnaces? do they have an invisible slot?

**Comment by RadioactiveStud** [comment]
I'm pretty sure they all are infinite. Yes

**Comment by Eternaldoom** [comment]
They arent all

**Comment by RadioactiveStud** [comment]
Well then I didn't test any of those.

**Comment by Shadow232** [comment]
i checked them, and they removes by 1 hit, not like vanilla, and this furnice from divinerpg have only slot for fuel item`s..
