### ISSUE TITLE
Mob crash !! Hot bug

### ISSUE THREAD

**Issue by Shadow232** [DivineRPG/DivineRPG#74]
In ender dimension, then you attack or me attack mob Ayeraco_Horde, minecraft will crash... ( about how it crashes i don`t know, because then i login it automatically crash :D

Crash:
http://pastebin.com/aPbfQT8t

**Comment by Eternaldoom** [comment]
@krwminer, have you happened to test this? I haven't been able to reproduce it in the dev environment.

**Comment by Shadow232** [comment]
i to didn`t understand, for the beginning all was great, we killed dragon, some mobs after that spawned ayeraco_horde and make craches :)

**Comment by krwminer** [comment]
I used the horn last night in a SP copy of the MP world we are playing. It did not crash, but the Ayeraco_Horde does not spawn correctly in Creative mode. They just hover a distance over the end and you can not hit them.

Once I went to Survival, all except the Yellow one came down and I killed it. But the Yellow one never came down. :(
