### ISSUE TITLE
Missing recipes for all diamond chunks

### ISSUE THREAD

**Issue by krwminer** [DivineRPG/DivineRPG#75]

**Comment by Eternaldoom** [comment]
I was actually gonna ask people what they thought of the recipes and if there should be new ones. Do you think the old recipes are too expensive, or should they stay?

**Comment by Shadow232** [comment]
normal... better if make armor balance :) and in divine rpg is some bugs with texture, then i open NEI in last page here WildWood item`s were without texture..

**Comment by krwminer** [comment]
The diamond part is not expensive. You have a massive amount of diamond by the time you are considering using the chunks.

**Comment by Eternaldoom** [comment]
Not the diamond, the other material. For example, a grey one takes 8 shadow bars

**Comment by RadioactiveStud** [comment]
@Shadow232 Update to the latest version (src). If the problem is still there let me know.
What do we use the chunks for?

**Comment by Eternaldoom** [comment]
Dyeing swords and armor

**Comment by krwminer** [comment]
I think shadow bars have no place in recipes for color. changes.

**Comment by Eternaldoom** [comment]
Well they should stay, the question is how many should be used. I guess I'll make it just 1

**Comment by RadioactiveStud** [comment]
1 sounds good.
