### ISSUE TITLE
Sharks are not spawning or spawning and falling out of the world

### ISSUE THREAD

**Issue by krwminer** [DivineRPG/DivineRPG#78]
Sharks and Whale seem to freely move on land.

**Comment by krwminer** [comment]
Also the spawn rates are still too high. :(

**Comment by RadioactiveStud** [comment]
With the current settings I see some whales but I'm not seeing any sharks. What about you?

**Comment by krwminer** [comment]
I will test when I get home from work.

I recall that in DRPG 1.4.7 it was pretty rare to see a whale and/or shark.

**Comment by RadioactiveStud** [comment]
I know it wasn't common at least.

**Comment by krwminer** [comment]
Whales are better, I have not seen any sharks either.

**Comment by RadioactiveStud** [comment]
I will turn the sharks spawn rate way up and test it. If they still don't spawn we have a different problem.

**Comment by RadioactiveStud** [comment]
Yea

**Comment by Eternaldoom** [comment]
They were before, and I don't think that code got changed

**Comment by RadioactiveStud** [comment]
#BlameMojang

**Comment by Eternaldoom** [comment]
*facepalm*

**Comment by krwminer** [comment]
If you change the size back to the way it used to be, sharks spawn again.

        this.setSize(0.95F, 0.95F);

Might yo have set it too small at the current setting?

        this.setSize(0.75F, 0.50F);

Is this import used?

import net.minecraft.potion.Potion;

**Comment by Eternaldoom** [comment]
hmm... it appears that they might be spawning, but falling through water

**Comment by RadioactiveStud** [comment]
This should be closed now right?

**Comment by Eternaldoom** [comment]
well the sharks still arent spawning

**Comment by RadioactiveStud** [comment]
Oh I thought the size fixed it... :(

**Comment by badtzmaru** [comment]
i have not yet seen any crabs either. in 1.4.7 they were fairly common. Is there a specific biome that they should be spawning in other than ocean?

**Comment by Eternaldoom** [comment]
Beach. I've seen lots of them

**Comment by krwminer** [comment]
Actually, now that mention it. I have not seen Crabs on the beach either. I have only seen King Crabs.

**Comment by krwminer** [comment]
The Divine Crab Spawner that we found has been working fine.

**Comment by krwminer** [comment]
When I first started our test world, I was surrounded by Crabs on the beach where I spawned. Some time shortly after that I have not seen them. I just roamed around a test world with night vision potion active so I could see to the bottom of the ocean.

I did not see any Sharks spawn in the Ocean or Crabs on the beaches.

I wish minecraft had better spawning control. :/
