### ISSUE TITLE
DivineRPG mobs do not spawn in biomes o' plenty worlds

### ISSUE THREAD

**Issue by badtzmaru** [DivineRPG/DivineRPG#84]
i am running a server that uses biomes o' plenty as well as realistic worldgen, and non of the divinerpg mobs are spawning in the non vanilla biomes.

**Comment by krwminer** [comment]
Are you running the latest version from github?

I have been testing with some friends on private server with Biome O Plenty for over a weeks and the mobs have been spawning fine in Biome O Plenty biomes.

**Comment by Eternaldoom** [comment]
yeah this was fixed.

**Comment by badtzmaru** [comment]
alright thank you
