### ISSUE TITLE
Some texture problems

### ISSUE THREAD

**Issue by Shadow232** [DivineRPG/DivineRPG#85]
http://prntscr.com/5th6ep

item list:
WildWood Blade
WildWood Slicer
WildWood Phaser
WildWood Bow
WildWood Pickaxe
WildWood Shovel
WildWood Axe
WildWood Shickaxe
WildWood Arrow
WildWood Blitz

**Comment by krwminer** [comment]
I can not reproduce this with the latest build. Are you sure you did a "gradlew clean build"?

**Comment by Shadow232** [comment]
yes..

**Comment by Eternaldoom** [comment]
This was already fixed
