### ISSUE TITLE
Reciepe slime sword bug

### ISSUE THREAD

**Issue by Shadow232** [DivineRPG/DivineRPG#86]
nice bug :D 

http://prntscr.com/5tk51f

**Comment by krwminer** [comment]
I can not reproduce this with the latest build. Are you sure you did a "gradlew clean build"?

**Comment by Shadow232** [comment]
yes, i didn`t only build it this last commit ( boss commit )

**Comment by Eternaldoom** [comment]
Can't reproduce this. The slime sword did have a duplicate recipe, but that's fixed and I'm not sure how it could have cause this.
