### ISSUE TITLE
ender sword not colorable using diamond chunks

### ISSUE THREAD

**Issue by badtzmaru** [DivineRPG/DivineRPG#92]
According to the wiki, you should be able to dye the ender sword colors by using different colors of diamond chunks. This is not working for me.
![2015-01-19_17 15 12](https://cloud.githubusercontent.com/assets/6172936/5810652/c8f51372-9ffe-11e4-90b5-122cf5bff1da.png)

**Comment by krwminer** [comment]
lol. Beat me to it. It was on my list to report tonight.
