### ISSUE TITLE
Wildwood Spawning broken

### ISSUE THREAD

**Issue by krwminer** [DivineRPG/DivineRPG#94]
Nothing is spawning in Wildwood except an occasional Moonwolf which spawns at 20 out of 200 health.

**Comment by krwminer** [comment]
Anyone have any ideas on this one? I spent some time looking into it and really did not get anywhere.

I was able to spawn the Wildwood Tomo in Eden, but was not able to spawn the Eden Tomo in Wildwood. The real head scratcher is that the Moonwoolf spawns, but nothing else.

**Comment by Eternaldoom** [comment]
This was an issue before, except wolfs didn't spawn, but it miraculously went away. I'm not sure why this is.

**Comment by krwminer** [comment]
Well then I guess it really did not go away as much as hid for a while.

I might play with it more tonight. Really sounds almost like a memory corruption type problem. Loose pointer or such. We will see.

**Comment by Eternaldoom** [comment]
fixed in 0bf98c4
