### ISSUE TITLE
Divine Dungeons with Caveclops

### ISSUE THREAD

**Issue by krwminer** [DivineRPG/DivineRPG#99]
A Divine Dungeon with a Caveclops spawner located above 25, (or so), will not spawn any Caveclops.

**Comment by Eternaldoom** [comment]
Well... That's because of the stupid getCanSpawnHere thing with spawners, but I'm going to remove caveclops dungeons anyway since they're an OP way to farm realmite.

**Comment by krwminer** [comment]
I am trying to tackle more spawning issues, but no luck so far. I guess I really need to look over minecrafts code for it. :/

**Comment by krwminer** [comment]
Ah... The Jungle Dramcryx is an excellent way to farm Jungle Shards also...

You should see the Grinder I made for it. It pushes them through a ceiling of lava flow and kills them, the dropped shards collect in a chest. No fuss, no mess, just stand there.

**Comment by Eternaldoom** [comment]
Yeah... I dunno. You need more jungle shards to make stuff though.

**Comment by krwminer** [comment]
Just thought I would let you know. :)

**Comment by krwminer** [comment]
Should reopen this bug or another one as a place holder until you implement the proper Divine Dungeon spawner? I just do not want to loose track of it.
